- x/payment/types/builder.go
> chore: add mutex on KeyringSigner for QueryAccount

- app/abci_test.go
- app/app.go
- app/module.go
- contrib/single-node.sh
- readme.md
- testutil/network/network.go
- x/payment/client/testutil/integration_test.go
- x/payment/keeper/keeper.go
use celes by default
closes https://github.com/celestiaorg/celestia-app/issues/158
---
> add stakedenom by deafult

- app/app.go
- app/module.go
> Micro Celes

- x/payment/types/errors.go
- x/payment/types/payformessage_test.go
- x/payment/types/wirepayformessage.go
- x/payment/types/wirepayformessage_test.go
> improve error handling

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/workflows/proto.yml
> Fixed typos

- x/qgb/orchestrator/relayer.go
- x/qgb/orchestrator/relayer_command.go
> adds NewRelayer method to QGB

- app/app.go
> chore: change account prefix to celestia instead of celes

- x/qgb/orchestrator/deploy_command.go
Closes https://github.com/celestiaorg/celestia-app/issues/403
> Fix qgb deploy command valset query

- app/app.go
- contrib/single-node.sh
- readme.md
- testutil/test_app.go
changes denom from celes -> tia
closes #279
> Change Denomination to tia

- .github/workflows/docker-build.yml
Closing https://github.com/celestiaorg/celestia-app/issues/424
> adds ephemeral cluster docker image build

- go.mod
- go.sum
bump sdk dependency to change default configs
related to 
https://github.com/celestiaorg/cosmos-sdk/pull/150
https://github.com/celestiaorg/cosmos-sdk/issues/151
closes: #XXXX
> Bump sdk to v1.1.1-sdk-v0.46.0 to change the default configs

- e2e/qgb/Makefile
- e2e/qgb/qgb_network.go
> Qgb e2e makefile

- x/qgb/keeper/query_valset.go
- x/qgb/orchestrator/evm_client.go
- x/qgb/orchestrator/querier.go
- x/qgb/orchestrator/relayer.go
- x/qgb/orchestrator/relayer_client.go
This fixes the relay mechanism for valsets in multiple validators' environment.
However, it does not address data commitments as the following issue is still not addressed https://github.com/celestiaorg/celestia-app/issues/370
> QGB update relayer to work in multiple validators environment

- e2e/qgb/Makefile
- e2e/qgb/README.md
- e2e/qgb/scripts/cleanup.sh
- e2e/qgb/scripts/deploy_qgb_contract.sh
- e2e/qgb/scripts/start_node_and_create_validator.sh
- e2e/qgb/scripts/start_orchestrator_after_validator_created.sh
- e2e/qgb/scripts/start_relayer.sh
Adds few cosmetics to the e2e scripts
> Scripts cosmetics

- docs/architecture/ADR-004-QGB_relayer_security.md
ADR for the relayer security issue we have.
> Add ADR-004-QGB_relayer_security

- x/qgb/keeper/keeper_data_commitment.go
A fix for a wrong check when setting the latest data commitment nonce
> Fixes set latest data commitment nonce

- e2e/qgb/deployer_test.go
- e2e/qgb/full_test.go
- e2e/qgb/relayer_test.go
- e2e/qgb/scripts/deploy_qgb_contract.sh
- x/qgb/orchestrator/deploy_command.go
- x/qgb/orchestrator/evm_client.go
- x/qgb/orchestrator/relayer.go
- x/qgb/orchestrator/relayer_command.go
Closes https://github.com/celestiaorg/celestia-app/issues/356 
https://github.com/celestiaorg/celestia-app/issues/362
> update the evm client to wait for transactions to be included

- e2e/qgb/celestia-app/config.toml
- e2e/qgb/celestia-app/genesis.json
- e2e/qgb/orchestrator_test.go
- e2e/qgb/qgb_network.go
- e2e/qgb/relayer_test.go
- go.sum
- testutil/common.go
- x/qgb/abci.go
- x/qgb/genesis.go
- x/qgb/keeper/keeper_attestation.go
- x/qgb/keeper/keeper_data_commitment.go
- x/qgb/keeper/query_general.go
- x/qgb/keeper/query_valset_confirm.go
- x/qgb/types/abi_consts.go
- x/qgb/types/errors.go
- x/qgb/types/genesis.go
- x/qgb/types/genesis_test.go
Probably closes the following: https://github.com/celestiaorg/celestia-app/issues/502 and https://github.com/celestiaorg/celestia-app/issues/339
> QGB better genesis initialization

- scripts/protocgen.sh
Closes:  https://github.com/celestiaorg/celestia-app/issues/507
Opens: https://github.com/celestiaorg/celestia-app/issues/553
> temporary fix for any import in query.pb.go

- .github/workflows/proto.yml
Resolves https://github.com/celestiaorg/celestia-app/issues/284
- This CI check [fails](https://github.com/rootulp/celestia-app/runs/7462101844?check_suite_focus=true) for https://github.com/rootulp/celestia-app/pull/2
> ci: run proto-gen

- x/qgb/orchestrator/querier.go
Removing some unnecessary comments
> QGB Remove unnecessary comment

- x/qgb/keeper/msg_server.go
- x/qgb/orchestrator/orchestrator.go
- x/qgb/orchestrator/querier.go
adds comments for valset nonce == 1 case and removes unnecessary msg_Server check on data commitments
> QGB handle nonce 1 case 

- .github/workflows/lint.yml
Resolves https://github.com/celestiaorg/celestia-app/issues/568
> fix: warning in golangci config

- .golangci.yml
- app/app.go
- app/export.go
- app/test/block_size_test.go
- app/test/process_proposal_test.go
- testutil/test_app.go
- x/payment/client/cli/tx.go
- x/payment/client/testutil/integration_test.go
- x/payment/types/builder_test.go
- x/payment/types/codec.go
- x/payment/types/events.go
- x/payment/types/genesis.go
- x/payment/types/payfordata_test.go
- x/payment/types/verify_sigs.go
- x/qgb/types/genesis.go
Resolves https://github.com/celestiaorg/celestia-app/issues/534
> ci: enable gofumpt

- app/app.go
- app/module.go
Resolves https://github.com/celestiaorg/celestia-app/issues/440
---
> Replace microceles with microtia

- readme.md
Inspired by the README badges on https://github.com/celestiaorg/celestia-node
> README badges

- .gitignore
> adds `.idea` to gitignore

- app/process_proposal.go
- app/test/process_proposal_test.go
Resolves https://github.com/celestiaorg/celestia-app/issues/595
Opens https://github.com/celestiaorg/celestia-core/issues/826
> Reject blocks with unsorted messages

- app/process_proposal.go
Closes https://github.com/celestiaorg/celestia-core/issues/810
> log proposerAddress for rejected blocks

- Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/633
> fix: remove test-build

- .github/workflows/test.yml
- Makefile
- scripts/test_cover.sh
Closes https://github.com/celestiaorg/celestia-app/issues/635
Closes https://github.com/celestiaorg/celestia-app/issues/639
> fix: remove unused build flags

- README.md
From https://github.com/celestiaorg/celestia-core#diagram
> docs: add diagram

- pkg/shares/info_reserved_byte.go
- pkg/shares/info_reserved_byte_test.go
Part of https://github.com/celestiaorg/celestia-app/issues/659
> Implement ParseInfoReservedByte

- pkg/prove/proof.go
- pkg/prove/proof_test.go
This PR copies and pastes the prove package from core to the app.
[permalink](https://github.com/celestiaorg/celestia-core/tree/212901fcfc0f5a095683b1836ea9e890cc952dc7/pkg/prove) to the original code in attempt to somewhat preserve the git history
closes #699
part of #698
> chore(pkg)!: move the prove package from core -> app

- app/prepare_proposal.go
- app/split_shares.go
- app/test/block_size_test.go
- app/test/prepare_proposal_test.go
- app/test/process_proposal_test.go
- app/test/split_shares_test.go
- pkg/appconsts/appconsts.go
- pkg/da/data_availability_header.go
- pkg/da/data_availability_header_test.go
- pkg/inclusion/nmt_caching_test.go
- pkg/prove/proof.go
- pkg/prove/proof_test.go
- pkg/shares/compact_shares_test.go
- pkg/shares/non_interactive_defaults_test.go
- pkg/shares/parse_compact_shares.go
- pkg/shares/parse_sparse_shares.go
- pkg/shares/share_merging.go
- pkg/shares/share_splitting.go
- pkg/shares/shares_test.go
- pkg/shares/sparse_shares_test.go
- pkg/shares/split_compact_shares.go
- pkg/shares/split_sparse_shares.go
- pkg/shares/utils.go
- pkg/wrapper/nmt_wrapper.go
- pkg/wrapper/nmt_wrapper_test.go
- x/payment/spec/docs.md
- x/payment/types/payfordata.go
- x/payment/types/payfordata_test.go
- x/payment/types/square_sizes.go
- x/payment/types/wirepayfordata.go
Part of https://github.com/celestiaorg/celestia-core/issues/841
Follow up to https://github.com/celestiaorg/celestia-core/pull/861
> feat: move share consts from celestia-core

- pkg/prove/proof.go
- pkg/shares/compact_shares_test.go
- pkg/shares/parse_compact_shares.go
- pkg/shares/parse_sparse_shares.go
- pkg/shares/shares.go
- pkg/shares/sparse_shares_test.go
- pkg/shares/split_compact_shares.go
- x/payment/types/payfordata_test.go
Spun out of https://github.com/celestiaorg/celestia-app/pull/691 because these improvements are can be reviewed & merged independently
> docs: improve doc comments

- app/estimate_square_size_test.go
- pkg/shares/compact_shares_test.go
- pkg/shares/shares_test.go
- pkg/shares/sparse_shares_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/755
> chore: prefer appconsts sizes over `100` or `1000`

- pkg/shares/parse_sparse_shares.go
- pkg/shares/shares_test.go
- pkg/shares/utils.go
- pkg/shares/utils_test.go
Addresses: https://github.com/celestiaorg/celestia-app/pull/810#discussion_r982671718
> chore: move `zeroPadIfNecessary` to utils

- .github/CODEOWNERS
Closes https://github.com/celestiaorg/celestia-app/issues/807
> chore: specs-staging CODEOWNERS

- README.md
- app/app.go
- app/test/block_size_test.go
- scripts/single-node.sh
- testutil/test_app.go
- x/payment/types/builder_options.go
- x/payment/types/payfordata_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/858
Opens https://github.com/celestiaorg/celestia-app/issues/862
> chore!: rename `TIA` to `CLS`

- scripts/single-node.sh
Closes https://github.com/celestiaorg/celestia-app/issues/897
This is pretty janky but may save a future dev time.
> fix: link to gnu-sed in single-node script

- README.md
Closes https://github.com/celestiaorg/celestia-app/issues/896
> docs: remove devnet code block

- pkg/shares/non_interactive_defaults_test.go
Closes https://github.com/informalsystems/audit-celestia/issues/23
> test: three additional test cases for FitsInSquare

- scripts/single-node.sh
fixes a left pver `--ethereum-address`
> fix: single node script

- pkg/inclusion/nmt_caching_test.go
addresses https://github.com/celestiaorg/celestia-app/pull/926#discussion_r1008319767
> chore: delete residual commented code

- docs/architecture/adr-004-qgb-relayer-security.md
- proto/qgb/genesis.proto
- third_party/proto/confio/proofs.proto
- third_party/proto/tendermint/crypto/proof.proto
- x/payment/spec/docs.md
- x/qgb/types/genesis.pb.go
Partially addresses https://github.com/celestiaorg/celestia-app/issues/931
> fix: typos

- Dockerfile
add make back to the docker file
> fix: add make back to the docker file

- docs/architecture/adr-008-square-size-independent-message-commitments.md
I added more details to the positive celestia-app changes section so that @musalbas has more information for https://github.com/celestiaorg/celestia-app/issues/941
> docs: add details to positive celestia-app changes

- cmd/celestia-appd/cmd/root.go
update the min fee to something non zero
> chore: change the default minimum gas fee to something non-zero

- e2e/qgb/celestia-app/genesis.json
- e2e/qgb/scripts/start_node_and_create_validator.sh
- x/qgb/orchestrator/config.go
- x/qgb/orchestrator/orchestrator.go
- x/qgb/orchestrator/orchestrator_command.go
Adds ability to specify transaction fees for orchestrator.
> feat: QGB support specifying Tx fee for orchestrator

- cmd/celestia-appd/cmd/root.go
Addressed minor feedback on #892 
- moved comments immediately above the line of code they are relevant to
- removed comment that doesn't provide more info than the line of code
- add link to issue
> chore: address feedback on #892

- Dockerfile
Analogous to https://github.com/celestiaorg/celestia-app/pull/1017 but to the QGB v1 branch
> fix: add git to Dockerfile build

- x/blob/client/cli/wirepayfordata.go
Closes https://github.com/celestiaorg/celestia-app/issues/981
> chore: improve payForBlob help text

- app/estimate_square_size.go
- app/estimate_square_size_test.go
- app/malleate_txs.go
- app/prepare_proposal.go
- go.mod
- go.sum
- pkg/appconsts/appconsts.go
- pkg/prove/proof.go
- pkg/shares/doc.go
- pkg/shares/parse_compact_shares.go
- pkg/shares/share_merging.go
- pkg/shares/share_splitting.go
- pkg/shares/shares.go
- pkg/shares/shares_test.go
- pkg/shares/split_compact_shares.go
- x/blob/types/payforblob_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1068
> feat!: remove evidence from data square

- app/estimate_square_size_test.go
Motivation: to fix CI on https://github.com/celestiaorg/celestia-app/pull/1083 per https://github.com/celestiaorg/celestia-app/pull/1083#issuecomment-1332611019
> fix: remove randomness from estimate square size test

- x/blob/types/errors.go
- x/blob/types/wirepayforblob.go
- x/blob/types/wirepayfordata_test.go
Closes https://github.com/informalsystems/audit-celestia/issues/8
> feat: throw error for zero blob size

- x/blob/types/payforblob.go
a user asked a question while digging through our code, so adding docs here. We should also probably document this outside of the code as well.
> chore: add docs to create commitment explaining the double namespace

- docs/architecture/adr-001-abci++-adoption.md
- docs/architecture/adr-002-qgb-valset.md
- docs/architecture/adr-003-qgb-data-commitments.md
- docs/architecture/adr-004-qgb-relayer-security.md
- docs/architecture/adr-005-qgb-reduce-state-usage.md
- docs/architecture/adr-006-non-interactive-defaults.md
- docs/architecture/adr-007-universal-share-prefix.md
- docs/architecture/adr-008-square-size-independent-message-commitments.md
- docs/architecture/adr-template.md
docs(improvement): minor grammar updates
> docs(improvement): minor grammar updates

- app/test/fuzz_abci_test.go
- pkg/shares/share_splitting.go
fixes the bug described in #1108
the modified tests fails on v0.10.x
> fix!: Share splitting bug v0.11.0

- pkg/shares/share_merging.go
- pkg/shares/shares.go
- pkg/shares/shares_test.go
- pkg/shares/split_sparse_shares.go
This is the celestia-app side of a fix for https://github.com/celestiaorg/celestia-node/issues/1448. It introduces `share.RawData()` for usage in celestia-node
> feat: implement `share.RawData()`

- app/test/process_proposal_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/831
> test: sequence start indicator tampering

- x/blob/keeper/gas_test.go
- x/blob/keeper/keeper.go
Addresses my late feedback on https://github.com/celestiaorg/celestia-app/pull/1095
> chore: address rootulp feedback on PR 1095

- pkg/shares/share_merging.go
- pkg/shares/share_merging_test.go
Part of https://github.com/celestiaorg/celestia-node/issues/1448
> feat: implement `ShareSequence.RawData()`

- .github/CODEOWNERS
- .github/auto_request_review.yml
- .github/workflows/housekeeping.yml
This PR makes a minor update to the `CODEOWNERS` file and implements the housekeeping flow for using the PR auto assignement feature.
Proof of GH working as expected
> .github: add housekeeping flow to utilize pr auto assignment for gh team

- app/process_proposal.go
- app/test/process_proposal_test.go
closes #1164 
blocked by #1167, as the tests won't pass until that's merged
> fix!: enforce that blocks with PFBs without a share index get rejected

- pkg/da/data_availability_header.go
- pkg/shares/share_splitting.go
- pkg/shares/shares.go
- pkg/shares/tail_padding.go
- pkg/shares/tail_padding_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1176
> chore: consolidate tail padding share

- app/write_square_test.go
Addresses feedback from https://github.com/celestiaorg/celestia-app/pull/1152#discussion_r1063430563
> fix: godoc for write square test

- x/qgb/abci_test.go
Closes: https://github.com/celestiaorg/celestia-app/issues/768
> Add more QGB abci test cases

- specs/src/rationale/message_block_layout.md
Closes https://github.com/celestiaorg/celestia-app/issues/1151
> specs: non-interactive default rules for reduced padding

- app/estimate_square_size.go
- app/estimate_square_size_test.go
- pkg/shares/share_merging.go
- pkg/shares/share_merging_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1222
> fix: `estimateCompactShares`

- specs/src/specs/data_structures.md
Closes https://github.com/celestiaorg/celestia-app/issues/1247
> docs: spec namespaced padding share

- app/test/integration_test.go
- x/blob/payforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/1133
> chore!: remove `gasLim` param in favor of `TxBuilderOption`

- app/app.go
- app/encoding/index_wrapper_decoder.go
- app/test/integration_test.go
- app/test/prepare_proposal_test.go
- x/blob/README.md
- x/blob/client/testutil/integration_test.go
- x/blob/types/builder_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1253
> chore: remove references to "malleated"

- x/blob/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/1268
> docs: update x/blob/README.md

- cmd/celestia-appd/cmd/root.go
- go.mod
- go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/1201
> chore: set the default keyring backend to `test`

- x/blob/types/errors.go
- x/blob/types/payforblob.go
- x/blob/types/payforblob_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1278
> feat: check that `MsgPayForBlob` components are non-zero

- pkg/shares/shares.go
- pkg/shares/shares_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1280
> fix: IsCompactShare for PFB tx shares

- x/qgb/client/verify.go
> chore: rename message to blob in QGB verify command

- go.mod
- go.sum
Downgrade to NMT 0.12.0 while @distractedm1nd @liamsi investigate an issue in 0.13.0
> chore: downgrade nmt to 0.12.0

- x/qgb/orchestrator/test/contract_interaction_test.go
> test: add contract interaction verify attestation test

- go.mod
removes replace statement for nmt
> chore: remove replace statement

- go.mod
- go.sum
this tag wasn't working previously, but I guess github's servers resolved the new tag or something, cause its working now... :upside_down_face:
> chore: use correct tag

- specs/src/specs/consensus.md
- specs/src/specs/data_structures.md
Context: https://github.com/celestiaorg/celestia-app/pull/1353
Closes https://github.com/celestiaorg/celestia-app/issues/1344
> docs: revise specs for padding shares

- testutil/testnode/full_node.go
- testutil/testnode/full_node_test.go
Dynamic port allocation for  the testnode as per https://github.com/celestiaorg/celestia-app/pull/1342#issuecomment-1425944402
> feat: make the testnode port allocation dynamic

- .github/workflows/docker-build-publish-common.yml
fixes https://github.com/celestiaorg/celestia-app/issues/1378
> fix: add permissions to docker security build

- pkg/appconsts/appconsts.go
- pkg/wrapper/nmt_wrapper.go
- pkg/wrapper/nmt_wrapper_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1384
> chore: explicitly set namespace size

- x/qgb/keeper/keeper_data_commitment.go
Addresses this delayed feedback: https://github.com/celestiaorg/celestia-app/pull/1389#discussion_r1108681579
> refactor: attestation iteration

- .github/workflows/test.yml
Closes https://github.com/celestiaorg/celestia-app/issues/1396
> ci: remove unused build tags from go test

- app/test/qgb_rpc_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1394
> chore: fix qgb rpc flaky test

- docs/architecture/adr-012-sequence-length-encoding.md
Closes https://github.com/celestiaorg/celestia-app/issues/1413
> chore: update dead link

- testutil/testnode/node_init.go
> chore: remove duplicate error handling in `initFileStructure`

- testutil/testnode/full_node.go
> fix: use a custom remove function to find the file causing the flakiness

- testutil/testnode/rpc_client.go
Now that this function, apparently, reduces flakiness a lot (I haven't seen any on orchestrator-relayer repo). I guess we can put it in the start node cleanup so that users won't have to worry about it.
> chore: cherry pick flakiness fix

- go.mod
- go.sum
> chore: bump core to v1.15.0

- specs/src/specs/data_structures.md
Closes https://github.com/celestiaorg/celestia-app/issues/1454
> docs: note about Q3

- README.md
Closes https://github.com/celestiaorg/celestia-app/issues/1470
> docs: explicitly state supported Go version

- .github/workflows/issue-label-automation.yml
Automate-labels for dependabot PRs
Closes #1464
> ci: automate-labels for dependabot PRs

- .github/workflows/test.yml
Remove usage of the deprecated workflow
#1398
> chore: Remove usage of deprecated rokroskar/workflow-run-cleanup-action

- app/module_test.go
Addresses this feedback: https://github.com/celestiaorg/celestia-app/pull/1484#discussion_r1134680164
> chore: remove nolint

- .github/workflows/gh-pages.yml
- specs/src/SUMMARY.md
Attempts to address https://github.com/celestiaorg/celestia-app/issues/1495
Although the PR Preview action didn't comment on this PR, we think it may on subsequent PRs.
> ci: PR preview specs

- docs/architecture/adr-009-non-interactive-default-rules-for-reduced-padding.md
> docs: change LessThen to MoreThen

- .github/workflows/lint.yml
- .github/workflows/test.yml
- Dockerfile
- Makefile
- README.md
- docker/Dockerfile.test
- docker/Dockerfile_ephemeral
- go.mod
Closes https://github.com/celestiaorg/celestia-app/issues/769
> chore: upgrade to Go 1.19

- pkg/shares/doc.go
Closes https://github.com/celestiaorg/celestia-app/issues/1560
> docs: account for namespace version and 32 byte namespace id

- README.md
- x/blob/README.md
Addresses https://github.com/celestiaorg/celestia-app/pull/1559#pullrequestreview-1363883954
> docs: specs vs package-specific docs

- app/test/integration_test.go
- testutil/blobfactory/payforblob_factory.go
- testutil/testnode/node_interaction_api.go
- x/blob/client/cli/payforblob.go
- x/blob/client/cli/testrandblob.go
- x/blob/client/testutil/integration_test.go
- x/blob/types/blob_tx.go
- x/blob/types/blob_tx_test.go
- x/blob/types/test/blob_tx_test.go
Introduce `--share-version` CLI flag 
-  #1041  
- [.] New and updated code has appropriate documentation
- [.] New and updated code has new and/or updated testing
- [.] Required CI checks are passing
- [] Visual proof for any user facing features like CLI or documentation updates
- [.] Linked issues closed with keywords
> feat: Introduce `--share-version` CLI flag

- pkg/shares/sparse_shares_test.go
- testutil/testfactory/blob.go
Closes https://github.com/celestiaorg/celestia-app/issues/1622
> chore: export GenerateRandomBlobOfShareCount

- pkg/wrapper/nmt_wrapper.go
- pkg/wrapper/nmt_wrapper_test.go
- x/blob/types/payforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/1450
> chore: explicitly set IgnoreMaxNamespace: true

- Makefile
Addresses https://github.com/celestiaorg/celestia-app/pull/1599#pullrequestreview-1373226138
```shell
$ make adr-gen
$ git status
On branch rp/adr-gen
Your branch is up to date with 'origin/rp/adr-gen'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
docs/architecture/adr-template.md
```
> chore: address adr-gen feedback

- go.mod
- go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/1589
> chore: upgrade to cosmos-sdk v1.10.0-sdk-v0.46.11

- scripts/single-node.sh
Originally added in https://github.com/celestiaorg/celestia-app/commit/7d4b04136d4abc63e726e67c984103985da709c7 and appears irrelevant now
> chore: remove outdated comment

- x/blob/client/cli/tx.go
- x/blob/types/payforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/1655
Closes https://github.com/celestiaorg/celestia-app/issues/1651
> chore!: remove unnecessary constants

- testutil/testnode/full_node.go
- testutil/testnode/full_node_test.go
- x/qgb/abci.go
- x/qgb/test/versions_integration_test.go
- x/qgb/v1/consts.go
- x/qgb/v1beta1/consts.go
- x/qgb/versions.go
- x/version/chains.go
- x/version/test/integration_test.go
This PR changes the `SignificantPowerDifferenceThreshold` qgb constant depending on the app version. Note that this PR is targeting only the v0.13.x branch.
closes #1594
> feat!: implement the BSR hardfork

- specs/src/specs/data_structures.md
Motivated by https://github.com/celestiaorg/celestia-app/issues/1673#issuecomment-1529796284
> docs: clarify namespace specs

- pkg/appconsts/appconsts.go
increases the default min fee by two orders of magnitude.
closes #1701
> chore: increase default min fee

- pkg/appconsts/appconsts.go
- x/qgb/types/errors.go
- x/qgb/types/genesis.go
Closes https://github.com/celestiaorg/celestia-app/issues/1706
> chore: extract the minimum data commitment to a constant and update error message

- docs/architecture/adr-010-remove-wire-msg-pay-for-blob.md
> docs: adr-010 fix link

- .github/workflows/ci-release.yml
- .github/workflows/docker-build-publish.yml
- .github/workflows/github-pages.yml
- .github/workflows/housekeeping.yml
- .github/workflows/protobuf.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
Closes https://github.com/celestiaorg/celestia-app/issues/1796
> ci: consistent workflow names

- go.mod
- go.sum
bumps core to include the end exclusive rpc
> chore!: bump core to v1.21.0-tm-v0.34.27

- test/util/common.go
- x/qgb/abci.go
- x/qgb/abci_test.go
- x/qgb/genesis.go
- x/qgb/keeper/keeper_attestation.go
- x/qgb/keeper/keeper_data_commitment.go
- x/qgb/keeper/keeper_valset.go
- x/qgb/types/attestation.go
- x/qgb/types/data_commitment.go
- x/qgb/types/errors.go
- x/qgb/types/keys.go
- x/qgb/types/query.pb.go
- x/qgb/types/valset.go
Closes https://github.com/celestiaorg/celestia-app/issues/309 and https://github.com/celestiaorg/celestia-app/issues/1808
> feat!: implement QGB pruning

- x/qgb/abci_test.go
handles https://github.com/celestiaorg/celestia-app/pull/1799#discussion_r1202975773
> chore: documenting the block interval via code in QGB abci test

- app/test/qgb_rpc_test.go
- proto/celestia/qgb/v1/query.proto
- x/qgb/abci.go
- x/qgb/abci_test.go
- x/qgb/keeper/hooks.go
- x/qgb/keeper/keeper_data_commitment.go
- x/qgb/keeper/keeper_data_commitment_test.go
- x/qgb/keeper/keeper_valset.go
- x/qgb/keeper/keeper_valset_test.go
- x/qgb/keeper/query_data_commitment.go
- x/qgb/keeper/query_general.go
- x/qgb/keeper/query_valset.go
- x/qgb/types/keys.go
- x/qgb/types/query.pb.go
- x/qgb/types/query.pb.gw.go
Closes https://github.com/celestiaorg/celestia-app/issues/1821
> chore!: last -> latest prefix in QGB store values

- x/qgb/abci_test.go
- x/qgb/keeper/keeper_valset.go
- x/qgb/types/attestation.go
- x/qgb/types/data_commitment.go
- x/qgb/types/valset.go
Closes https://github.com/celestiaorg/celestia-app/issues/1804
> chore!: remove unnecessary type method from QGB attestations

- pkg/shares/parse_test.go
- pkg/shares/share_sequence.go
- pkg/shares/share_sequence_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1816
Tagging @jcstein @tuxcanfly for awareness. I plan on cutting a v0.13.3 release after this merges.
> fix: validSequenceLen for padding shares

- x/qgb/abci_test.go
Handles https://github.com/celestiaorg/celestia-app/pull/1799#discussion_r1202976985
> docs: pruning comment typos

- x/qgb/abci.go
- x/qgb/abci_test.go
- x/qgb/genesis.go
- x/qgb/handler.go
- x/qgb/keeper/hooks.go
- x/qgb/keeper/keeper.go
- x/qgb/keeper/keeper_attestation.go
- x/qgb/keeper/keeper_data_commitment.go
- x/qgb/keeper/keeper_valset.go
- x/qgb/module.go
- x/qgb/types/attestation.go
- x/qgb/types/genesis.go
- x/qgb/types/keys.go
- x/qgb/types/validator.go
- x/qgb/types/valset.go
QGB module go docs reformat 
Closes: https://github.com/celestiaorg/celestia-app/issues/1819
> docs: QGB go docs reformat

- x/tokenfilter/README.md
> docs: specify the token filter middleware

- test/util/testnode/node_interaction_api.go
> docs: fix the GenesisTime go doc

- pkg/shares/parse_sparse_shares_test.go
- pkg/shares/share_splitting.go
- pkg/shares/split_sparse_shares.go
- pkg/square/builder.go
Closes https://github.com/celestiaorg/celestia-app/issues/1926
> chore: rename to namespace padding

- x/blob/types/params.pb.go
- x/qgb/types/query.pb.go
When I run `make proto-gen` on main, I observe changes.
https://github.com/celestiaorg/celestia-app/pull/1768 changed [this line](https://github.com/celestiaorg/celestia-app/commit/5b35a01f2955cafbd545c2b51e17195df1d39321#diff-94b9ac93697af06645344ee8040d0b891f934ad1a5e49c7c39c3cb062ba34a4fR71) without a change to params.proto
> chore: `make proto-gen`

- app/prepare_proposal.go
- app/process_proposal.go
- app/validate_txs.go
Closes: https://github.com/celestiaorg/celestia-app/issues/1898
> feat: use panics and recovery appropriately

- proto/celestia/blob/v1/tx.proto
- x/blob/types/tx.pb.go
Part of https://github.com/celestiaorg/celestia-app/issues/1753 but was accidentally missed in https://github.com/celestiaorg/celestia-app/pull/1771
> docs: fix namespace comment

- pkg/namespace/namespace.go
- pkg/namespace/namespace_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1883
> feat: `NewV0` namespace

- .github/CODEOWNERS
I don't think I should be a codeowner.
> Update CODEOWNERS: remove MSevey

- x/qgb/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/1977
All the whitespace changes were auto applied by my editor
> fix: markdown-lint

- proto/celestia/qgb/v1/genesis.proto
- test/util/common.go
- x/qgb/README.md
- x/qgb/keeper/hooks.go
- x/qgb/types/genesis.pb.go
> chore: QGB module cosmetics

- x/blob/types/errors.go
- x/blob/types/payforblob.go
- x/blob/types/payforblob_test.go
> fix!: add namespace version check in pfbs

- specs/src/specs/data_structures.md
Attempts to mitigate https://github.com/celestiaorg/celestia-app/issues/1887
> ci: disable link check for doi.org

- specs/src/specs/shares.md
Closes https://github.com/celestiaorg/celestia-app/issues/2000
> docs: share version

- scripts/README.md
Motivation: https://github.com/celestiaorg/docs/pull/841/files/28eb632b46742e996426933cafd8ebd6bf71485d#r1245899784
> docs: scripts README

- app/test/fuzz_abci_test.go
- test/util/direct_tx_gen.go
fixes #2027 by passing the correct information to prepare and process proposal along with adding a passing condition to that test.
> fix: prepare/process proposal consistency test

- x/mint/abci_test.go
Motivation https://github.com/celestiaorg/celestia-app/pull/2030
> test: unit test inflation rate for year fifteen

- README.md
Motivation: https://github.com/celestiaorg/celestia-app/pull/2035#issuecomment-1621810641
> docs: describe conventional commits

- specs/src/specs/data_structures.md
Closes https://github.com/celestiaorg/celestia-app/issues/2064
> chore: markdown-link-check ignore bitcointalk.org

- x/mint/types/constants.go
Closes https://github.com/celestiaorg/celestia-app/issues/2040
> refactor: use `SecondsPerYear`

- app/prepare_proposal.go
- app/process_proposal.go
- app/test/integration_test.go
- app/test/process_proposal_test.go
- go.mod
- go.sum
- pkg/da/data_availability_header.go
- pkg/da/data_availability_header_test.go
- pkg/inclusion/nmt_caching_test.go
- pkg/proof/proof.go
- pkg/proof/proof_test.go
- pkg/square/square_fuzz_test.go
- pkg/square/square_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2060
Marked as breaking b/c after this PR `NewDataAvailabilityHeader` may return an error.
> chore!: bump to rsmt2d v0.10.0

- test/util/malicious/app_test.go
- test/util/malicious/out_of_order_prepare.go
Closes https://github.com/celestiaorg/celestia-app/issues/2091
`make test` passes locally
> fix: malicious test and prepare proposal

- pkg/da/data_availability_header.go
- pkg/da/data_availability_header_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1011
cc: @Wondertan
> feat: SquareSize helper for dah

- go.mod
- go.sum
- pkg/square/builder.go
- test/util/malicious/out_of_order_builder.go
Closes https://github.com/celestiaorg/celestia-app/issues/2071
> refactor: use `blob.Namespace()` from celestia-core

- tools/blocktime/main.go
- tools/blocktime/readme.md
This PR ports a small tool I created for measuring block intervals such that others may use it as well
> feat: add blocktime tool

- scripts/single-node.sh
fixes a left pver `--ethereum-address`
(cherry picked from commit eb5fe096368b7c7d48f5df4933cc6b1d9ab70136)
Cherry pick eb5fe096368b7c7d48f5df4933cc6b1d9ab70136
Fixes: https://github.com/celestiaorg/celestia-app/issues/2101
> fix: single node script (#929)

- app/app.go
> feat: add node service which exposes min gas price

- specs/src/specs/namespace.md
Closes https://github.com/celestiaorg/celestia-app/issues/2146
> docs: remove trailing whitespace

- pkg/shares/padding.go
- pkg/shares/padding_test.go
- pkg/shares/parse_test.go
- pkg/shares/share_sequence_test.go
- pkg/shares/shares_test.go
- pkg/shares/split_sparse_shares.go
- pkg/shares/split_sparse_shares_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2142
> refactor: use blob share version for padding shares

- app/square_size.go
- x/blob/keeper/params.go
Closes https://github.com/celestiaorg/celestia-app/issues/2149
> chore: rename to `GovMaxSquareSize`

- Makefile
- docker/Dockerfile_txsim
Closes https://github.com/celestiaorg/celestia-app/issues/2161
> fix: txsim docker build

- x/blob/client/cli/payforblob.go
Not sure if other changes should be done to ADRs that still have examples with the old namespace size and also tests...
> chore: update pfb namespace size description

- go.mod
- go.sum
> chore(deps): bump core version to v1.26.0-tm-v0.34.28

- pkg/shares/blob_share_commitment_rules.go
- pkg/shares/blob_share_commitment_rules_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2175
This [test case](https://github.com/rootulp/celestia-app/blob/e9f5c157e56e7aff232250ae4a1aac58dfa2336f/pkg/shares/blob_share_commitment_rules_test.go#L312-L316) still passes.
> refactor: simplify roundUpByMultipleOf

- pkg/square/builder.go
Closes https://github.com/celestiaorg/celestia-app/issues/2174
> docs: clarify motivation for SliceStable

- x/blob/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/2178
> docs: fix validity rule for blob namespaces

- app/test/check_tx_test.go
- app/test/integration_test.go
Part of https://github.com/celestiaorg/celestia-app/issues/2156
> test: blob sizes that are too large

- x/mint/keeper/genesis.go
Closes https://github.com/celestiaorg/celestia-app/issues/2042
> docs: describe need for GetModuleAccount

- Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/2210
> test: skip TestMaliciousTestNode in race mode

- .github/workflows/docker-build-publish.yml
This fix is intended to fix the creation of the package for txsim
> fix: packageNaming fix for txsim

- app/test/integration_test.go
> fix: incorrect byte units in comments

- .github/mergify.yml
I think this is the bug in mergify
> Update mergify.yml to fix label

- .github/workflows/issue-label-automation.yml
Attempt to fix #2262 
The steps to actually verify this are a bit annoying but will try to backport this PR to v1.x, merge, update https://github.com/celestiaorg/celestia-app/pull/2260 with latest from v1.x, re-trigger the issue label automation workflow.
> ci: maybe fix issue label automation for mergify

- .github/workflows/issue-label-automation.yml
Attempts to close https://github.com/celestiaorg/celestia-app/issues/2262
> ci: maybe fix issue label automation

- .github/workflows/issue-label-automation.yml
Closes https://github.com/celestiaorg/celestia-app/issues/2262
Tested this on my fork and it works as expected. The problem with the last PR was that the environment variables are strings so they need to be compared against the string literals `'true'` and `'false'`.
> ci: fix issue label automation

- x/mint/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/2070
> docs: add security section to x/mint README

- app/test/integration_test.go
- test/util/malicious/app_test.go
- x/blob/payforblob.go
> feat!: make submitPFB broadcast mode configurable

- scripts/build-run-single-node.sh
- scripts/single-node.sh
> chore: register the EVM address correctly in single-node scripts

- Makefile
It's causing a data race: https://github.com/celestiaorg/celestia-app/actions/runs/5905789625/job/16020549998?pr=2316
> fix(test): skip the `TestSignerTestSuite` in test race

- cmd/celestia-appd/cmd/root.go
Closes https://github.com/celestiaorg/celestia-app/issues/2318
> fix(cmd): correctly use the log-to-file flag

- x/blob/README.md
> docs: update dead submit PFB link

- scripts/build-run-single-node.sh
- scripts/single-node.sh
As of https://github.com/celestiaorg/celestia-app/pull/2329#discussion_r1303409135, we need to remove the `s` suffix as it's not supported by mac
> fix: support MacOS in scripts

- Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/2332 b/c seems un-needed.
> chore: remove `-compat` usage

- x/blob/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/2350
> docs: fix namespace rules in x/blob/README.md

- docker/README.md
- docker/txsim.sh
ref: https://github.com/celestiaorg/celestia-app/pull/2326#discussion_r1304493605
> feat: update the txsim docker script and documentation

- go.mod
- go.sum
Bump to https://github.com/celestiaorg/nmt/releases/tag/v0.19.0
cc: @distractedm1nd
> chore(deps): bump to nmt v0.19.0

- app/test/std_sdk_test.go
- go.mod
- go.sum
bumps the sdk to include the latest changes to the vesting module
> chore!: bump the cosmos-sdk to include new vesting module changes

- specs/src/README.md
- specs/src/SUMMARY.md
- specs/src/specs/block_validity_rules.md
- specs/src/specs/data_square_layout.md
- specs/src/specs/fraud_proofs.md
Backport #1966 to unblock #2384
> docs: add block validity rules specs (backport #1966)

- test/cmd/txsim/cli.go
- test/txsim/run.go
- test/txsim/sequence.go
During the interaction with txsim, I noticed certain inconsistencies between the suggested flags and the actual flags available in the implementation. The purpose of this PR is to reconcile the two aspects and ensure alignment.
Partially covers https://github.com/celestiaorg/celestia-app/issues/2383.
> fix(txsim): resolves discrepancies between suggested and implemented flags 

- app/app.go
Closes https://github.com/celestiaorg/celestia-app/issues/2391
> chore: remove `GetMaccPerms`

- scripts/single-node.sh
Closes https://github.com/celestiaorg/celestia-app/issues/2404
I frequently need to modify a config and test it out. When using the existing single-node.sh script, it's a bit tedious to find the randomly generated CELESTIA_APP_HOME directory and plumb that into subsequent ad-hoc commands.
This PR modifies the `single-node.sh` script to use the default CELESTIA_APP_HOME directory (usually `~/.celestia-appd`).  That way, if a developer needs to make a modification to a config, they can do that in the expected location (i.e. `~/.celestia-appd/config/config.toml`) and then re-run `celestia-appd start` and test out the modification.
Other improvements include:
- Adds a y/n prompt to confirm deleting any existing CELESTIA_APP_HOME directory
- Hoists variables to the top
- Silences noisy …
> chore: default home directory for `single-node.sh`

- .github/workflows/test.yml
> typo(ci): upload word typo

- .github/workflows/docker-build-publish.yml
> chore: bump docker ci to v0.2.3

- go.mod
- go.sum
- x/qgb/client/verify.go
- x/qgb/types/abi_consts.go
Bumps the QGB contracts version to latest
> chore(deps): bump the QGB contracts version

- scripts/single-node.sh
The default Celestia app home directory contains a typo
> fix(scripts): single node celestia app home fix

- x/mint/abci.go
- x/mint/types/minter.go
- x/mint/types/minter_test.go
Addresses finding 008 of Binary Builders preliminary audit.
> refactor(x/mint): error if current before previous

- pkg/user/tx_options.go
Closes:  https://github.com/celestiaorg/celestia-app/issues/2376
> chore!: remove unused InheritTxConfig function

- x/qgb/client/query.go
- x/qgb/types/errors.go
Closes https://github.com/celestiaorg/celestia-app/issues/2523
> feat: add query qgb evm address by valoper address command

- x/blob/ante/max_total_blob_size_ante.go
> chore: use builtin min function

- .github/workflows/ci-release.yml
- .github/workflows/lint.yml
- .github/workflows/markdown-linter.yml
Closes https://github.com/celestiaorg/celestia-app/issues/2555
1. https://github.com/rootulp/celestia-app/pull/36
2. https://github.com/rootulp/celestia-app/pull/37
> ci: run markdown-linter on ci-release

- specs/src/specs/params.md
- x/mint/README.md
- x/mint/types/constants.go
Closes https://github.com/celestiaorg/celestia-app/issues/2481
> docs: add one more mint param to params.md

- go.mod
- go.sum
> chore: bump our fork of the sdk to v1.18.1-sdk-v0.46.14

- docs/architecture/adr-019-strict-inflation-schedule.md
- specs/src/specs/ante_handler.md
- specs/src/specs/data_structures.md
- specs/src/specs/public_key_cryptography.md
- specs/src/specs/resource_pricing.md
- x/blob/types/payforblob.go
- x/qgb/overview.md
- x/upgrade/README.md
fixes dead link
this blocking the updates to v1.x since we need that CI to pass
> fix: dead link

- go.mod
- go.sum
Bumps to the latest version of the contracts that use some gas optimizations.
> chore(deps): bump qgb contracts version to v2.1.2

- app/default_overrides.go
- app/default_overrides_test.go
- specs/src/specs/params.md
Closes https://github.com/celestiaorg/celestia-app/issues/2625
> chore: reduce VotingPeriod to 1 week

- app/default_overrides.go
minor PR to update the description of tia
> chore: update the default description for tia

- specs/src/specs/params.md
Closes https://github.com/celestiaorg/celestia-app/issues/2801
> docs: alphabetize params

- .github/workflows/nightly.yml
- .github/workflows/test.yml
Closes https://github.com/celestiaorg/celestia-app/issues/1112
This change will:
1. Run all tests in the nightly workflow
2. Run fuzz tests on every PR. Note this isn't a required check
Verified this runs fuzz tests on a PR in my fork. See https://github.com/rootulp/celestia-app/pull/45
> ci: run fuzz tests on every PR

- .github/workflows/ci-release.yml
Closes https://github.com/celestiaorg/celestia-app/issues/2896
Before: https://github.com/celestiaorg/celestia-app/actions/runs/7091353330/job/19300606228#step:6:71
After: https://github.com/rootulp/celestia-app/actions/runs/7146296002/job/19463697449#step:6:68
> ci(goreleaser): set fetch-depth to 0

- .gitignore
Add `vendor` to .gitignore so no more green changes when we run `go mod vendor`
> chore: Add vendor to gitignore

- Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/2938 by doing the short term fix
> test: skip TestCLITestSuite in race mode

- x/blob/module.go
- x/blobstream/module.go
Closes https://github.com/celestiaorg/celestia-app/issues/2953
> refactor: remove `RegisterCodec`

- go.mod
- go.sum
updates core to fix the breaking config change
is something breaking if it fixes something else that was breaking? lol
> chore: bump core to revert breaking config change

- .github/CODEOWNERS
> chore: rename the codeowners contributor name

- docs/architecture/adr-006-non-interactive-defaults.md
- docs/architecture/adr-009-non-interactive-default-rules-for-reduced-padding.md
Closes https://github.com/celestiaorg/celestia-app/issues/2159
> docs: mark outdated ADRs

- go.work.sum
- pkg/appconsts/versioned_consts_test.go
Added a unit test for GlobalMinGasPrice constant getter. https://github.com/celestiaorg/celestia-app/pull/3040#discussion_r1465446053
Refactored existing unit tests to make it more readable.
> test: add unit test for global min gas price getter

- NOTICE
> chore: remove "and onwards" in NOTICE

- app/app.go
1. Remove three temporary module variables
1. Rename some imports for consistency
> refactor: remove temporary module variables

- .github/CODEOWNERS
In this PR, I've updated the CODEOWNERS file to include my GitHub handle in the relevant sections. I seek confirmation from reviewers to ensure my additions align with our current ownership policies. If there are sections where my ownership is not applicable, kindly inform me so I can revise my PR accordingly.
> chore: extending CODEOWNERS

- app/app.go
- app/posthandler/posthandler.go
Another small refactor to make app.go more readable.
> refactor: extract posthandler package

- app/ante/fee_checker.go
- app/ante/min_fee_test.go
- go.work.sum
- pkg/appconsts/versioned_consts.go
- pkg/appconsts/versioned_consts_test.go
> fix: global min gas price version error

- specs/src/specs/namespace.md
> chore: adds a note about namespace collisions in the namespace spec

- specs/src/specs/namespace.md
Closes https://github.com/celestiaorg/celestia-app/issues/3107
> chore: adds a one liner about a potential consequence of namespace collision

- Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/3095
> test: skip TestLegacyUpgrade in race mode

- .github/CODEOWNERS
Closes https://github.com/celestiaorg/celestia-app/issues/3231
> chore: add Sanaz and Nina as codeowners

- x/upgrade/keeper.go
- x/upgrade/keeper_test.go
- x/upgrade/tally_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2878
> refactor(x/upgrade): voting power threshold 

- app/prepare_proposal.go
- app/process_proposal.go
- app/validate_txs.go
Fixes a few inconsistencies between the code and comments.
> docs: improve prepare proposal comments

- README.md
- pkg/proof/README.md
A few miscellaneous fixes in the README
> docs: improve README

- app/prepare_proposal.go
- app/process_proposal.go
- app/squaresize/max_effective.go
- test/util/malicious/out_of_order_prepare.go
- x/blob/ante/blob_share_decorator.go
- x/blob/keeper/params.go
Closes https://github.com/celestiaorg/celestia-app/issues/2267
> refactor: deduplicate max effective square size

- app/prepare_proposal.go
- app/process_proposal.go
- app/square_size.go
- test/util/malicious/out_of_order_prepare.go
- x/blob/ante/blob_share_decorator.go
- x/blob/keeper/params.go
Closes https://github.com/celestiaorg/celestia-app/issues/3336 by reverting #3294
Opens https://github.com/celestiaorg/celestia-app/issues/2267
I observe a consensus failure if I reboot celestia-app on `main`. I don't observe a consensus failure if I reboot celestia-app on this branch after the revert.
> revert: deduplicate max effective square size

- test/e2e/benchmark/throughput.go
- test/e2e/main.go
- test/e2e/readme.md
- test/e2e/simple.go
addressing suggestions https://github.com/celestiaorg/celestia-app/pull/3301
> refactor: address review comments from e2e tests as executables pr

- test/e2e/readme.md
Just mentioning a simple known issue when setting up the cluster.
> docs: mentions known missing cluster configuration in test/e2e docs

- test/txsim/run_test.go
- test/util/testnode/read.go
- tools/blockscan/main.go
- tools/blockscan/readme.md
This adds a tool for displaying the contents of blocks for debugging
> feat: add blockscan tool

- x/blobstream/client/verify.go
Follow up to https://github.com/celestiaorg/celestia-app/pull/3357. There was one remaining CodeQL violation that this PR resolves.
> fix: resolve lingering CodeQL violation

- scripts/single-node.sh
Make the `single-node.sh` script POSIX compatible so it runs on macOS/Linux etc without issue
> chore: POSIX compatible single-node

- app/app.go
- app/module/ibc.go
Addresses: https://github.com/celestiaorg/celestia-app/issues/3167
Adds a versioning wrapper around the IBC middleware so that they are not run when they are not supposed to be
> feat: versioned ibc middleware

- go.mod
- go.sum
downgrades ibc and retracts v1.8.0
> fix: downgrade ibc and retract v1.8.0

- test/e2e/check_upgrades.go
- test/e2e/main.go
- test/e2e/testnet/node.go
- test/e2e/testnet/node_helpers.go
- test/e2e/testnet/testnet.go
This fixes the port forwarding issues nina faces
cc: @ninabarbakadze 
Closes https://github.com/celestiaorg/celestia-app/issues/3187
> fix: MinorVersionCompatibility test

- test/tokenfilter/setup.go
- test/tokenfilter/tokenfilter_test.go
> fix: tokenfilter test

- pkg/proof/proof.go
Manually backports https://github.com/celestiaorg/celestia-app/pull/3460 to v1.x because there were so many diffs between the two branches.
> chore: export NewShareInclusionProofFromEDS

- specs/src/specs/params.md
Closes https://github.com/celestiaorg/celestia-app/issues/3322
cc: @evan-forbes
> docs: use one term for MaxBlockSizeBytes

- README.md
Closes https://github.com/celestiaorg/celestia-app/issues/361
> docs(README): section on usage as a library

- x/signal/keeper_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/3564
> chore(x/signal): add comment to test

- app/app.go
- app/app_test.go
- x/minfee/module.go
- x/minfee/module_test.go
> fix: minfee key table not registered on app restarts

- pkg/user/tx_client.go
> fix: TxClient gas price querying on v1 networks

- test/util/common.go
Completely optional refactor that I made while reviewing this code.
> refactor: test/util/common

- .github/workflows/ci-release.yml
- .github/workflows/lint.yml
- .github/workflows/nightly.yml
- .github/workflows/test.yml
- Dockerfile
- Makefile
- README.md
- docker/Dockerfile.test
- docker/Dockerfile_ephemeral
- go.mod
- go.sum
Manual backport of https://github.com/celestiaorg/celestia-app/pull/3607
> chore(deps): upgrade to celestia-core v1.37.0-tm-v0.34.29

- test/interchain/chainspec/celestia.go
Closes https://github.com/celestiaorg/celestia-app/issues/3631
```shell
$ make test-interchain
--> Running interchain tests
=== RUN   TestInterChainAccounts
...
--- PASS: TestInterChainAccounts (85.25s)
PASS
ok  	github.com/celestiaorg/celestia-app/test/interchain	85.843s
```
> test: fix TestInterChainAccounts

- specs/src/specs/namespace.md
> chore: fixes link to the namespace implementation

- test/interchain/go.mod
- test/interchain/go.sum
- test/testground/go.mod
- test/testground/go.sum
Follow up to https://github.com/celestiaorg/celestia-app/pull/3654
> chore(deps): upgrade to celestia-core v1.38.0

- go.mod
- go.sum
celestia-core bersion bump backport
> chore: bump celestia core

- README.md
- app/app.go
- app/module/manager.go
- local_devnet/celestia-app/app.toml
> chore: fix some comments

- tools/blockheight/README.md
- tools/blockheight/main.go
I used this tool to determine that the v2 upgrade height that we should configure on Arabica.
> feat: blockheight tool

- pkg/user/tx_client.go
> fix: error handling

- go.mod
- go.sum
Backporting fix as suggested in https://github.com/celestiaorg/celestia-app/pull/3849#pullrequestreview-2289617423
> chore(go.mod): bump grafana/pyroscope-go deps

- pkg/wrapper/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/3885
All fixed. :=)
> docs: fix broken link 

- test/cmd/txsim/cli.go
- test/cmd/txsim/cli_test.go
We need this so our e2e tests can schedule an upgrade to a new network version
> feat: add cli command for using upgrade sequences with txsim

- .github/workflows/docker-build-publish.yml
Brings in a patch fix for the docker workflow
> chore(deps): bump docker workflow version

- app/process_proposal.go
Fix the lint errors of this [PR](https://github.com/celestiaorg/celestia-app/pull/3925).
> fix(ci): lint errors

- app/test/state_sync_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/3935
> docs: how snapshot was created

- docs/maintainers/docker.md
Motivated by https://github.com/celestiaorg/celestia-app/issues/3934
> docs: guide to manually publish docker images

- Makefile
- go.mod
- go.sum
adds a script to disable bbr as a convenience for anyone that needs to test w/ and w/o bbr
> feat: script to disable bbr

- Makefile
- go.mod
- go.sum
> feat: script to disable bbr (#4047)

- test/util/malicious/app.go
I hope my correction will contribute to the project's development. Thank you for the time you gave me.
> chore: fix typo

- test/util/malicious/test_app.go
OutOfOrderNamesapceConfig - OutOfOrderNamespaceConfig
thanks for your work
> docs: fix typo

- go.mod
- go.sum
- test/interchain/go.mod
- test/interchain/go.sum
Upgrade to https://github.com/celestiaorg/celestia-core/releases/tag/v1.44.2-tm-v0.34.35 to pick up the fix in https://github.com/celestiaorg/celestia-core/pull/1582
> chore(deps): upgrade to celestia-core v1.44.2

- Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/4235
I modified my local config and ran `make configure-v3` and the values for these 6 configs match what I expect.
After this merges, @rootulp will send a message in Discord to ask validators to run `make configure-v3` to update their local configs.
> chore: modify configure-v3 to update all default overrides

- test/util/testnode/config.go
**invCheckPerid - invCheckPeriod**
> docs(typo): correct function config.go

- x/blob/README.md
- x/blob/ante/ante_test.go
- x/blob/client/cli/util.go
> docs: fix typos

- app/errors/nonce_mismatch.go
- app/module/manager.go
- test/util/direct_tx_gen.go
fix some function names in comment
> docs: fix function names in comments

- x/mint/keeper/grpc_query.go
>  docs: fix typo

- x/minfee/module.go
> docs: fix grammar

- test/pfm/simapp.go
This is a [new function](https://pkg.go.dev/maps@go1.21.1#Clone) added in the go1.21 standard library, which can make the code more concise and easy to read.
> refactor: use maps.Clone to simplify the code

- go.mod
- go.sum
- test/e2e/major_upgrade_v2.go
- test/e2e/major_upgrade_v3.go
- test/e2e/testnet/defaults.go
- test/e2e/testnet/testnet.go
> fix: knuu e2e tests

- .github/workflows/test-e2e.yml
> feat(e2e): use dev k8s cluster for e2e tests

- go.mod
- go.sum
- test/interchain/go.mod
- test/interchain/go.sum
Addresses https://github.com/cosmos/ibc-go/security/advisories/GHSA-4wf3-5qj9-368v on v3.x branch
> fix: non-deterministic JSON in IBC acks again

- go.mod
- go.sum
- test/interchain/go.mod
- test/interchain/go.sum
Bumps core to v1.51.0-tm-v0.34.35
> chore(deps): bump core to v1.51.0-tm-v0.34.35

- README.md
- docs/architecture/adr-015-namespace-id-size.md
- docs/architecture/adr-023-gas-used-and-gas-price-estimation.md
- docs/release-notes/release-notes.md
- tools/blocktime/readme.md
- x/blob/README.md
- x/minfee/README.md
- x/signal/README.md
To fix the markdown-link-check CI on v3.x
> chore: fix links

- cmd/celestia-appd/cmd/start.go
The existing docs that are printed out don't work.
> docs: Fix binary docs for enabling and checking BBR.

- test/e2e/readme.md
fix old link to a new one.
you are welcome
> docs: fix link

- cmd/celestia-appd/cmd/start.go
- go.mod
- go.sum
- test/interchain/go.mod
- test/interchain/go.sum
- test/util/testnode/rpc_client.go
Upgrade to https://github.com/celestiaorg/cosmos-sdk/releases/tag/v1.28.2-sdk-v0.46.16 to fix https://github.com/celestiaorg/cosmos-sdk/issues/451
Will create v3.8.1-arabica after this merges.
> fix: start `tendermint.rpc.grpc.BlockAPI`

- app/ante/fee_checker.go
> refactor: provide more info in the verifyMinFee error message

- specs/src/ante_handler_v3.md
> docs: clarify MaxTxSize AnteHandler

- go.mod
- go.sum
Upgrade to non RC versions of cosmos-sdk and celestia-core.
> chore(deps): upgrade to non RC versions of sdk and core

- app/ante/tx_size_gas.go
sepc256k1Pubkey - secp256k1Pubkey
> docs: fix typo tx_size_gas.go

- app/param_filters.go
> docs: fix function name in comment

- docker/Dockerfile
- docker/multiplexer.Dockerfile
- go.mod
- go.sum
Remove dependency on local pin of multiplexer, pin to v0.1.0
> build: pin to v0.1.0 of the multiplexer and remove local pin

- app/test/priority_test.go
Hi! I fixed typo in `app/test/priority_test.go`
`priortisation` - `prioritisation`
Thank you
> docs: fix typo priority_test.go

- test/interop/hyperlane_test.go
Ensures celestia app cannot use hyperlane synthetic tokens.
closes: #4638
> test: add hyperlane disabled synthetic tokens test

- cmd/celestia-appd/cmd/download_genesis.go
Closes https://github.com/celestiaorg/celestia-app/issues/4673
> refactor: isKnownChainID

- go.mod
- go.sum
Upgrade to the latest multiplexer release
> chore(deps): upgrade to multiplexer v0.3.0

- .github/workflows/docker-build-publish.yml
- Makefile
- test/e2e/readme.md
- test/e2e/testnet/node.go
ref: https://github.com/celestiaorg/celestia-app/pull/4718/files#r2069938649
> refactor: update v3 line to use standalone registry

- .github/workflows/docker-build-publish.yml
- Makefile
- docker/multiplexer.Dockerfile
- test/e2e/readme.md
- test/e2e/testnet/node.go
> refactor: change image registries

- multiplexer/abci/multiplexer_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4728
> test: openTraceWriter with empty file

- Makefile
Update the embedded binary to the latest v3.x.x version
> chore(deps): upgrade to v3.10.0-rc1 embedded binary

- go.mod
- go.sum
Upgrade to the latest multiplexer release
> chore(deps): upgrade to multiplexer v0.4.0

- scripts/single-node.sh
Closes https://github.com/celestiaorg/celestia-app/issues/4748
```
make install
$ ./scripts/single-node.sh
celestia-app version: 4.0.0-rc2-1-g83e4322d0
celestia-app home: /Users/rootulp/.celestia-app
celestia-app genesis file: /Users/rootulp/.celestia-app/config/genesis.json
Do you want to delete existing /Users/rootulp/.celestia-app and start a new local testnet? [y/n]
y
Deleting /Users/rootulp/.celestia-app...
Initializing validator and node config files...
Overriding the genesis.json expedited min deposit from 50 TIA to 50,000 TIA.
Adding a new key to the keyring...
Adding genesis account...
Creating a genesis tx...
Collecting genesis txs...
Overriding the genesis.json app version from 0 to 4.
Tracing is set up with the ability to pull traced data from the node on the address …
```
> fix: `single-node.sh`

- Makefile
Upgrade embedded binary to https://github.com/celestiaorg/celestia-app/releases/tag/v3.10.0-rc2
```
make install
```
works
> chore(deps): upgrade to app v3.10.0-rc2

- README.md
- app/init_test.go
Updates typos of default app home directory from: https://github.com/celestiaorg/celestia-app/pull/4667#issuecomment-2854733545
> fix: use standard default app home v3

- app/ante/circuit_breaker_test.go
- app/app.go
- app/default_overrides.go
- x/blob/types/estimate_gas_test.go
- x/minfee/keeper/migrations_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4765
> chore!: remove `DefaultInitialVersion`

- x/mint/README.md
- x/mint/types/minter_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4776
> docs(x/mint): update README for CIP-29

- specs/src/multisig.md
> chore(specs/multisig): use versioned link to avoid ci breakages

- Makefile
- go.mod
Closes https://github.com/celestiaorg/celestia-app/issues/4711
Locally
```
make prebuilt-binary
```
Created and attached binaries to https://github.com/rootulp/celestia-app/releases/tag/v4.0.0-rc4
> fix(ci): goreleaser disk space issue

- README.md
Add a warning to README until https://github.com/celestiaorg/celestia-app/issues/4798 is resolved.
> docs: add note about multiplexer support

- Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/4806
> chore(deps): upgrade to v3.10.0-arabica

- .github/workflows/test-e2e.yml
🤦 use correct makefile target in CI, it was trying to run the Knuu tests with the names of the new docker tests. I also added a `continue-on-error` in the test matrix so each test will not be cancelled if others fail.
> fix: use correct test in ci workflow

- Makefile
- docker/Dockerfile
- docker/multiplexer.Dockerfile
This PR removes unused parameters in the docker and make file. 
closes #4860
> chore: remove unused parameters

- .github/workflows/test.yml
- Makefile
- multiplexer/appd/run.go
- multiplexer/appd/run_test.go
closes #4857
Added some additional multiplexer tests which verify the embedded v3 binary can have commands executed on it. (via "version" / "help" )
The tests require the multiplexer build tag
> test: adding multiplexer tests

- test/docker-e2e/go.mod
- test/docker-e2e/go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/4874
> chore: run `go mod tidy` on docker-e2e

- x/zkism/types/ism.go
- x/zkism/types/metadata.go
- x/zkism/types/metadata_test.go
Quick one... just adds the structure as recommended by the issue.
closes: #4724
> chore: add noop implementation of ism verify method

- docs/release-notes/release-notes.md
Closes https://github.com/celestiaorg/celestia-app/issues/4927
Tagging @maxzonder for any feedback.
> docs: build v3.x binary with pebble support

- app/app.go
Closes: https://github.com/celestiaorg/celestia-app/issues/4950
ref: https://github.com/celestiaorg/celestia-app/issues/4950#issuecomment-2955569603 for the rationale.
> fix(app): disable `query consensus comet` CLI command

- tools/latency-monitor/main.go
Allow this tool to be used purely to load a network - no need for latency reports if `--disable-metrics` is passed.
> feat(tools): allow disabling metrics reporting for blob submission latency tool

- multiplexer/abci/multiplexer.go
> docs: fix function name

- docs/release-notes/release-notes.md
Part of https://github.com/celestiaorg/celestia-app/issues/4889
Motivation: https://celestia-team.slack.com/archives/C087852KEVC/p1750104267045649
> docs(release-notes): link to depedency release notes

- docs/maintainers/increase-square-size.md
Based on [Slack thread](https://celestia-team.slack.com/archives/C02PFFCGMNW/p1750326262887719)
cc: @renaynay @sysrex
> docs: increase square size

- docs/release-notes/release-notes.md
Motivation: https://github.com/celestiaorg/celestia-app/issues/5020#issuecomment-2989648731
> docs(release-notes): include diff for proxy_app

- docs/release-notes/release-notes.md
Closes https://github.com/celestiaorg/celestia-app/issues/4963
> docs(release-notes): embedded binary directory layout

- go.mod
- go.sum
- test/docker-e2e/go.mod
- test/docker-e2e/go.sum
So that the default keyring is `test`
> chore: upgrade to sdk v1.29.3

- .goreleaser.yaml
- Makefile
- internal/embedding/data.go
Needed before we create v4.0.4-arabica
> chore(deps): upgrade to v3.10.3-arabica

- pkg/appconsts/v4/app_consts.go
- pkg/appconsts/v4/app_consts_test.go
- pkg/appconsts/versioned_consts.go
- pkg/appconsts/versioned_consts_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/5064
> fix(appconsts)!: reduce upgrade height delay for testnets

- tools/talis/download.go
Allows download a comma separated list of tables from talis nodes
> feat: talis download list of tables

- app/consistent_apphash_test.go
> test(v1.x): expand apphash test coverage

- README.md
Based on https://github.com/celestiaorg/celestia-core/pull/2173
cc: @rach-id
> docs: improve purpose of celestia-core GRPC server

- .github/mergify.yml
Motivation: https://github.com/celestiaorg/celestia-app/issues/5194#issuecomment-3053790327
> ci: enable forwardport to main from v4.x

- x/signal/integration_test.go
- x/signal/keeper.go
- x/signal/keeper_test.go
- x/signal/types/msgs.go
Implements option 2 of https://github.com/celestiaorg/celestia-app/issues/5189#issuecomment-3063061766
Follow ups
> feat(x/signal): emit custom events

- Makefile
- docker/multiplexer.Dockerfile
- internal/embedding/data.go
Closes https://github.com/celestiaorg/celestia-app/issues/5236
> fix: v4 versions

- pkg/appconsts/app_consts.go
- test/interop/simapp.go
- test/multiplexer/multiplexer_test.go
- tools/talis/init.go
Hey team! Fixed typos 
pkg/appconsts/app_consts.go
`7 day` - `7 days`
test/interop/simapp.go
`ISC4` - `ICS4`
test/multiplexer/multiplexer_test.go
`multi plexer` - `multiplexer`
tools/talis/init.go
`director` - `directory`
> docs: fix typos 

- .github/workflows/test.yml
- test/docker-e2e/dockerchain/config.go
- test/docker-e2e/e2e_full_stack_blob_test.go
- test/docker-e2e/e2e_full_stack_pfb_test.go
- test/util/genesis/genesis.go
This test performs a basic full stack test which deploys app, node and uses txclient to broadcast PFBs.
The node image can stay relatively static (bump as required) the app image is built on every tag/pr. This test should flag if anything like app / wiring or anything that effects core functionality breaks.
If it is expected that the test breaks on a given PR, we can ignore the failure as these E2Es are not marked as required.
closes #5227
> test: Basic Full Stack E2E Test

- test/cmd/txsim/cli.go
- test/interop/simapp.go
- tools/chainbuilder/benchmark_test.go
- tools/talis/download.go
- x/mint/types/minter_test.go
Inspired by https://github.com/celestiaorg/celestia-app/pull/4450 and replace all.
> refactor: modernized code with built-in func

- go.mod
- go.sum
- test/docker-e2e/go.mod
- test/docker-e2e/go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/5303
IAVL [v1.2.6](https://github.com/cosmos/iavl/releases/tag/v1.2.6) contains this PR: https://github.com/cosmos/iavl/pull/1025 which may resolve the issue.
> fix: iavl unlock of unlocked mutex

- tools/talis/deployment.go
- tools/talis/download.go
Just a couple more improvements to talis UX
> chore: support workers during s3 deployments and fix traces download directory

- proto/celestia/signal/v1/query.proto
- x/signal/cli/query.go
- x/signal/interfaces.go
- x/signal/keeper.go
- x/signal/keeper_test.go
- x/signal/types/query.pb.go
- x/signal/types/query.pb.gw.go
Closes: https://github.com/celestiaorg/celestia-app/issues/5388
> feat: query validators who have not signalled

- .github/mergify.yml
> ci: enable backporting to v5.x

- go.mod
- go.sum
- test/docker-e2e/go.mod
- test/docker-e2e/go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/5312
> fix: improve event UnmarshalJSON

- .goreleaser.yaml
- Makefile
- docker/multiplexer.Dockerfile
- internal/embedding/data.go
Part of https://github.com/celestiaorg/celestia-app/issues/4370
> chore(deps): upgrade to v3.10.6

- app/prepare_proposal.go
Closes https://github.com/celestiaorg/celestia-app/issues/4992
Reopen #5047 
fixed golanci lint, also fixed comment to match the current logic
> fix: stop panicking in PrepareProposalHandler

- multiplexer/appd/run.go
I don't think this fixes the problem, at best it hacks around it, but it seems like a good protection to add.
I tried to get the upgrade to halt while having some websocket connenction open, however I couldn't replicate locally. I'm not sure the hypothesis of websockets make sense anymore since the shutdown of the application shouldn't be blocked by websocket subscriptions from comet. It is still an interesting pattern.
might close #5408
> fix: force kill the embedded app after 6s

- cmd/celestia-appd/cmd/update_config.go
fix inconsistent function name in comment
> docs: fix comment

- go.mod
- go.sum
- test/docker-e2e/go.mod
- test/docker-e2e/go.sum
bumps to official ibc tag
part of #5587
> chore: bump ibc to official tag

- pkg/user/signer.go
Remove manual index tracking and use standard Go append pattern for cleaner code
> refactor: simplify account collection in Signer

- tools/talis/digital_ocean.go
Belarus servers have been unstable for past week. So I think we can remove it for now
> chore: remove blrs region from talis

- pkg/user/tx_client.go
- pkg/user/tx_client_test.go
> fix: stop incrementing the sequence for each connection

- pkg/user/tx_client.go
we somehow merged something that had a compiler error
> fix: compiler error

- .github/workflows/goreleaser.yml
Closes https://github.com/celestiaorg/celestia-app/issues/5828
> fix: goreleaser for v5.x

- pkg/user/tx_client.go
Fixes #5822 
This is in order to improve readability and debugging in the interim
> refactor: tx client to deduplicate broadcast methods

- README.md
> docs: add DeepWiki badge so that repo is auto-indexed

- pkg/wrapper/buffered_tree.go
- pkg/wrapper/buffered_tree_test.go
This PR is the testing PR, there are two files need to be catched by CI, fix the first one firstly. After the CI failed, I will commit the next one, if the CI is good after I commit the rest, The CI is working perfectly.
> chore: fix lint and test the CI
