config.yml
We don't need this config file anymore, as the `starport serve` command is not used.
ref: #2
=> Delete short config used by starport serve

.github/dependabot.yml, cmd/lazyledger-appd/cmd/root.go, go.mod, go.sum
Some logging flags got lost in versioning issues between starport and the cosmos-sdk, this PR adds them back.
closes #9
=> Add persistant logging flags

app/abci_test.go, go.mod, go.sum, x/lazyledgerapp/client/cli/payformessage.go, x/lazyledgerapp/client/cli/tx.go, x/lazyledgerapp/keeper/msg_server.go, x/lazyledgerapp/types/payformessage.go, x/lazyledgerapp/types/payformessage_test.go, x/lazyledgerapp/types/tx.pb.go
This PR adds a sub command to the cli to generate a `MsgWirePayForMessage` transaction.
```sh
Usage:
lazyledgerapp tx lazyledgerapp payForMessage [hexNamespace] [hexMessage] [flags]
```
Breaking down the above command, 
- `lazyledgerappd` is the root command for everything lazyledger-app, including starting the node and generating transactions, but of this can change. 
- the `tx` sub-command contains other sub-commands related to generating transactions
- the `lazyledgerapp` sub-command specifies the module that is being used
- `payForMessage` is the sub-command to generate a `MsgWirePayForMessage`
The only necessary inputs are the namespace and the message, where everything else can be optional with sane defaults. 
~~This PR should not be merged until #21 is merged.~~ :heavy_check_mark: …
=> Generate a `MsgWirePayForMessage` via CLI

app/abci_test.go, x/payment/types/payformessage.go, x/payment/types/payformessage_test.go
This adds a simple check to ensure that reserved namespaces are not used when submitting a `MsgWirePayForMessage`. It also adds unit tests for validate basic (which should have been added a while ago), and removes some comment graffiti.
closes: #67
=> Add check for reserved namespaces

.github/workflows/docker-build.yml, .github/workflows/linkchecker.yml, CHANGELOG-PENDING.md
Creates a GH action that will produce a docker image with the `latest` tag 
---
=> Create docker build GH action

app/abci.go, app/child_tx_decoder.go, go.mod, go.sum, testutil/network/network.go, x/payment/client/cli/wirepayformessage.go, x/payment/client/testutil/integration_test.go, x/payment/types/builder_test.go
This PR updates the cli to the latest refactor first introduced in #129, along with adding an integration test for the cli.
TODO: 
closes: #132 and #39
=> Update cli and add cli integration test

Makefile, app/app.go, app/child_tx_decoder.go, go.mod, go.sum, proto/cosmos/base/query/v1beta1/pagination.proto, proto/payment/genesis.proto, proto/payment/query.proto, proto/payment/tx.proto, third_party/proto/tendermint/abci/types.proto, x/payment/client/testutil/integration_test.go, x/payment/types/payformessage.go
This PR modifies the integration test to also query for the malleated transaction using the original transaction's hash. 
blocked by [#612](https://github.com/celestiaorg/celestia-core/pull/612)
=> Integration test for querying malleated transactions

app/test/abci_test.go, testutil/test_app.go
exports some testing utilities, specifically tools to easily create a new app. Helps out [#420](https://github.com/celestiaorg/celestia-node/pull/420)
closes #206
=> Refactor to export testutils

x/qgb/keeper/keeper_delegate_key.go, x/qgb/keeper/msg_server.go, x/qgb/types/errors.go, x/qgb/types/events.go, x/qgb/types/keys.go, x/qgb/types/setorchestratoraddress.go
Adds QGB orchestrator address logic.
Contributes to: https://github.com/celestiaorg/celestia-app/issues/197
=> add qgb orchestrator address logic

readme.md
This PR updates the `README.md` to use the current denom which is `uceles` instead of `celes`.
=> README.md: Update `celes` to `uceles`

go.mod, go.sum, x/qgb/abci_test.go, x/qgb/handler_test.go, x/qgb/keeper/keeper.go, x/qgb/keeper/keeper_delegate_key_test.go, x/qgb/keeper/keeper_test.go, x/qgb/keeper/keeper_valset_test.go, x/qgb/keeper/msg_server.go, x/qgb/keeper/query_delegate_key.go, x/qgb/keeper/query_valset_confirm_test.go, x/qgb/keeper/test_common.go, x/qgb/types/ethereum_signer_test.go, x/qgb/types/genesis.go, x/qgb/types/genesis_test.go, x/qgb/types/keys.go, x/qgb/types/setorchestratoraddress.go, x/qgb/types/setorchestratoraddress_test.go, x/qgb/types/types_test.go
closes: https://github.com/celestiaorg/celestia-app/issues/220
=> Adds qgb module tests

x/qgb/handler_test.go, x/qgb/keeper/keeper_data_commitment.go, x/qgb/keeper/keeper_valset_confirm.go, x/qgb/keeper/query_data_commitment.go, x/qgb/keeper/query_data_commitment_test.go, x/qgb/keeper/query_valset_confirm_test.go, x/qgb/types/datacommitmentconfirm.go, x/qgb/types/datacommitmentconfirm_test.go
Adds QGB data commitment tests
closes: https://github.com/celestiaorg/celestia-app/issues/238
=> Add qgb data commitment tests

x/qgb/handler_test.go, x/qgb/keeper/keeper.go, x/qgb/keeper/keeper_delegate_key.go, x/qgb/types/ethereum_signer.go, x/qgb/types/keys.go
Adds a simplified integration test for data commitments in QGB module
=> Adds msg server data commitment test for QGB module

x/qgb/keeper/keeper_data_commitment.go, x/qgb/keeper/query_data_commitment_test.go
Uses index prefix to query for commitments.
Adds to: https://github.com/celestiaorg/celestia-app/issues/241
Currently, the keys are as follows: 
https://github.com/celestiaorg/celestia-app/blob/8209e23a3645209a8c81214026eadd8c9607521d/x/qgb/types/keys.go#L111
=> Adds simple indexing to qgb module

.github/workflows/lint.yml, go.mod, go.sum
fixes the CI linter by specifying a specific version instead of automatically using the latest version of go
it also removes the specific version of tendermint in the replace directive, as we want to replace it across all inherited dependencies, not only for a specific verison
=> Fix the ci linter

.github/workflows/release-sims.yml, .github/workflows/sims.yml, .github/workflows/test.yml, .gitignore, Makefile, contrib/devtools/Makefile, scripts/protocgen.sh
`go get` for binaries was deprecated in 1.17 and removed in 1.18 in favor of `go install`. https://go.dev/doc/go-get-install-deprecation
=> go get -> go install

app/app.go
Basically copy & paste everything gov related from a fresh starport app.
related to: https://github.com/celestiaorg/celestia-app/issues/168
---
=> Add back the governance module

Makefile
Update the Makefile to use tendermintdev/sdk-proto-gen version v0.2 to temporarily fix the broken script.
Closes: https://github.com/celestiaorg/celestia-app/issues/340
=> temporary fix for proto-gen

Makefile
=> fix: actually print version on version sub-command

app/app.go, x/payment/keeper/gas_test.go, x/payment/keeper/keeper.go
This PR consumes gas for PayForData transactions. This should work, as it's a fairly standard operation, but it would be nice to have more integration testing. When attempting to add this to the cli integration test, I encountered #379. We might want to wait until that bug is fixed just to be sure.
closes #48
=> Deduct fees for PayForData transactions 

x/qgb/orchestrator/config.go, x/qgb/orchestrator/deploy_command.go, x/qgb/orchestrator/orchestrator_client.go, x/qgb/orchestrator/orchestrator_command.go, x/qgb/orchestrator/relayer_client.go, x/qgb/orchestrator/relayer_command.go
Closes https://github.com/celestiaorg/celestia-app/issues/302
=> better structure QGB CLI flags

app/encoding/encoding.go
We weren't registering the legacy amino codec, which stops us from being able to unmarshal some things from tendermint in some sub commands of our cli.
closes: #XXXX
=> Register the legacy amino codec

app/prepare_proposal.go, app/split_shares.go, app/test/block_size_test.go, x/payment/client/cli/wirepayfordata.go, x/payment/client/testutil/integration_test.go, x/payment/payfordata.go, x/payment/types/square_sizes.go
this could still use some cleaning up, but this PR changes things so that we sign over all applicable square sizes when creating a wirePFD
cc @renaynay 
closes: #239
=> Sign over all applicable square sizes by default

.github/workflows/test.yml
Adds simple github action to  run QGB E2E.
Closing https://github.com/celestiaorg/celestia-app/issues/409
=> Qgb e2e GitHub action

e2e/qgb/Makefile, e2e/qgb/deployer_test.go, e2e/qgb/full_test.go, e2e/qgb/orchestrator_test.go, e2e/qgb/qgb_network.go, e2e/qgb/relayer_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/438
=> better context handling + timeouts for QGB E2E network

cmd/celestia-appd/cmd/root.go, cmd/celestia-appd/main.go
Move NewRootCmd into separate pkg so it can be used externally.
closes: #525 (@Bidon15 should confirm if that actually closes it)
removes the necessity of copypasta in https://github.com/celestiaorg/test-infra/pull/27
---
=> chore: refactor NewRootCmd into separate pkg

x/qgb/handler_test.go, x/qgb/keeper/msg_server.go, x/qgb/types/errors.go
Closes https://github.com/celestiaorg/celestia-app/issues/520
=> QGB Verify the sent data commitment confirm is a data commitment attestation request

go.mod, go.sum, testutil/common.go, x/qgb/abci_test.go, x/qgb/handler_test.go, x/qgb/keeper/keeper.go, x/qgb/keeper/msg_server.go, x/qgb/keeper/query_data_commitment_confirm_test.go, x/qgb/keeper/query_valset_confirm_test.go, x/qgb/orchestrator/orchestrator.go, x/qgb/orchestrator/test/test_utils.go, x/qgb/types/data_commitment_confirm.go, x/qgb/types/data_commitment_confirm_test.go, x/qgb/types/ethereum_signer.go, x/qgb/types/ethereum_signer_test.go, x/qgb/types/keys.go, x/qgb/types/validator.go, x/qgb/types/valset_confirm.go
Depends on https://github.com/celestiaorg/cosmos-sdk/pull/221
contributes to https://github.com/celestiaorg/cosmos-sdk/issues/143
=> QGB Use Geth implementation of Ethereum address

e2e/qgb/deployer_test.go, e2e/qgb/docker-compose.yml, e2e/qgb/full_test.go, e2e/qgb/relayer_test.go, e2e/qgb/scripts/deploy_qgb_contract.sh, e2e/qgb/scripts/start_relayer.sh, x/qgb/orchestrator/config.go, x/qgb/orchestrator/deploy_command.go, x/qgb/orchestrator/evm_client.go, x/qgb/orchestrator/orchestrator.go, x/qgb/orchestrator/orchestrator_command.go, x/qgb/orchestrator/relayer.go, x/qgb/orchestrator/relayer_command.go
Closes https://github.com/celestiaorg/celestia-app/issues/307 and https://github.com/celestiaorg/celestia-app/issues/506
=> adds more configuration flags

e2e/qgb/deployer_test.go, e2e/qgb/errors.go, e2e/qgb/full_test.go, e2e/qgb/orchestrator_test.go, e2e/qgb/qgb_network.go, e2e/qgb/relayer_test.go, e2e/qgb/test_commons.go
- Better usage of context (no more gymnastics)
- Usage of two channels to organize communication between multiple go routines
Closes https://github.com/celestiaorg/celestia-app/issues/522
=> QGB better e2e context and channel usage

.github/workflows/proto.yml
Resolves https://github.com/celestiaorg/celestia-app/issues/560
Sample PR fails when a field was added to `tx.proto` but the corresponding generated file `x/payment/types/tx.pb.go` was not committed. See https://github.com/rootulp/celestia-app/runs/7506797210?check_suite_focus=true#step%3A3%3A68=
---
=> ci: check protobuf generated code

.github/workflows/docker-build.yml, .github/workflows/lint.yml, .github/workflows/sims.yml, .github/workflows/tag.yml, .github/workflows/test.yml, Dockerfile, Makefile, contrib/Dockerfile.test, docker/Dockerfile_ephemeral, go.mod
This PR updates this repo to use go 1.18. It also requires an update to golangci-linter in order for that to keep working. 
closes #572 
unblocks #472
=> chore: update to go 1.18

x/payment/types/errors.go, x/payment/types/payfordata.go, x/payment/types/payfordata_test.go, x/payment/types/wirepayfordata.go, x/payment/types/wirepayfordata_test.go
Resolves https://github.com/celestiaorg/celestia-app/issues/312
=> Throw errors if messages try to use `ParitySharesNamespaceID` or `TailPaddingNamespaceID`

.golangci.yml, app/split_shares.go, x/payment/types/builder.go, x/payment/types/events.go, x/payment/types/payfordata.go
Partially addresses https://github.com/celestiaorg/celestia-app/issues/323
=> ci: enable misspell linter

Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/581
The `$(BUILD_FLAGS)` contain the version:
https://github.com/celestiaorg/celestia-app/blob/5148c709f06357331d0d1a88884080aec55025f4/Makefile#L13-L20
```shell
make build
$ ./build/celestia-appd version
0.6.0-11-gcfa991a
```
=> fix: use build flags when running make build

.golangci.yml, app/app.go, app/encoding/encoding.go, app/test/block_size_test.go, app/test/prepare_proposal_test.go, app/test/process_proposal_test.go, app/test/split_shares_test.go, cmd/celestia-appd/cmd/root.go, testutil/network/network.go, testutil/test_app.go, x/payment/types/builder.go, x/payment/types/codec.go, x/payment/types/payfordata.go
Partially addresses https://github.com/celestiaorg/celestia-app/issues/323
=> ci: enable revive

.github/PULL_REQUEST_TEMPLATE.md, .github/mergify.yml, .github/workflows/docker-build.yml, .github/workflows/lint.yml, .github/workflows/sims.yml, .github/workflows/test.yml, readme.md
Partially addresses https://github.com/celestiaorg/celestia-app/issues/564 but blocked on a repo admin renaming `master` to `main` in Github UI
=> chore: rename master to main

.github/mergify.yml
adds a few upcoming release branches to mergify. Note that we haven't created v0.8 or v0.9 branches yet, and shouldn't until later.
=> chore: add v0.7.x, v0.8.x, and v0.9.x to mergify

.golangci.yml
Closes https://github.com/celestiaorg/celestia-app/issues/323
This repo was already compliant with https://github.com/kyoh86/exportloopref so no code changes were necessary
=> ci: enable exportloopref

app/process_proposal.go, app/split_shares.go, app/test/process_proposal_test.go, app/test/split_shares_test.go, pkg/shares/share_merging.go, pkg/shares/share_splitting.go, pkg/shares/shares.go, pkg/shares/shares_test.go, x/payment/types/payfordata.go
This PR moves the share encoding code from core to the app. It makes as few changes as possible, as to make the upcoming refactor for non-interactive defaults actually reviewable.
the code originally came from: 
https://github.com/celestiaorg/celestia-core/blob/5c844685421fcb0ff328bba1752d080420002f41/types/shares.go 
https://github.com/celestiaorg/celestia-core/blob/5c844685421fcb0ff328bba1752d080420002f41/types/shares_test.go
https://github.com/celestiaorg/celestia-core/blob/5c844685421fcb0ff328bba1752d080420002f41/types/share_splitting.go
https://github.com/celestiaorg/celestia-core/blob/5c844685421fcb0ff328bba1752d080420002f41/types/share_merging.go
closes: #623
=> chore: move share encoding logic from core -> app

x/qgb/orchestrator/relayer.go
Closes https://github.com/celestiaorg/celestia-app/issues/628
=> relaying 2/3 signatures correctly

x/payment/types/payfordata.go, x/payment/types/payfordata_test.go
Closes https://github.com/informalsystems/audit-celestia/issues/2
=> fix: invalidate reserved namespace ids in ValidateBasic

Makefile, README.md
Inspired by https://github.com/celestiaorg/celestia-node/blob/main/Makefile#L61-L74
I intentionally introduced a markdownlint violation
```
$ make lint
--> Running linter
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
README.md:62 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Carrers"]
make: *** [lint] Error 1
```
=> chore: add lint and fmt Makefile tasks

x/payment/types/payfordata.go
Closes https://github.com/informalsystems/audit-celestia/issues/4
=> fix: comment for NextHighestPowerOf2

app/prepare_proposal.go, x/payment/types/payfordata.go, x/payment/types/payfordata_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/648
=> Clarify naming of NextHighestPowerOf2

x/payment/types/payfordata.go
Closes https://github.com/celestiaorg/celestia-app/issues/664
Note these tests still pass:
https://github.com/celestiaorg/celestia-app/blob/6ad5686889bbc39f2c7542caa7a15ab58ae7fec0/x/payment/types/payfordata_test.go#L336-L342
=> chore: remove redundant checks

Makefile, go.mod, go.sum, proto/buf.gen.gogo.yaml, scripts/protocgen.sh, x/payment/types/tx.pb.gw.go, x/qgb/types/msgs.pb.gw.go
Closes #553
Update protbuf generator to follow the version in cosmos-sdk upstream - published `v0.45.8`
=> Update protobuf generator

pkg/appconsts/appconsts.go, pkg/shares/info_reserved_byte.go, pkg/shares/info_reserved_byte_test.go
Part of https://github.com/celestiaorg/celestia-app/issues/659
=> Implement InfoReservedByte

x/qgb/orchestrator/errors.go, x/qgb/orchestrator/querier.go, x/qgb/orchestrator/relayer.go
Adds a check on the confirms' commitments before relaying them
=> QGB Relayer add commitments check when relaying confirms

x/payment/types/square_sizes_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/677
=> test: AllSquareSizes

docs/architecture/ADR-005-QGB_posting_confirms_in_reserved_namespace.md, docs/architecture/ADR-005-QGB_reduce_state_usage.md
Closing https://github.com/celestiaorg/celestia-app/issues/656
=> QGB ADR-005 Reducing QGB module state usage

app/app.go, app/encoding/malleated_tx_decoder.go, app/process_proposal.go, app/test/prepare_proposal_test.go
I don't think it makes sense that we are keeping the custom decoder in the app package, since it is strictly related to encoding. 
Moved this in the non-interactive defaults feature branch, but it should probably be its own PR.
=> chore: move malleated transaction decoder to the encoding package

pkg/inclusion/get_commit.go, pkg/inclusion/nmt_caching.go, pkg/inclusion/nmt_caching_test.go, pkg/inclusion/paths.go, pkg/inclusion/paths_test.go, pkg/shares/non_interactive_defaults_test.go
finishes the api for message inclusion 
part of #382 
closes #381
=> feat: finish msg inclusion api

pkg/inclusion/get_commit.go, pkg/inclusion/paths.go, pkg/prove/proof.go, pkg/shares/non_interactive_defaults.go, pkg/shares/share_merging.go, x/payment/types/payfordata.go, x/payment/types/payfordata_test.go, x/payment/types/square_sizes.go, x/payment/types/wirepayfordata.go
Closes https://github.com/celestiaorg/celestia-app/issues/687
Note this doesn't address https://github.com/celestiaorg/celestia-core/issues/853
=> Use `squareSize` instead of `k` or `origSquareSize`

app/app.go, app/split_shares.go, app/test/block_size_test.go, go.mod, go.sum, pkg/da/data_availability_header.go, pkg/prove/proof.go, pkg/prove/proof_test.go, pkg/prove/querier.go, pkg/shares/contiguous_shares_test.go, pkg/shares/shares_test.go, pkg/shares/split_contiguous_shares.go, pkg/shares/split_message_shares.go
This PR introduces a new custom ABCI query that generates the ABCI inclusion proof for a transaction of a specific index. 
Note that this PR does not fix the tx inclusion proof logic to follow the non-interactive defaults, as we haven't merged those yet. It does however alter the integration test to require that transactions include proofs, so we are testing the new ABCI query method.
blocked by https://github.com/celestiaorg/celestia-core/pull/859
closes #698
=> feat: Implement and install new ABCI Query for transaction inclusion proofs 

app/test/fuzz_abci_test.go, testutil/payment/testutil.go
closes #588 
see [comment](https://github.com/celestiaorg/celestia-app/pull/692#discussion_r965515048)
=> test: add test to build random blocks and check if they're valid

docs/architecture/ADR-002-QGB-ValSet.md, docs/architecture/ADR-003-QGB-DataCommitment.md, go.mod, go.sum, proto/qgb/query.proto, testutil/common.go, x/qgb/abci_test.go, x/qgb/keeper/hooks.go, x/qgb/keeper/keeper_attestation.go, x/qgb/keeper/keeper_data_commitment.go, x/qgb/keeper/keeper_valset.go, x/qgb/keeper/query_valset.go, x/qgb/types/genesis.go, x/qgb/types/query.pb.go, x/qgb/types/valset.go
This PR contains the feedback for the https://github.com/celestiaorg/celestia-app/pull/742
=> QGB Feedback on PR #742

pkg/shares/shares_test.go
Spun out of https://github.com/celestiaorg/celestia-app/pull/691
While iterating on the `TestMerge` test, I encountered an unexpected error
```
square size is not a power of two: 0
```
because I failed to declare the square size on the data returned from `generateRandomBlockData`. I moved a variable definition to avoid this scenario.
Very minor improvement. Can be closed if not helpful.
=> chore: define `OriginalSquareSize` inside `generateRandomBlockData`

docs/architecture/ADR-004-QGB_relayer_security.md
Closing https://github.com/celestiaorg/celestia-app/issues/471
=> Qgb universal nonces ADR update

Dockerfile, docker/Dockerfile_ephemeral
Currently, the CI is failing because of not found `gcc` and standard C libraries when building the ephemeral cluster docker image. This PR fixes that.
Also, removes unnecessary `git` install.
=> fix: Update Dockerfiles and fix CI

app/export.go
closes #763 
also notice the branch and [tag](https://github.com/celestiaorg/celestia-app/tree/v0.6.1-rc1-fixed-export) that has this change added to [v0.6.0](https://github.com/celestiaorg/celestia-app/tree/evan/fix-export-v0.6.0), as we will need that when creating a new genesis file for the new testnet
=> fix: update export code to work with v0.46.0

.github/workflows/proto.yml, go.mod
I was using go 1.19 and also the version of the cosmos-sdk specified wasn't right.
=> chore: Go mod tidy on QGB branch

app/estimate_square_size.go, pkg/shares/split_compact_shares.go, pkg/shares/split_compact_shares_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/777
I choose to fix the implementation to match the doc comment because it seems like a leaky abstraction for this function to also return the # of available bytes in the pending share. By removing the second return value, the compact share `Count` more closely matches the sparse share [`Count`](https://github.com/rootulp/celestia-app/blob/5eab874a214861a5de9af2a662c9bcbe352c5608/pkg/shares/split_sparse_shares.go#L87-L90) function signature.
=> fix: compact share `Count`

pkg/shares/shares.go, pkg/shares/split_compact_shares.go, pkg/shares/split_sparse_shares.go
Move `MarshalDelimited*` functions to the files in which they are used. Previously they were located in the top level `shares.go` which makes it non-obvious that `MarshalDelimitedTx` is only applicable to compact shares whereas `MarshalDelimitedMessage` is only applicable to sparse shares.
=> chore: move `MarshalDelimited*` functions

scripts/single-node.sh
the default is `25s` now instead of `5s`
=> fix: update default `timeout_commit` when running `sed` on genesis in `single-node.sh` script

pkg/prove/proof_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/789
=> fix: `joinByteSlice` implementation

.github/workflows/markdown-lint.yml
See https://github.com/celestiaorg/celestia-app/actions/runs/3131501267/jobs/5082905834. Didn't actually pick up linting errors in the `specs` directory. Note that official examples use quotes: https://github.com/igorshubovych/markdownlint-cli/tree/f891b45ee50f621330160e5dcfa47435ac2220f8#globbing-examples
=> Fix markdown lint workflow to actually run on subdirectories properly

pkg/shares/split_compact_shares.go
We will increase the # of reserved bytes from 1 to 2 when we do https://github.com/celestiaorg/celestia-app/issues/711. The current implementation hardcodes only 1 reserved byte rather than relying on `appconsts.CompactShareReservedBytes`.
=> chore: prefer appconsts for # of reserved bytes

app/estimate_square_size.go, pkg/appconsts/appconsts.go, pkg/prove/proof.go, pkg/prove/proof_test.go, pkg/shares/compact_shares_test.go, pkg/shares/split_compact_shares_test.go
Part of https://github.com/celestiaorg/celestia-app/issues/725
Rename `CompactShareContentSize` to `ContinuationCompactShareContentSize` because we will soon introduce a new appconst for `FirstCompactShareContentSize`.
=> chore: rename to `ContinuationCompactShareContentSize`

.github/CODEOWNERS
Inspired by https://github.com/celestiaorg/celestia-core/blob/v0.34.x-celestia/.github/CODEOWNERS
Prerequisite to https://github.com/celestiaorg/celestia-app/issues/807 but doesn't close it. #807 can be tackled on the `specs-staging` branch after this PR merges to `main` because the `specs/` directory doesn't exist on `main`.
=> chore: initial `CODEOWNERS` file

pkg/shares/parse_sparse_shares.go, pkg/shares/shares_test.go, pkg/shares/split_compact_shares.go, pkg/shares/split_sparse_shares.go
Spun out of https://github.com/celestiaorg/celestia-app/pull/781
In https://github.com/celestiaorg/celestia-app/pull/781 , there is a need to calculate the total data length written to a compact share splitter so that a varint of this data length can be written to the first share. It becomes easier to perform this calculation if the utility function `zeroPadIfNecessary` returns the `bytesOfPadding` because the export command can subtract the `bytesOfPadding` from the number of bytes used by all shares in the compact share splitter.
Without this change, it may be possible to calculate the # of bytes written by summing the # of bytes written to shares and the number of bytes in the pending share _prior_ to adding padding to the pending share but this option includes more edge cases.
=> feat: return `bytesOfPadding`

pkg/shares/compact_shares_test.go, pkg/shares/info_byte.go, pkg/shares/info_byte_test.go, pkg/shares/parse_compact_shares.go, pkg/shares/parse_sparse_shares.go, pkg/shares/sparse_shares_test.go, pkg/shares/split_compact_shares.go, pkg/shares/split_sparse_shares.go
Closes https://github.com/celestiaorg/celestia-app/issues/787
=> Rename `InfoReservedByte` to `InfoByte`

pkg/shares/share_splitting_test.go
Define unit tests for transaction splitting. These should be helpful when we tackle https://github.com/celestiaorg/celestia-app/issues/802
=> test: transaction splitting

pkg/shares/parse_compact_shares.go
Spun out of https://github.com/celestiaorg/celestia-app/pull/781
=> chore: rename txLen to unitLen

pkg/shares/share_splitting_test.go, pkg/shares/split_compact_shares.go
Closes https://github.com/celestiaorg/celestia-app/issues/779
=> feat!: stop forcing reserved byte to zero

app/prepare_proposal.go, app/process_proposal.go, pkg/prove/proof.go, pkg/prove/proof_test.go, pkg/shares/compact_shares_test.go, pkg/shares/share_splitting.go, pkg/shares/share_splitting_test.go, pkg/shares/shares.go, pkg/shares/shares_test.go, pkg/shares/sparse_shares_test.go, pkg/shares/split_compact_shares.go, pkg/shares/split_sparse_shares.go, x/payment/types/payfordata.go
Closes https://github.com/celestiaorg/celestia-app/issues/721
=> chore!: remove `NamespacedShares`

pkg/shares/share_merging.go, pkg/shares/share_merging_test.go, pkg/shares/shares.go
Closes https://github.com/celestiaorg/celestia-app/issues/723
Opens https://github.com/celestiaorg/celestia-app/issues/839
=> feat: new `ParseShare` API

pkg/appconsts/appconsts.go, pkg/shares/compact_shares_test.go, pkg/shares/parse_compact_shares.go, pkg/shares/parse_sparse_shares.go, pkg/shares/share_merging.go, pkg/shares/sparse_shares_test.go, pkg/shares/utils.go
Closes https://github.com/celestiaorg/celestia-app/issues/830 specifically:
> Alternatively, if we don't want this to be a ProcessProposal validity rule, we can enforce this type of check when we parse the data square back into block data (e.g. [here](https://github.com/celestiaorg/celestia-app/blob/6b86e91eea1063c27c1ae461eddbe505f778df08/pkg/shares/parse_compact_shares.go#L14))
=> feat: throw error when parsing unsupported share version

pkg/shares/compact_shares_test.go, pkg/shares/parse_sparse_shares.go, pkg/shares/utils.go, pkg/shares/utils_test.go
Move `ParseDelimiter` from `parse_sparse_shares` to `utils.go` because it is used when parsing sparse and compact shares
=> chore: move `ParseDelimiter`

pkg/appconsts/appconsts.go
ADR007 merged and the share package has a README (soon to be godoc package comment) so this doc comment no longer seems necessary
=> Remove doc comment on SparseShare vs CompactShare

pkg/prove/proof.go
This printf statement was accidentally introduced in https://github.com/celestiaorg/celestia-app/pull/781
It should be removed to avoid log spam when developers run `make test`
=> fix: remove debug printf statement

Makefile
I noticed that we no longer need a Makefile `PACKAGES` variable because this repo doesn't contain a `/simulation` directory. We removed sims from workflows in https://github.com/celestiaorg/celestia-app/pull/697 but there wasn't a `/simulation` directory then either.
This makes the `make test` command easier to copy + paste (if for instance you want to add a trailing `-count=1` flag to disable the cache)
Note: cosmos-sdk uses PACKAGE variables [here](https://github.com/cosmos/cosmos-sdk/blob/main/Makefile#L3-L4) but celestia-app doesn't appear to need this extra complexity
=> chore: remove Makefile `PACKAGES`

x/payment/types/wirepayfordata.go
The check on this [line](https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/x/payment/types/wirepayfordata.go#L148) is redundant as it's done [here](https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/x/payment/types/wirepayfordata.go#L160).
Originally discovered by @mpoke in https://github.com/informalsystems/audit-celestia/issues/6#issuecomment-1272940401
=> chore: remove redundant check

pkg/shares/non_interactive_defaults.go, pkg/shares/non_interactive_defaults_test.go
Closes https://github.com/informalsystems/audit-celestia/issues/16
=> fix: FitsInSquare for case with 0 messages

docs/architecture/adr-007-universal-share-prefix.md, pkg/appconsts/appconsts.go, pkg/prove/proof_test.go, pkg/shares/parse_compact_shares.go, pkg/shares/shares.go, pkg/shares/split_compact_shares.go
Motivaiton: "sequence length" is more precise than "data length"
=> chore: rename data length to sequence length

README.md
Inspired by https://github.com/celestiaorg/celestia-node#package-specific-documentation
Addresses https://github.com/celestiaorg/celestia-app/pull/842#pullrequestreview-1139027323
We can keep the share docs in Godoc form or move them back to README.md form because both will render in https://pkg.go.dev/github.com/celestiaorg/celestia-app/pkg/shares
=> Add a package-specific documentation section

pkg/shares/share_merging.go, pkg/shares/share_merging_test.go
After correcting an error in unit tests:
```diff
-			if reflect.DeepEqual(got, tt.want) {
+			if !reflect.DeepEqual(got, tt.want) {
```
unit tests surfaced an error with the current `ParseShares` implementation. The last currentSequence wasn't appended to the result prior to returning.
=> fix: ParseShares failed to append last sequence

x/qgb/orchestrator/confirm_store.go, x/qgb/orchestrator/indexer.go, x/qgb/orchestrator/loader.go
Adds a basic implementation for an in memory store, a transactions' parser, an indexer, an extractor and a loader to QGB.
This stuff is still not used, other subsequent PRs will make use of them. This is just trying to have smaller PRs instead of a giant, big one containing the whole new design.
Adds to https://github.com/celestiaorg/celestia-app/issues/684
=> feat: Add store, indexer, extractor and loader to QGB

.markdownlint.yaml, docs/architecture/adr-006-non-interactive-defaults.md, x/payment/spec/docs.md
Addresses https://github.com/informalsystems/audit-celestia/issues/20#issuecomment-1278896978
Question for reviewers: do we treat ADRs as a snapshot in time or should we update them to reflect changes that take place after the ADR was reviewed?
=> docs: update code block in ADR-006

specs/src/specs/data_structures.md
Closes https://github.com/celestiaorg/celestia-app/issues/728
=> docs: describe message length varint

README.md
I encountered an error:
```
$ celestia-appd tx payment payForData 0101010101010101 0101010101010101 --from validator --keyring-backend test
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account celestia10etmzwghs0rcffu6dzs4wdw6wrumgcu2u3wl67 not found: key not found
```
because I failed to delete the `~/.celestia-app/keyring-test` from a previous devnet. After deleting it, I was able to successfully submit a PFD. This change updates the docs to suggest deleting the entire `~/.celestia-app` directory prior to running the single node script.
=> docs: delete all contents of `~/.celestia-app`

README.md, docs/architecture/adr-002-qgb-valset.md, docs/architecture/adr-003-qgb-data-commitments.md, docs/architecture/adr-005-qgb-reduce-state-usage.md
The markdown lint links CI workflow is [failing](https://github.com/celestiaorg/celestia-app/actions/runs/3296219513/jobs/5439416229). This PR fixes links by updating links to use permalinks.
See https://github.com/celestiaorg/celestia-app/pull/902#issuecomment-1287007498
=> fix: markdown lint links

x/payment/types/payfordata.go, x/payment/types/payfordata_test.go
This PR is a pure refactor that renames `heights` => `treeSizes` because the previous name was slightly misleading. This function doesn't return the heights of the trees in the Merkle mountain range, it returns the number of leaves in each tree. For example, for the unit test that was added:
``` golang
totalSize:  19,
squareSize: 8,
expected:   []uint64{8, 8, 2, 1},
```
the Merkle mountain range looks like
```ascii
// Height
// 3              x                               x
//              /    \                         /    \
//             /      \                       /      \
//            /        \                     /        \
//           /          \                   /          \
// 2        x            x                 x            x
//        /   \        /   \ …
```
=> chore: rename `height` to `treeSizes` in Merkle mountain range

.github/workflows/docker-build.yml
Currently the docker-build workflow attempts to tag releases with 
```
...${{ steps.version.outputs.full }}
```
but the correct string is
```
...${{ steps.tag_version.outputs.full }}
``` 
to match the previous step id of `tag_version`
=> Update docker-build workflow to fix version tags

x/payment/types/payfordata.go
The modified error message was incorrect because it errors when the number of signatures `!= 1`.
=> fix: error message unexpected number of signatures

pkg/shares/shares_test.go, pkg/shares/sparse_shares_test.go, pkg/shares/split_sparse_shares.go
Closes https://github.com/celestiaorg/celestia-app/issues/873
Closes https://github.com/informalsystems/audit-celestia/issues/20
=> refactor: remove count from spare share splitter

.gitignore
Add `__debug_bin` to gitignore because this file is generated when you run tests in Debug mode inside VSCode.
=> gitignore `__debug_bin`

x/payment/client/cli/query.go, x/payment/client/cli/tx.go, x/payment/doc.go, x/payment/keeper/keeper.go, x/payment/module.go, x/payment/payfordata.go, x/payment/spec/docs.md, x/payment/types/events.go
=> Update docs for payment module

x/payment/keeper/gas_test.go, x/payment/keeper/keeper.go
Closes https://github.com/celestiaorg/celestia-app/issues/431
=> feat: charge gas per message shares

app/app.go, app/test/block_size_test.go, scripts/single-node.sh, testutil/test_app.go, x/payment/types/builder_options.go, x/payment/types/payfordata_test.go
This reverts commit 3598fe28772ed1ad55a0bc0b76d222828d35960f.
=> Revert "chore!: rename `TIA` to `CLS` (#859)"

x/payment/spec/docs.md
Update payment docs to account for how message share commitment is generated post ADR 008.
Note: targets feature branch
=> docs: update "How is the `MessageShareCommitment` generated?"

.golangci.yml, app/estimate_square_size.go
Enable `prealloc` linter in `.golangci.yml
Closes #676
=> chore: Enable prealloc linter

app/test/block_size_test.go, app/test/prepare_proposal_test.go, app/test_util.go, testutil/payment/testutil.go, x/payment/client/cli/wirepayfordata.go, x/payment/payfordata.go, x/payment/types/payfordata_test.go, x/payment/types/wirepayfordata.go, x/payment/types/wirepayfordata_test.go
If ADR 008 is adopted, only one message share commitment is signed so this PR renames a plural function to be singular. This is a follow-up to https://github.com/celestiaorg/celestia-app/pull/937 and could've been included in that PR.
Note: targets feature branch
=> chore: rename SignShareCommitments -> SignShareCommitment

Makefile
- Reorder commands into groups:
1. Install
2. Build
3. Protobuf
4. Docker
5. Lint
6. Test
- Add `.PHONY` targets to commands that don't generate files
- Add `echo` statements to describe what command is doing
=> chore: improve Makefile

testutil/testnode/full_node_test.go, testutil/testnode/node_interaction_api.go
Add check on `FillBlock` -> `squareSize` arg:
- Check squareSize should be > 2
- Check squareSize is a pow of 2
Closes #867
=> feat: Add checks on FillBlock squareSize

app/test/block_size_test.go
adds a check for gas usage during the integration test
closes #389
=> chore: test for gas usage

cmd/celestia-appd/cmd/root.go
Supersedes https://github.com/celestiaorg/celestia-core/pull/885
Closes https://github.com/celestiaorg/celestia-core/issues/812 
Closes https://github.com/celestiaorg/celestia-core/issues/867
Closes https://github.com/celestiaorg/celestia-app/issues/590
=> feat!: override default mempool params

pkg/shares/shares_test.go
apparently I forgot to un-comment some important tests
=> chore: uncomment out tests

pkg/shares/share_merging.go, pkg/shares/shares_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/840
Reduce the public API of the shares package by unexporting `Merge`. This function doesn't appear invoked by celestia-node ([search](https://github.com/celestiaorg/celestia-node/search?q=Merge)) so it doesn't seem necessary to export.
=> chore!: unexport merge

Dockerfile
Fixes the following error:
```
---> 0119ef2bed23
Step 5/12 : RUN make build
---> Running in 8f545cb05d38
make: git: No such file or directory
make: git: No such file or directory
--> Updating go.mod
```
<--- 
Please provide an explanation of the PR, including the apprioprate context,
background, goal, and rationale. If there is an issue with this information,
please provide a tl;dr and link the issue. 
-->
=> fix: add git to Dockerfile build

app/estimate_square_size_test.go, app/malleate_txs.go, app/parse_txs.go, app/prepare_proposal.go, app/process_proposal.go, app/test/block_size_test.go, app/test/prepare_proposal_test.go, app/test/process_proposal_test.go, app/test_util.go, go.mod, go.sum, pkg/prove/proof.go, pkg/prove/proof_test.go, pkg/shares/parse_sparse_shares.go, pkg/shares/share_merging.go, pkg/shares/share_merging_test.go, pkg/shares/share_splitting.go, pkg/shares/shares_test.go, pkg/shares/sparse_shares_test.go, pkg/shares/split_sparse_shares.go, pkg/shares/utils.go, pkg/shares/utils_test.go, testutil/testnode/full_node_test.go, x/blob/types/payforblob.go, x/blob/types/wirepayforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/1022
Does not rename all instances of `message` to `blob` see https://github.com/celestiaorg/celestia-app/issues/995
=> chore!: upgrade to celestia-core `v1.8.0-tm-v0.34.20`

x/blob/keeper/keeper.go
=> chore: rename gas descriptor to use `blob` instead of `data`

testutil/testnode/full_node.go, testutil/testnode/full_node_test.go, testutil/testnode/node_init.go
We need to be able to modify the genesis state when using the testnode. This PR refactors the testnode to allow for that. It also includes a helper function that handles creation of this genesis state and simplify the process of starting an in process node. 
closes #1037 
part of/blocking #658 
spun out of and blocking #1029
=> chore!: refactor the testnode to expose the genesis state 

testutil/testnode/full_node.go, testutil/testnode/full_node_test.go, testutil/testnode/rpc_client.go
@renaynay found that we weren't actually waiting for the tendermint node to shutdown during cleanup. This might be causing an issue when running multiple different nodes in CI (not locally). We also were not returning errors for the cleanup functions, which could be silencing useful errors.
=> chore!(testnode): return errors in cleanup functions and wait for cleanup

x/qgb/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/501
=> docs: add qgb module readme

pkg/shares/parse_sparse_shares.go, pkg/shares/shares_test.go, x/blob/types/errors.go, x/blob/types/wirepayforblob.go, x/blob/types/wirepayfordata_test.go
Follow up to https://github.com/celestiaorg/celestia-app/pull/1028 where I didn't propagate the new struct field `ShareVersion` to all instances of `coretypes.Blob`. 
Unfortunately Go isn't exhaustive on specifying struct fields so I wasn't made aware of this miss until working on an unrelated change. Open to ideas on how to have higher confidence all instances have been addressed. [The non_exhaustive attribute](https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute) makes me think Rust structs are exhaustive by default.
=> fix: propagate share version

mlc_config.json
celestia-app is observing several false positives on the markdown lint link checker. See https://github.com/celestiaorg/celestia-app/actions/runs/3586356956/jobs/6035453041#step:4:318
this PR attempts to mitigate by configuring markdown lint link checker to retry when an HTTP 429 is observed. See https://github.com/gaurav-nelson/github-action-markdown-link-check#too-many-requests
=> ci: markdown link checker config

cmd/celestia-appd/cmd/root.go
cherry-picks default changes closes #1094
=> chore: cherry pick default changes

scripts/single-node.sh
If you try connecting a local celestia-node instance to celestia-app that is running via this script, it fails with:
```error
$ celestia bridge init --p2p.network "test"
Error: invalid network specified: test
```
Ref:
https://github.com/celestiaorg/celestia-node/blob/52048ce466d58c1688ba48de0a2656b27306634d/nodebuilder/p2p/network.go#L12-L19
=> feat: use `private` chain ID for single node

pkg/appconsts/appconsts.go
Update godoc comment for `FirstCompactShareSequenceLengthBytes` to account for https://github.com/celestiaorg/celestia-app/pull/850
=> docs: update FirstCompactShareSequenceLengthBytes

docs/architecture/adr-007-universal-share-prefix.md, pkg/shares/split_compact_shares.go
Closes https://github.com/celestiaorg/celestia-app/issues/1097
=> chore: rename to sequence len

docs/architecture/adr-007-universal-share-prefix.md, pkg/shares/share_merging.go, pkg/shares/shares.go, pkg/shares/shares_test.go, pkg/shares/split_compact_shares.go, pkg/shares/split_sparse_shares.go
Cherry-pick two recent changes to the v0.11.x release branch so that we can create a v0.11.1 release and upgrade to that in celestia-node. `share.RawData()` is needed to complete the celestia-node side of https://github.com/celestiaorg/celestia-node/issues/1448. The rename to sequence len was also cherry-picked to avoid merge conflicts
=> chore: cherry-picks for v0.11.1

x/blob/types/payforblob.go
=> fix: pay for blob typo(s) and redundant import

cmd/celestia-appd/cmd/root.go
=> chore: switch default keyring backend

x/blob/keeper/gas_test.go, x/blob/keeper/keeper.go
Replaces gas per blob byte constant with stored param
-- Note - To be merged after #1031
=> feat: use kvstore to fetch gas per blob byte

app/app.go
as noticed by @cmwaters, we accidentally removed setting the app's msg service router. This is why this functionality was present in v0.6.0, but not in v0.10.0. The only usage of the msg service router is for the gov keeper, so it doesn't have an effect on other modules. 
this fix is tested in a followup PR #1160 
closes #1158
=> fix!: pass the baseapp msg service router

app/write_square.go, app/write_square_test.go, pkg/inclusion/paths.go, pkg/inclusion/paths_test.go, pkg/shares/non_interactive_defaults.go, pkg/shares/non_interactive_defaults_test.go, pkg/shares/share_merging_test.go, pkg/shares/share_splitting.go
Closes https://github.com/celestiaorg/celestia-app/issues/1149
=> feat: implement non-interactive default rules for reduced padding

pkg/appconsts/appconsts.go, pkg/shares/split_sparse_shares.go
This constant is an implementation detail and shouldn't be exported from celestia-app
=> chore: un-export namespaced padded share bytes

app/check_tx.go, app/test/block_size_test.go, app/test/check_tx_test.go, testutil/blobfactory/payforblob_factory.go, testutil/blobfactory/test_util.go, x/blob/client/cli/wirepayfordata.go, x/blob/client/testutil/integration_test.go, x/blob/types/errors.go
fixes two bugs, one where we were creating PFD transactions without actually wrapping them with a blob :face_with_spiral_eyes:, and then another bug where we should have been checking for that during checkTx. 
closes #1165 
blocking, and related to #1168
=> fix: reject txs from the mempool that have a PFB but not a blob

app/test/std_sdk_test.go, testutil/testnode/sign.go, x/blob/types/builder.go
Adds a smoke test for some of the std cosmos-sdk modules. This test does not test that the state was changed as expected, only that the msgs included in the transactions were applied successfully. 
blocked by #1159, as the test for submitting a governance proposal currently fails until that is merged
=> chore!: Test std modules

specs/src/specs/data_structures.md
Part of https://github.com/celestiaorg/celestia-app/issues/1153
Should only be merged if https://github.com/celestiaorg/celestia-app/pull/1181 is merged
=> chore: uint32 for message size

Makefile, app/test/block_size_test.go, app/test/fuzz_abci_test.go, testutil/testnode/full_node_test.go, x/blob/client/testutil/integration_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1025
Add the Makefile command `test-short` which runs unit tests in `-short` mode. On my machine, `make test-short` completes in ~15 seconds
=> chore: make `test-short`

app/process_proposal.go, pkg/inclusion/get_commit.go, x/blob/types/blob_tx.go, x/blob/types/payforblob.go, x/blob/types/payforblob_test.go
part of #388, and split apart from #1154
this PR uses a new mechanism to generate the share commit that can create a commitment over multiple blobs. We don't yet support multiple blobs per PFB, so this is currently effectively hashing the normal share commitment.
=> feat!: use MultiShareCommitments instead of a single ShareCommitment

.github/workflows/housekeeping.yml
The housingkeeping workflow was failing due to forks not having write access during workflow runs. This is for security reasons. However there are many non-security critical tasks that require write access, such as requesting reviewers or making comments on a PR. For these, the `pull_request_target` trigger can be used, as it allows write access to forks for the select workflows. 
I tested this on a personal github org and it worked for both native branches and forks. 
**NOTE**:  the reason the workflow is not running on this PR is because of the chicken and egg issue of updating workflows, in that the update needs to be on main in order for it to run. 
Closes https://github.com/celestiaorg/.github/issues/19
=> .github: fix permissions issue on pr review request on forks

app/test/block_size_test.go, pkg/appconsts/appconsts.go, testutil/blobfactory/payforblob_factory.go, testutil/testnode/node_interaction_api.go, x/blob/client/cli/wirepayfordata.go, x/blob/payforblob.go, x/blob/types/blob_tx.go, x/blob/types/blob_tx_test.go, x/blob/types/payforblob.go, x/blob/types/payforblob_test.go, x/blob/types/test/blob_tx_test.go
part of #388 and split off from #1154. This is just a minor refactor for `NewMsgPayForBlob` to accept a `tmproto.Blob`, instead of the individual components.
=> chore!: refactor NewMsgPayForBlob to accept blobs

pkg/prove/proof_test.go
This is a minor refactor that I extracted from a larger in-progress PR. Prior to this PR, implementation details for compact shares leaked out to the `prove` package. Instead of leaking these implementation details, we can use the [`RawData()`](https://github.com/rootulp/celestia-app/blob/c72e9c1935e296ff599728f7fa4b9952d62da1b7/pkg/shares/shares.go#L99-L107) method.
=> chore: refactor `stripCompactShares`

x/qgb/abci_test.go, x/qgb/keeper/keeper_data_commitment.go
Fixes https://github.com/celestiaorg/celestia-app/issues/1204
Now, the ranges will be as follows, with a data commitment window of 400:
- 0-399
- 400-799
- 800-1199
- ...
=> fix: fix data commitment ranges overlap

app/estimate_square_size.go, app/estimate_square_size_test.go, app/parse_txs.go, app/process_proposal.go, go.mod, go.sum, pkg/shares/share_splitting.go, pkg/shares/shares_test.go, x/blob/types/blob_tx_test.go
bumps core to v1.13.0-tm-v0.34.23
blocking #1154 and #1042
=> chore: bump core to v1.13.0-tm-v0.34.23

testutil/blobfactory/payforblob_factory.go
The parameter `size` in `RandBlobTxsWithAccounts` accepts positive values as well as negative.
However, passing a negative value will make the random generator panic, thus making the integration tests fail without any clear error message. An example of this: https://github.com/celestiaorg/celestia-app/actions/runs/3911542927/jobs/6685657620
Thus, adding a check on `size` would fix this and never allow anyone to pass a negative value.
=> fix: add size check in RandBlobTxsWithAccounts

app/prepare_proposal.go, app/test/prepare_proposal_test.go, pkg/appconsts/appconsts.go, testutil/testfactory/common.go
this PR is the quick solution to #1209. Note that this is not a new block validity rule, only an extra check during `PrepareProposal`.
=> feat!: Add a default transaction limit

cmd/celestia-appd/cmd/root.go
Enable snapshots for testnet to enable validators to more quickly deploy nodes/run experiments
=> Enable snapshots

app/check_tx.go, app/estimate_square_size.go, app/parse_txs.go, app/write_square.go, x/blob/types/blob_tx.go, x/blob/types/test/blob_tx_test.go
=> chore: consolidate processedBlobTx with BlobTx

testutil/blobfactory/payforblob_factory.go
Similar to https://github.com/celestiaorg/celestia-app/pull/1235, the `blobCount` is used in the `rand` function, thus needs always to be strictly positive.
=> fix: add check to `blobCount` in RandBlobTxsWithAccounts

README.md
This PR is totally optional but I just learned that GitPOAP has a badge: https://docs.gitpoap.io/api#get-v1repoownernamebadge 
The motivation for adding a badge to the README is that it may increase awareness for contributors that they are eligible.
=> chore: add GitPOAP badge to README

testutil/testnode/full_node.go
by not setting the testing directory during integration tests, we end up saving the LOCK and LOG files from the snapshot directory to permanent directories instead of the temp ones created during the test.
this can be testing by running the integration tests locally without this change, and then with this change.
=> fix: stop saving snapshot files to wrong directory during tests

specs/src/specs/data_structures.md
Closes https://github.com/celestiaorg/celestia-app/issues/1175 
See the implementation [here](https://github.com/celestiaorg/celestia-app/blob/d7ac0b84765db3f649cd82326e3ead066d164637/pkg/shares/tail_padding.go#L9-L21).
=> docs: spec tail padding share

x/blob/doc.go
`x/blob/specs/docs.md` was removed in favor of `x/blob/README.md`
=> docs: fix path to x/blob docs

pkg/shares/split_compact_shares_test.go
If I use the compact share splitter to add a transaction that is exactly `FirstCompactShareContentSize`, I'd expect when I run `Export` or `Count` to just get a single share. But this test is failing
**UPDATE** I worked out what was missing and have adjusted the tests accordingly
=> chore: add more test cases for the compact share splitter

docker/entrypoint.sh
Hello team,
This is an small feature/fix that prevents any error when the container starts and try to create the folder in `${CELESTIA_HOME}/data` using the option `-p` in the `mkdir` command.
Thank you!
=> feat: Prevent any errors when creating the data folder

.github/workflows/lint.yml
Update to the latest release of golangci-lint: https://github.com/golangci/golangci-lint/releases while I try debugging an issue with golangci-lint failures on a different PR
=> chore: update to golangci-lint 1.50.1

cmd/celestia-appd/cmd/root.go, x/blob/client/cli/payforblob.go, x/blob/client/cli/testrandblob.go, x/blob/client/cli/tx.go, x/blob/client/testutil/integration_test.go
ATM, `test-infra` repo is using my fork of celestia-app, which is not ok. 
We need a CLI command for tests to trigger PFBs from apps' side, hence we have added another command named `TestRandBlob`
This PR contains another renaming, touching removal of `Wire` prefixes
Ref: https://github.com/celestiaorg/test-infra/issues/159
=> feat: add testRandBlob CLI for testground tests

x/qgb/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/1254
We could add more documentation after executing the command to give an example output, but I guess it's better to do it after we have mocked QGB deployed so that we have the same output as users.
=> docs: add QGB verify command docs

go.mod, go.sum, pkg/proof/proof.go, pkg/proof/proof_test.go, pkg/proof/querier.go
Latest v0.12.0-rc5 is not compliant with what node will have to upcoming v0.7.0-rc`x`, as celestia-node is using nmt `v0.14.0` and dropped v0.13.0
This PR fixes this, hence I propose to make a `v0.12.0-rc6` afterwards 🙏 
In addition, this PR cleans up codec from the signature that is not used in `NewTxInclusionProof ` anymore
=> chore!: bump `nmt` from v0.13 to v0.14 and remove the codec from `NewTxInclusionProof`

app/test/std_sdk_test.go, go.mod, go.sum, scripts/single-node.sh, testutil/common.go, testutil/testnode/node_init.go, x/qgb/abci_test.go, x/qgb/keeper/keeper.go
Closes https://github.com/celestiaorg/celestia-app/issues/1329
Depends on a new release of  the cosmos-sdk.
=> feat: remove orchestrator address

app/write_square_test.go
Addresses: https://github.com/celestiaorg/celestia-app/issues/1102
> this test could be as simple adding an additional check to an existing test that creates square not the max square size, and ensure that each transaction is getting included in the block.
`Test_finalizeLayout` already includes tests where a non max square size square is created and none of the transactions are dropped so I'm a little confused about this. I've added tests to include that we are dropping transactions if the blobs exceed the square size.
=> testing: add extra tests to ensure we remove txs correctly

pkg/shares/namespaced_padding.go, pkg/shares/namespaced_padding_test.go, pkg/shares/parse_sparse_shares.go
Implements the proposal in https://github.com/celestiaorg/celestia-app/issues/783#issuecomment-1419007954. 
Closes https://github.com/celestiaorg/celestia-app/issues/1136
Closes https://github.com/celestiaorg/celestia-app/issues/783
Opens https://github.com/celestiaorg/celestia-app/issues/1344
=> feat!: differentiate namespaced padded shares

cmd/celestia-appd/cmd/overrides.go, cmd/celestia-appd/cmd/root.go, pkg/appconsts/consensus_consts.go
This PR introduces a function that overrides configs when starting the in process tendermint node from the cli. This approach has the benefit of keeping the override logic in the application but still allows for all CI and tests to run as fast as we want.
close #1326
=> feat: override consensus configs

testutil/testnode/node_init.go
I will need this on the orchestrat-relayer repo tests to be able to sign attestations with the private key that was  used to initialized the testnode validator.
=> feat: expose the EVM private key used to create the testnode validator

pkg/proof/proof.go, pkg/proof/proof_test.go, x/qgb/client/verify.go
Closes https://github.com/celestiaorg/celestia-app/issues/1241
The new name `TxShareRange` is consistent with https://github.com/celestiaorg/celestia-app/blob/fd6382278f6fff4ab3d272e5f3034203c9378126/pkg/proof/proof.go#L66
Technically API breaking because this is an exported function but I doubt there are external users of this function.
=> chore!: rename `TxSharePosition` to `TxShareRange`

Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/1339
```shell
$ make
Choose a command run in celestia-app:
help           Get more info on make commands.
build          Build the celestia-appd binary into the ./build directory.
install        Build and install the celestia-appd binary into the $GOPATH/bin directory.
mod            Update go.mod.
mod-verify     Verify dependencies have expected content.
proto-gen      Generate protobuf files. Requires docker.
proto-lint     Lint protobuf files. Requires docker.
proto-format   Format protobuf files. Requires docker.
build-docker   Build the celestia-appd docker image. Requires docker.
lint           Run linters golangci-lint and markdownlint.
fmt            Format files per linters golangci-lint and markdownlint.
test …
```
=> feat: `make help`

pkg/inclusion/paths.go, pkg/shares/non_interactive_defaults.go, x/blob/types/payforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/1101 b/c deletes a duplicate function definition. `MinSquareSize` in the shares package already has unit tests [here](https://github.com/celestiaorg/celestia-app/blob/150e65de9a6559a64693be88c591d541b2812a8b/pkg/shares/non_interactive_defaults_test.go#L323).
=> chore: deduplicate `MinSquareSize`

app/test/std_sdk_test.go, testutil/testnode/full_node.go
Closes https://github.com/celestiaorg/celestia-app/issues/1358
=> feat: register testnode cleanup in teardown

app/test/qgb_rpc_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1343
=> test: add QGB queries test

x/qgb/keeper/keeper_data_commitment.go, x/qgb/keeper/keeper_data_commitment_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1388
=> feat: data commitment for height support for yet to be committed heights

.github/workflows/ci_release.yml, .github/workflows/lint.yml
I found the **Before** workflow diagram a bit confusing. I would expect all linters to run as part of the lint workflow and I wouldn't expect lint to block splitting up test files.
Before | After
--- | ---
TBH I don't know why **test / cleanup-runs** shows up in the lint block but I think we can get rid of that job soon via a different PR
=> ci: consolidate linters in lint workflow

.github/workflows/ci_release.yml
This is no longer needed because of the docker build and publish workflow
=> chore: remove residual docker build

scripts/single-node.sh
=> fix: remove changing unnecessary parameters in single-node.sh

testutil/testnode/full_node.go
Deletes testnode home directory during cleanup.
In fact, we have the following structure when creating the testnode: `/tmp/TestOrchestrator3541559682/001/.celestia-app/config`:
- we will delete `/tmp/TestOrchestrator3541559682/001/.celestia-app`  ourselves in the cleanup (this PR)
- the `testing` package will delete `/tmp/TestOrchestrator3541559682` automatically
This would leave the created `t.tempDir()` empty and hopefully reduce the frequency we see this flakiness https://github.com/celestiaorg/celestia-app/actions/runs/4242679413/jobs/7374501607
=> chore: delete testnode home dir during cleanup

docs/architecture/adr-001-abci++-adoption.md, docs/architecture/adr-002-qgb-valset.md, docs/architecture/adr-003-qgb-data-commitments.md, docs/architecture/adr-004-qgb-relayer-security.md, docs/architecture/adr-005-qgb-reduce-state-usage.md, docs/architecture/adr-006-non-interactive-defaults.md, docs/architecture/adr-007-universal-share-prefix.md, docs/architecture/adr-008-square-size-independent-message-commitments.md, docs/architecture/adr-009-non-interactive-default-rules-for-reduced-padding.md, docs/architecture/adr-011-optimistic-blob-size-independent-inclusion-proofs-and-pfb-fraud-proofs.md, docs/architecture/adr-012-sequence-length-encoding.md, docs/architecture/adr-template.md
Addresses https://github.com/celestiaorg/celestia-app/pull/1161#issuecomment-1437293103
1. Do we want to make the same change across other celestiaorg repos? 
2. Should we consider an org wide ADR template?
1. https://github.com/celestiaorg/celestia-app/issues/1415
=> docs: hoist ADR status

README.md
The current code coverage link takes you to a page that displays the code coverage on the `master` branch which isn't maintained on this repo. After this PR, the link takes you to the code coverage page for the `main` branch.
=> docs: fix code coverage link

specs/src/rationale/message_block_layout.md
This aims to clarify that the minimum square size in non-interactive default rules should be a power of 2. For example, for a message of length 23,  the minimum square size is  `8*8` (but not `5*5`). (based on a discussion in Slack)
=> chore: specifies minimum square size in non-interactive default rules

pkg/wrapper/nmt_wrapper_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1422
Motivation: I was reading through nmt_wrapper.go to prepare an ADR and got confused by the usage of ` appconsts.ContinuationSparseShareContentSize+1`. I made a few changes to the test file for clarity & maintainability.
=> chore: improve nmt wrapper tests

testutil/testnode/full_node.go, testutil/testnode/rpc_client.go
Now that this function, apparently, reduces flakiness a lot (I haven't seen any on orchestrator-relayer repo). I guess we can put it in the start node cleanup so that users won't have to worry about it.
=> fix: better way to delete tendermint config folder

go.mod, go.sum
bumping core before cutting v0.12.0 so that we have a cat up our sleeves :eyes:
=> chore: bump core to v1.15.0

pkg/proof/proof.go, pkg/wrapper/nmt_wrapper.go, pkg/wrapper/nmt_wrapper_test.go
While reviewing the NMT wrapper implementation and attempting to write its specs, came across a contradiction in the wrapper's design. On one hand, the wrapper is intended to encapsulate an instance of NMT and re-define/modify some of its APIs, specifically the [`Push`](https://github.com/celestiaorg/celestia-app/blob/6d27b78aa64a749a808e84ea682352b8b551fbd7/pkg/wrapper/nmt_wrapper.go#L80) method. On the other hand, the wrapper also exposes the [`Tree()`](https://github.com/celestiaorg/celestia-app/blob/6d27b78aa64a749a808e84ea682352b8b551fbd7/pkg/wrapper/nmt_wrapper.go#L112) method, which returns a pointer to the underlying NMT tree and thus allows direct access to the tree and enables arbitrary manipulation of the underlying tree outside of the intended control of the wrapper. For …
=> feat!: removes the `Tree` method from the NMT wrapper and introduces the `ProveRange` API

testutil/testnode/full_node.go
Allows customising the `chainID` of the testnode.
=> refactor(testutil/testnode): Allow passing chainID to testnode constuctor

cmd/celestia-appd/cmd/root.go
This PR simply adds the option via a new flag to log directly to a file. This feature was requested by @Bidon15 to not have to use the `&>` in the cli. If this turns out to be a desirable feature, we can easily expand on this in the future.
=> feat: add the ability to log directly to a file 

.github/workflows/issue-label-automation.yml, .github/workflows/project-automation.yml
Closes https://github.com/celestiaorg/celestia-app/issues/1455
The issue label automation was inspired by https://github.com/celestiaorg/celestia-node/pull/1877
The project automation uses [add-to-project](https://github.com/actions/add-to-project)
=> chore: issue label and project automation

.yamllint.yml, Makefile, README.md
Closes https://github.com/celestiaorg/celestia-app/issues/1403
yamllint config copied from https://github.com/celestiaorg/.github/blob/main/.yamllint.yml
=> chore: run hadolint and yamllint during `make lint`

docs/spec/nmt-wrapper.md
This PR includes a minor modification on the NMT wrapper spec requested by @liamsi and also previously discussed in https://github.com/celestiaorg/celestia-app/pull/1442.
This PR briefly mentions that in the extended data square,  `Q3` can be derived from `Q1` or `Q2`, with a pointer to the relevant spec.
=> chore: clarifies that Q3 can be computed from Q1 as well

.github/CODEOWNERS
Inspired by https://github.com/celestiaorg/celestia-app/pull/1481#pullrequestreview-1337892356 😆
=> chore: add Sanaz as NMT wrapper code owner

pkg/da/data_availability_header.go
This PR extracts min share creation into an exported function so that celestia-node can depend on it canonically without duplicating code and risking error.
=> feat(pkg/da): Extract min share creation into separate function for convenience

Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/1478
The before / after binaries are the exact same size
```
-rwxr-xr-x    1 rootulp  staff  81822242 Mar 13 11:58 celestia-appd-after
-rwxr-xr-x    1 rootulp  staff  81822242 Mar 13 11:57 celestia-appd-before
```
Based on a `./celestia-appd --help` invocation, they appear to behave identically
=> chore: remove packr2

app/app.go, app/module.go, app/module_test.go
Fixes an issue identified in https://github.com/celestiaorg/itn-doc/issues/168
Verified genesis.json contains `utia` in the gov module in [this diff](https://www.diffchecker.com/Q14DBeHB/)
=> feat!: specify `utia` as denom for gov module genesis

.github/workflows/gh-pages.yml
Manually triggering this workflow previously wouldn't deploy to the main `branch`. After this change it does.
=> ci: deploy main on workflow dispatch

docker/entrypoint.sh
Kubernetes and other container schedulers and runtimes send Unix signals to PID 1 in the container.
Currently, PID 1 is the call of `entrypoint.sh`, which starts the celestia-app with another PID. Therefore celestia-app never receives Unix signals (eg. SIGTERM) that where sent.
This PR changes the `entrypoint.sh` in such a way that celestia-app replaces the process itself. This way celestia-app will be PID 1 and then receives signals inside the container.
Interesting read:
- https://hynek.me/articles/docker-signals/
=> fix: signal handling for container

x/blob/README.md
Update `CreateCommitment` docs to reflect:
1. there isn't one commitment for multiple blobs (this was briefly introduced when we added PayForBlobs but reverted in https://github.com/celestiaorg/celestia-app/issues/1231) 
2. the duplicate namespace ID prefix to match up with NMT subtree roots
=> docs: improve CreateCommitment docs

app/estimate_square_size_test.go, pkg/da/data_availability_header.go, pkg/proof/proof.go, pkg/shares/compact_shares_test.go, pkg/shares/padding.go, pkg/shares/padding_test.go, pkg/shares/parse_sparse_shares_test.go, pkg/shares/parse_test.go, pkg/shares/powers_of_two.go, pkg/shares/powers_of_two_test.go, pkg/shares/share_builder.go, pkg/shares/share_builder_test.go, pkg/shares/share_splitting.go, pkg/shares/share_splitting_test.go, pkg/shares/shares_test.go, pkg/shares/split_compact_shares.go, pkg/shares/split_compact_shares_test.go, pkg/shares/split_sparse_shares.go, x/blob/types/payforblob.go, x/blob/types/payforblob_test.go
Context here: #1490 
closes #1490
=> chore: got rid of most panics in share pkg

go.mod, go.sum
This PR bumps `celestia-app` to using `v.1.15.1` which includes a patch to fix `SignedBlockEvents` which were causing validator hash mismatches.
=> chore: bump core to v1.15.1

go.mod, go.sum
Re-apply https://github.com/celestiaorg/celestia-app/pull/1534 to the v0.13.x release branch because [celestia-core/v1.15.1-tm-v0.34.23](https://github.com/celestiaorg/celestia-core/releases/tag/v1.15.1-tm-v0.34.23) contains a bug fix
=> fix: bump core to v1.15.1

go.mod, go.sum, pkg/wrapper/nmt_wrapper.go, pkg/wrapper/nmt_wrapper_test.go, x/blob/types/payforblob.go
Upgrade to NMT [v0.15.0](https://github.com/celestiaorg/nmt/releases/tag/v0.15.0) which contains improved error handling. Will cherry-pick this to the release branches after this merges: v0.12.x, v0.13.x, v0.14.x
=> chore: upgrade to nmt v0.15.0

go.mod, go.sum, pkg/wrapper/nmt_wrapper.go, pkg/wrapper/nmt_wrapper_test.go, testutil/testnode/full_node.go, testutil/testnode/full_node_test.go, x/blob/types/payforblob.go
Cherry-pick the following commits to the v0.12.x release branch:
1. https://github.com/celestiaorg/celestia-app/commit/ee84e3de2ea4d45537f95477c2bc6006b28a418c
2. https://github.com/celestiaorg/celestia-app/commit/909a566233917925cb4936ce21948664cdc6c204
Will create v0.12.2 after this merges
=> chore: bump NMT to v0.15.0 

README.md, scripts/build-run-single-node.sh, scripts/single-node.sh
This PR is a simple change to the single node script to use a randomly generated tmp directory instead of the default directory.
=> feat: add a tmp dir to the single node script

go.mod, go.sum, pkg/wrapper/nmt_wrapper.go, pkg/wrapper/nmt_wrapper_test.go, x/blob/types/payforblob.go
Cherry-pick https://github.com/celestiaorg/celestia-app/commit/ee84e3de2ea4d45537f95477c2bc6006b28a418c to the v0.13.x release branch. Will cut a new v0.13.x RC after this merges.
=> chore: bump NMT to v0.15.0

.github/workflows/ci_release.yml, .github/workflows/docker-build-publish.yml, .github/workflows/housekeeping.yml, .github/workflows/lint.yml
Tracked by: https://github.com/celestiaorg/devops/issues/140
=> chore: pin version of `celestiaorg/.github` workflows and actions

pkg/da/data_availability_header.go, pkg/da/data_availability_header_test.go, pkg/inclusion/get_commit.go, pkg/inclusion/nmt_caching.go, pkg/inclusion/nmt_caching_test.go
Rename RowsRoots to RowRoots to conform with ColumnRoots.
- Closes #1609
=> chore!: rename `RowsRoots` => `RowRoots`

app/test/process_proposal_test.go, testutil/blobfactory/payforblob_factory.go
Closes https://github.com/celestiaorg/celestia-app/issues/1558
=> test: ProcessProposal with invalid namespace in index wrapped PFB tx

specs/src/README.md, specs/src/SUMMARY.md, specs/src/specs/data_structures.md, specs/src/specs/public_key_cryptography.md
Closes https://github.com/celestiaorg/celestia-app/issues/1440
=> docs: public key crypto specs

.github/workflows/github-pages.yml
An attempt to stop this Github action from running for fork branches
=> ci: stop Deploy PR Preview for fork branches

pkg/shares/shares.go
Will probably help for debugging.
=> refactor(pkg/shares): Add length of share to err message for SequenceLen

cmd/celestia-appd/cmd/root.go, pkg/appconsts/appconsts.go, testing/txsim/account.go, testing/txsim/send.go, testing/txsim/sequence.go
Uses a constant in th `appconsts` package for the `DefaultMinGasPrice` that users can import.
=> feat: introduce DefaultMinGasPrice to appconsts

x/blob/module.go
This is pretty standard to do in the sdk, not sure how we haven't done this yet given over two years of running the state machine and audits lol 
Everything was still occurring via the legacy sdk.Router, but still...
=> chore: register blob msg server in module

x/blob/types/payforblob.go
The Cosmos SDK docs are pretty confusing. They describe two different ways to define a message:
1. https://docs.cosmos.network/v0.46/building-modules/messages-and-queries.html#msg-services
2. https://docs.cosmos.network/v0.46/building-modules/messages-and-queries.html#legacy-amino-legacymsgs
`MsgPayForBlobs` uses option 2. This PR attempts to clarify that.
=> chore: document that `MsgPayForBlobs` implements LegacyMsg interface

app/app.go, app/test/std_sdk_test.go
This PR removes legacy text proposals. While it is still possible to submit other proposals that are functionally very similar, here we are being explicit by removing the ability to handle text proposals.
part of #1593
=> feat!: Remove support for legacy plain text proposals

app/app.go, app/encoding/encoding.go, app/encoding/index_wrapper_decoder.go, cmd/celestia-appd/cmd/root.go, go.mod, go.sum, test/util/testnode/read.go
Closes https://github.com/celestiaorg/celestia-app/issues/1620
Closes https://github.com/celestiaorg/celestia-app/issues/1665
1. After this change, querying for an ordinary token transfer transaction still works.
2. Before this change, querying for a tx that includes a MsgPayForBlobs would result in an error. After this change, it returns the transaction:
```shell
$ ./build/celestia-appd query tx ACF2D0D2B4F1EAAEF01AFC3F3EA72FB4CE3B2AB45F02C39BB868D58A1964A35F --home $DIR
code: 0
codespace: ""
data: 122A0A282F63656C65737469612E626C6F622E76312E4D7367506179466F72426C6F6273526573706F6E7365
events:
- attributes:
- index: true
key: c3BlbmRlcg==
value: Y2VsZXN0aWExbmpnNXdtbDc1MnJreGQ3ZzgzemtjZWx4aGduZTdnNmFheHJtZGU=
- index: true
key: YW1vdW50
value: MTAwMHV0aWE=
type: coin_spent
- attributes: …
```
=> fix: override TxDecoder

pkg/shares/share_builder_test.go, pkg/shares/shares_test.go
I have made some changes to the code in this pull request. The main change is that I have renamed the variable `len` to `length`. This is because `len` is a built-in function in Go, and using it as a variable name can cause confusion and potential issues down the line. It is best practice to use a different name, and `length` is a clear and descriptive alternative.
=> Refactor variable name from len to length

go.mod, go.sum, testutil/common.go, x/qgb/abci_test.go, x/qgb/keeper/keeper_attestation.go, x/qgb/keeper/keeper_data_commitment.go, x/qgb/keeper/keeper_data_commitment_test.go, x/qgb/keeper/keeper_valset.go, x/qgb/keeper/keeper_valset_test.go, x/qgb/keeper/query_attestation.go, x/qgb/types/errors.go
cherry picks 3 relevant qgb changes from main, along with 3 from core (using the `v1.15.1-tm-v0.34.23-BSR-hardfork` tag)
=> chore: cherry-pick qgb changes for BSR update

x/blob/types/params.go
The issue is causing a lint error because it is using a redundant `if` statement to check for an error and then returning the error immediately after. This can be simplified by just returning the error directly, without checking for it using an `if` statement.
This issue is a part of a #1671
=> Redundant if-check in Validate function.

scripts/build-run-single-node.sh, scripts/single-node.sh
While debugging PFB txs, I found it helpful to enable tx indexing for the local node that gets run via the scripts in `./scripts`. Totally optional PR.
=> chore: enable tx indexing on dev scripts

x/qgb/abci_test.go, x/qgb/keeper/keeper_data_commitment.go
Implements the update logic for data commitment creation. Because, this is changing the state between the two versions and if a validator starts syncing from genesis (even using the new version), it will end up failing.
Thus, we need to implement the same mechanism we did for the `threshold` so that new binaries are able to sync from genesis.
More information in: https://github.com/celestiaorg/celestia-app/issues/1676#issuecomment-1532231143
Note: this will result in missing a block between the updates. But it's okey for BSR. However, we have an issue to update the data commitment creation to support changes in the window:  https://github.com/celestiaorg/celestia-app/issues/1685
=> feat: implement the update logic for data commitment creation

.github/workflows/docker-build-publish-common.yml
https://github.com/rollkit/local-celestia-devnet/pull/28#discussion_r1184006249 and https://github.com/rollkit/local-celestia-devnet/pull/28#issuecomment-1534182285
Cherry pick [7380eec](https://github.com/celestiaorg/celestia-app/commit/7380eec5e1e49a9ce697c950b72d1cfc03f39ab9) to the `v0.13.x` release branch. I will cut `v0.13.1` after this merges.
=> fix: cherry-pick common Docker CI to `v0.13.x`

.github/workflows/docker-build-publish-common.yml
Fixes https://github.com/celestiaorg/celestia-app/actions/runs/4883675301/workflow
I will cut v0.13.2 after this merges
=> fix: Docker publish permissions

.github/workflows/lint.yml, .github/workflows/test.yml, Makefile, README.md, go.mod, pkg/shares/parse_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/1691
=> chore: upgrade to Go 1.20

x/qgb/abci_test.go, x/qgb/keeper/keeper_data_commitment.go
This PR allows creating the data commitments correctly when the data commitments window changes. This change can be via an upgrade or a gov proposal. 
Closes https://github.com/celestiaorg/celestia-app/issues/1685
=> feat!: correctly creating the data commitments when the window is changed

x/paramfilter/test/param_filter_test.go, x/paramfilter/types.go
- updated err message to 
``` go
var ErrBlockedParameter = sdkerrors.Register(ModuleName, baseErrorCode, "parameter can not be modified")
```
- closes #1705
=> chore: improve error message for blocked params

Makefile
#360 introduced a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) incorrectly. The shebang is only used for executable files (from the Wikipedia link above, emphasis mine):
> When a text file with a shebang is used **as if it is an executable** in a Unix-like operating system, the program loader mechanism parses the rest of the file's initial line as an interpreter directive.
Makefiles aren't self-executable, rather they're inputs to the `make` command.
=> Remove shebang from Makefile.

docs/architecture/adr-011-optimistic-blob-size-independent-inclusion-proofs-and-pfb-fraud-proofs.md
Closes https://github.com/celestiaorg/celestia-app/issues/1724
=> docs: clarify proofs in ADR 11

test/cmd/txsim/cli_test.go
The tx sim tests use the baseapp which is full of data races. Thus, we need to skip running these tests in short mode, so that they're not run when we execute `make test-race`.
=> test: skip tx sim tests in short mode to avoid data races

go.mod, go.sum
bumps core to latest patch version: https://github.com/celestiaorg/celestia-core/releases/tag/v1.21.1-tm-v0.34.27
=> chore: bump core to v1.21.1-tm-v0.34.27

x/qgb/keeper/keeper_attestation.go
Closes https://github.com/celestiaorg/celestia-app/issues/1805
The latest attestation nonce and earliest attestation nonce are values written to store. In order to get them, we use the `getLatestAttestationNonce` and the `getEarliestAvailableAttestationNonce` methods. 
These methods panic if these values don't exist in store. However, the only time these values don't exist in store, if no manual changes were done to the store, is during the period between chain startup and block 1. 
So, we have the `CheckLatestAttestationNonce` method that checks if the value exists in store and returns true if so. And we use it in `abci.EndBlocker` and in queries not to return a stack trace, but a relevant error when querying during the period between chain startup and block 1.
Thus, the only change we …
=> docs: update the nonces docs in QGB store

x/qgb/types/attestation.go
Residual attestation type that is no longer needed/used
=> chore!: remove residual QGB attestation type

app/test/square_size_test.go, pkg/square/square_test.go, test/util/testnode/full_node_test.go, x/blob/client/testutil/integration_test.go
As per our call, this PR adds a _flaky suffix to flaky tests identified so far.
=> chore: adds _flaky suffix to flaky tests

.golangci.yml, x/blob/keeper/params.go, x/blob/types/builder.go, x/mint/keeper/keeper.go, x/qgb/client/verify.go, x/qgb/keeper/keeper.go, x/qgb/types/validator.go
Motivation https://github.com/celestiaorg/celestia-app/pull/1770#discussion_r1194307225. 
Today I learned that a linter exists to ban [naked returns](https://go.dev/tour/basics/7).
=> chore: ban naked returns

go.mod, go.sum
=> chore(deps): bump core version to v1.21.2-tm-v0.34.27

pkg/appconsts/global_consts.go, x/blob/types/errors.go, x/blob/types/payforblob.go, x/blob/types/payforblob_test.go
Noticed this while I was writing the block validity rules. This was still failing as expected since the commitment is check, but now we're being more explicit.
=> chore: explicitly reject share commitments that are not == hash len

.github/workflows/docker-build-publish.yml
We have the same building bumps for node https://github.com/celestiaorg/celestia-node/pull/2330
QGB orchestrator already contains the latest version of the common docker build pipeline 
https://github.com/celestiaorg/orchestrator-relayer/blob/main/.github/workflows/docker-build-publish.yml
=> chore: update common docker ci pipeline

x/blob/client/cli/query.go, x/blob/module.go
There is no need to pass a parameter for the query command and it's not used anywhere
IMPORTANT:
PRs should be left in Draft until the below checklist is completed.
-->
=> chore: remove unnecessary method param

test/util/testnode/genesis_options.go
That function is not changing anything related to the data commitment window, so I guess the comment was just copied by mistake
=> chore: remove unnecessary comment

x/qgb/keeper/keeper_attestation.go
We were using the wrong key when checking if the `EarliestAvailableAttestationNonce` exists in store
=> fix: use the right key for `EarliestAvailableAttestationNonce` check method

app/test/integration_test.go
minor refactor of one of our integration tests to use `testnode` instead of the cosmos-sdk's version.
part of #832
=> refactor: use testnode instead of cosmos-sdk version

pkg/inclusion/paths.go, pkg/shares/non_interactive_defaults.go, pkg/shares/non_interactive_defaults_test.go, pkg/square/builder.go
`NextShareIndex` also returns a boolean "fitsInRow" value which isn't used anywhere in the logic anymore. This PR cleans up the function by removing it. Note that this breaks the Go API
=> chore!: remove unused fitsInRow return value

app/ante.go, app/app.go
Non state-breaking change that improves the efficiency of relayers by gating redundant transactions at the mempool layer.
This also extracts out the ante handler into its own file for readability
=> feat: introduce ibc redundant relay decorator

app/process_proposal.go, app/test/process_proposal_test.go, test/util/direct_tx_gen.go, x/blob/types/blob_tx.go, x/qgb/types/query.pb.go
Closes: https://github.com/celestiaorg/celestia-app/issues/1973
=> fix!: signature validity checks in ProcessProposal

x/blob/ante/ante.go
Closes: https://github.com/celestiaorg/celestia-app/issues/1971
Yes, I'm aware that there's a lot of redundancy in the checks across the different stages in committing and executing a block. My plan is to start at a point of restrictiveness and then slowly remove redundancy rather than add more restrictiveness (which would be breaking)
=> feat!: run min gas pfb decorator in process proposal

app/ante.go, app/app.go, app/prepare_proposal.go, app/process_proposal.go, app/test/integration_test.go, app/test/prepare_proposal_test.go, app/test/process_proposal_test.go, app/validate_txs.go, test/util/direct_tx_gen.go, test/util/testnode/node_interaction_api.go, x/blob/ante/ante.go, x/blob/ante/ante_test.go, x/blob/keeper/keeper.go, x/blob/types/blob_tx.go, x/blob/types/errors.go, x/blob/types/payforblob.go, x/blob/types/payforblob_test.go
This PR backports the following commits in preparation for rc5
- db3e6584 feat!: run min gas pfb decorator in process proposal (#1985)
- 43b933ee fix!: implement full antehandler checks (#1984)
- c7281149 feat: implement MinGasPFBDecorator (#1936)
- d34f88e0 feat: introduce ibc redundant relay decorator (#1934)
- 639d6243 feat: use panics and recovery appropriately (#1948)
- cd212def fix!: signature validity checks in ProcessProposal (#1981)
- a27d2520 fix!: add namespace version check in pfbs (#1983)
Ideally we should MERGE COMMIT and not SQUASH COMMIT so we can preserve the commit history
=> chore: backport fixes into v1.x for rc5

pkg/inclusion/paths.go, pkg/shares/blob_share_commitment_rules.go, pkg/shares/blob_share_commitment_rules_test.go, pkg/square/builder.go
This PR pulls out a lot of redundant logic, simplifying the `NextShareIndex` function to make it more readable and understandable. I've also added more comments and updated the links.
Rationale: There is no subtreeWidth value that is not a multiple of the square size given that both must be powers of 2 and that the subtreewidth can't be greater than the minimum blob square size (and the blob has to fit in the square). This reinforces the notion that this algorithm is square size independent
=> chore: simplify next share index

app/test/integration_test.go, app/test/qgb_rpc_test.go, app/test/square_size_test.go, app/test/std_sdk_test.go, test/cmd/txsim/cli_test.go, test/txsim/run_test.go, test/util/testnode/config.go, test/util/testnode/full_node.go, test/util/testnode/full_node_test.go, test/util/testnode/node_interaction_api.go, x/mint/test/mint_test.go, x/qgb/client/verify.go, x/upgrade/test/integration_test.go
This refactor is mainly targeting #1990, but doing so in a way that uses common patters to avoid continuing to blow up the api
closes #1990
=> chore!: refactor testnode to expose appcreator

scripts/test_cover.sh
this pr enables us to add multiple directories to the exclusion list for measuring test coverage, and then adds the malicious package to that list
=> feat: add multiple excluded directories to the test coverage script

.golangci.yml, app/test/integration_test.go, app/test/process_proposal_test.go, app/validate_txs.go, pkg/shares/share_sequence_test.go, pkg/shares/split_compact_shares_test.go, pkg/square/builder_test.go, pkg/square/square_test.go, pkg/wrapper/nmt_wrapper_test.go, test/txsim/run.go, test/txsim/send.go, test/txsim/sequence.go, test/util/blobfactory/payforblob_factory.go, test/util/blobfactory/test_util.go, test/util/testnode/config.go, test/util/testnode/node_interaction_api.go, x/blob/client/testutil/integration_test.go, x/blob/types/blob_tx_test.go, x/blob/types/builder.go, x/blob/types/payforblob.go, x/blob/types/test/blob_tx_test.go, x/mint/keeper/genesis.go, x/qgb/client/query.go, x/qgb/types/genesis.go
Closes https://github.com/celestiaorg/celestia-app/issues/1989
=> chore: enable stylecheck

app/prepare_proposal.go, app/process_proposal.go, app/test/fuzz_abci_test.go, app/test/prepare_proposal_test.go, app/test/process_proposal_test.go, go.mod, go.sum, pkg/shares/parse_sparse_shares_test.go, test/util/testfactory/blob.go
consistently pass the correct chain-id to the application using `RequestPrepareProposal` and `RequestProcessProposal`
this PR still needs to update the go.mod to use the official tag of tendermint after its released
closes #2020 and #2021
=> fix!: use correct chain-id when filtering and checking txs

app/prepare_proposal.go, app/process_proposal.go, app/test/fuzz_abci_test.go, app/test/prepare_proposal_test.go, app/test/process_proposal_test.go, go.mod, go.sum, pkg/shares/parse_sparse_shares_test.go, test/util/testfactory/blob.go
backports the latest fix for rc7
=> chore!: backport for rc7

Makefile
Our test seem to be running longer than expected
=> test: add 30m timeout to CI tests

app/test/fuzz_abci_test.go
Closes: https://github.com/celestiaorg/celestia-app/issues/2055
=> test: fix flaky TestPrepareProposalConsistency

test/util/testnode/full_node.go
Closes https://github.com/celestiaorg/celestia-app/issues/2026
Now the testnode uses the configured chain-id and relies on the default to set the initial random value instead of overwriting it with a random value.
=> fix: stop overwriting chain-id in testnode

x/blob/types/payforblob.go
The function name no longer contains the word "heights"
=> docs: remove outdated TODO

scripts/build-run-single-node.sh, scripts/single-node.sh
While debugging https://github.com/celestiaorg/celestia-app/issues/2098 I frequently applied this patch to previous releases. Since these scripts exist for development purposes, I think it would save devs time by always enabling the API.
=> chore: always enable API in local dev scripts

go.mod, go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/2098
=> chore: upgrade to cosmos-sdk v1.16.1-sdk-v0.46.13

x/blob/types/payforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/2110
=> refactor: calculate namespace before loop

Dockerfile, Makefile
Mainly add ledger flag to add ledger support by default.
fixes #1658
=> fix(Makefile)!: add ledger build flag to build with ledger support by default

x/mint/test/mint_test.go, x/mint/types/constants.go, x/mint/types/minter_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2120
On a 32-bit system, an int can store values up to 2,147,483,647, which is much smaller than 31,556,952,000,000,000 (number of nanoseconds in a year).
After this merges I will cherry-pick it to the `v1.x` release branch
=> fix: explicit int64 for NanosecondsPerYear

x/mint/types/constants.go
Closes https://github.com/celestiaorg/celestia-app/issues/2129
https://github.com/celestiaorg/celestia-app/pull/2121 didn't actually fix the issue because the expression 
```go
NanosecondsPerYear = int64(NanosecondsPerSecond * SecondsPerYear)
```
was multiplying two `int`s together prior to the cast to `int64`. Since the product of those two `int`s overflows an `int32`, the value would overflow prior to the cast.
The fix proposed in this PR converts SecondsPerYear to an `int64`. Now the expression multiplies an `int` and `int64` so the product is an `int64` which won't overflow. 
I added this to the Makefile
```go
build-arm: mod
@cd ./cmd/celestia-appd
@mkdir -p build/
@GOOS=linux GOARCH=arm go build $(BUILD_FLAGS) -o build/ ./cmd/celestia-appd
@go mod tidy -compat=1.20
.PHONY: build-arm …
```
=> fix: int overflow for 32 bit machines

test/txsim/blob.go, test/txsim/sequence.go, x/blob/ante/ante.go, x/blob/keeper/keeper.go, x/blob/types/payforblob.go
This also simplifies some of the gas consumption logic between the ante handler and blob keeper
=> fix: txsim uses the same gas estimation method

specs/src/specs/namespace.md
Upon reviewing the namespace module, it came to my attention that namespaces below the [maximum reserved namespace ](https://github.com/celestiaorg/celestia-app/blob/5615205760ac3921506e2c457fc2deb924f8aed5/pkg/namespace/consts.go#L56)are being treated as reserved (see [IsReserved](https://github.com/celestiaorg/celestia-app/blob/2b74a9d970618de76f82d385f46f176452c12bb3/pkg/namespace/namespace.go#L133)), regardless of their current usage. Therefore, this pull request aims to revise the specifications to accurately reflect this fact. It is important to note that the list of reserved namespaces extends beyond what is included in the table and encompasses namespaces below the maximum reserved namespace.
=> doc: clarifies the exact range of reserved namespaces

pkg/namespace/namespace.go, pkg/namespace/namespace_test.go
=> chore: fixes mutability of the Repeat output

pkg/namespace/namespace.go, pkg/namespace/namespace_test.go
A unit test for `leftPad` was missing, which is added in this PR.
=> test: adds missing unittest for leftPad

app/app.go, app/errors/errors.go, app/errors/errors_test.go, test/txsim/blob.go, test/txsim/sequence.go, x/blob/ante/ante.go, x/blob/keeper/keeper.go, x/blob/types/payforblob.go
=> feat: backport features to allow node to handle gas price estimation

docs/architecture/adr-021-restricted-block-size.md
Fix a small issue in ADR-021. I don't think these lines meant to use `MaxBytes` b/c there is a separate field `MaxBlockSizeBytes` that acts as an upper bound for `MaxBytes`.
=> doc: fix incorrect usage of `MaxBytes`

test/util/malicious/app_test.go
the testnode is still hitting the race detector #1369, so we aren't running those integration tests with the race detector
=> fix: stop running the malicious integration test during short mode

test/util/testnode/rpc_client.go
This was missed in https://github.com/celestiaorg/celestia-app/pull/2122 since app construction is different in tests than via the binary
=> fix: enable node grpc service in tests

cmd/celestia-appd/cmd/root.go, test/util/testnode/full_node.go, x/upgrade/test/integration_test.go
This is merely a bandaid fix over a much larger problem which is the incongruence with how nodes are constructed and run. 
Previously options set in the app config weren't being passed to the constructor. This PR fixes it
=> fix: pass all the app config arguments to the app constructor

pkg/shares/padding.go, pkg/shares/share_builder.go, pkg/shares/share_builder_test.go, pkg/shares/split_compact_shares.go, pkg/shares/split_sparse_shares.go
Closes https://github.com/celestiaorg/celestia-app/issues/2157
A separate `Init()` function seems kinda like an anti pattern. If it must always be called after `NewBuilder`, why doesn't `NewBuilder` call it? @mojtaba-esk
=> refactor!: remove builder return param from init

docs/architecture/adr-021-restricted-block-size.md
=> docs: clarify that `MaxSquareSize` is a versioned constant

specs/src/specs/namespace.md
Adding a new line before the list so that the linter doesn't complain.
=> chore(docs): lists should be surrounded by blank lines in md

pkg/proof/proof_test.go, pkg/proof/querier.go
Fixes the range to support end exclusive share ranges
=> fix: end exclusive parse namespace end share range

Makefile
=> chore: backport version string to fallback to the sha256 commit

specs/src/README.md, specs/src/SUMMARY.md, specs/src/specs/cat_pool.md, specs/src/specs/index.md
Given that it is only the specification of celestia-app that is published it makes more sense to include it there rather than in the directory of the cat pool itself
=> chore: copy across cat pool spec from celestia-core

test/txsim/account.go
this is a quick bug fix that rounds up when calculating fees in txsim. Without doing this, the fees used are too low by a single utia
=> fix: round up when calculating fee in txsim

specs/src/specs/cat_pool.md
=> chore: fixes linter issues by adjusting heading levels in cat_pool.md 

app/app.go, app/test/square_size_test.go, pkg/appconsts/global_consts.go, test/txsim/account.go, test/txsim/send.go, test/txsim/stake.go, test/util/blobfactory/payforblob_factory.go, test/util/blobfactory/test_util.go
This moves BondDemon to the appconsts package. This is a commonly used constant especially for clients submitting messages. They shouldn't need to import the entire app package just to use this constant. By doing this we also remove a duplicate bondDenom that was created to avoid import cycles
=> chore: move BondDenom to appconsts

x/blob/types/payforblob.go, x/blob/types/payforblob_test.go
Very minor cleanup of an unnecessary field
=> chore: remove duplicate ShareSize constant

pkg/namespace/consts.go, pkg/namespace/namespace.go, pkg/namespace/namespace_test.go, pkg/shares/padding.go, pkg/shares/padding_test.go, pkg/shares/parse_test.go, pkg/shares/share_sequence_test.go, pkg/shares/shares.go, specs/src/specs/namespace.md, specs/src/specs/shares.md
Closes https://github.com/celestiaorg/celestia-app/issues/2253
=> feat!: reserve the last 256 namespaces for protocol use

x/upgrade/test/integration_test.go
This fixes the flakiness of the upgrade test sometimes perceived in CI and also locally.
The CI might fail if https://github.com/celestiaorg/celestia-app/pull/2251 is still not merged.
=> fix: TestLegacyGovUpgradeFailure flakiness

Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/2276
Note: doesn't need to be backported to v1.x because v1.x skips tests via `-short`
https://github.com/celestiaorg/celestia-app/blob/53b5dbf2438a085ded2952a0250829213eb77f55/Makefile#L114-L118
=> test: skip TestMaxTotalBlobSizeSuite during test-race

app/test/std_sdk_test.go, go.mod, go.sum, test/e2e/setup.go, test/tokenfilter/setup.go, test/util/common.go, test/util/testnode/node_init.go, x/qgb/abci_test.go, x/qgb/keeper/keeper.go, x/qgb/keeper/keeper_valset.go, x/qgb/keeper/keeper_valset_test.go, x/qgb/types/query.pb.go, x/qgb/types/validator.go
Bumps to the latest version of the SDK. Note that this deactivates the use of the EVM address. To fulfill that functionality we will need to reintroduce a mapping in https://github.com/celestiaorg/celestia-app/pull/2169
=> chore!: bump sdk fork to v1.17.0

app/prepare_proposal.go
Following a question raised by @cmwaters in this [comment](https://github.com/celestiaorg/celestia-app/pull/2233#discussion_r1289992252), I have opted to eliminate the logged information pertaining to the number of transactions in the mempool at height 1.
=> chore: removes the log info related to the number of txs in mempool when preparing the first block

app/test/square_size_test.go, test/cmd/txsim/cli.go, test/e2e/simple_test.go, test/txsim/account.go, test/txsim/run.go, test/txsim/run_test.go
This PR adds the ability to specify a specific account to use as master for txsim. This is useful for when we don't want to always use the account with the most funds in our wallet.
closes #2286
kinda sorta blocking #2197
=> feat: add the ability to specifiy the txsim master account

pkg/genesis/vesting_accounts.go
closes #2295 
more context in the issue.
A short summary: To install a vesting account in the genesis file, allocate the desired amount to `OriginalVestingBalance` and the banking module. For instance, to lock a `total_allocation` and unlock `1TIA`, follow these steps:
Set `account.OriginalVestingBalance = total_allocation`.
Set `account.BalanceInBankModule = total_allocation + 1TIA`.
However, to avoid donating extra funds, a new approach is adopted: unlock `1TIA` from the vested amount. This is achieved by subtracting `1TIA` from the `OriginalVestingBalance`:
Update `account.OriginalVestingBalance = total_allocation - 1TIA`.
Keep `account.BalanceInBankModule = total_allocation`.
This achieves the same goal without additional donations.
=> fix: InitUnlockedBalance unlocked from the vesting balance

scripts/build-run-single-node.sh, scripts/single-node.sh
(cherry picked from commit 64be04f9e643793113d1effeb9afaba207abcda9)
Closes https://github.com/celestiaorg/celestia-app/issues/2328
Cherry picks a missing fix.
=> fix: register the EVM address correctly in scripts

pkg/appconsts/v2/app_consts.go, pkg/appconsts/versioned_consts.go
Adds v2 package. For now this is just the same as v1 but might change in the future. 
We will need at least the version number for a versioned state machine
=> feat: add support for v2

x/blob/client/cli/payforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/2346
```
$ ./build/celestia-appd tx blob PayForBlobs --help
Pay for a data blob to be published to the Celestia blockchain. [hexNamespaceID] must be a 10 byte hex encoded namespace ID. [hexBlob] can be an arbitrary length hex encoded data blob. This command only supports a single blob per invocation.
```
=> fix: PayForBlobs help text for namespace ID

test/e2e/readme.md, test/e2e/simple_test.go
Our e2e tests were failing because we made a breaking change and didn't update thr RC. We should probably come up with a more clever way of working out the latest release and running that
=> fix: update e2e test

x/blob/client/cli/payforblob.go
Prefixing hex values with the `0x` prefix is a common convention. Nevertheless, the `blob` module CLI does not have the capability to parse the `0x` prefix. Hence, including this clarification in the command description can greatly assist users.
=> chore(blob): clarifies that hex values should not be 0x prefixed in the PayForBlobs subcommand

Makefile, app/test/priority_test.go, pkg/user/tx_options.go
adds a simple integration test for tx priority in the mempool
closes #513 #2377
=> chore: add test for tx priority

cmd/celestia-appd/cmd/root.go
Closes https://github.com/celestiaorg/celestia-app/issues/2380
I synced a node to arabica-10. 
```
$ du -h ~/.celestia-app/data
7.8M	/Users/rootulp/.celestia-app/data/state.db
11M	/Users/rootulp/.celestia-app/data/blockstore.db
```
Stop the node then run compaction. Note: I had to run this from the CELESTIA_APP home directory in order for the compaction output to overwrite the existing `data/state.db`.
```shell
$ cd ~/.celestia-app
$ celestia-appd experimental-compact-goleveldb
I[2023-08-31|14:24:39.819] starting compaction...                       db=data/blockstore.db
I[2023-08-31|14:24:39.828] starting compaction...                       db=data/state.db
```
```shell
6.3M	/Users/rootulp/.celestia-app/data/state.db
11M	/Users/rootulp/.celestia-app/data/blockstore.db
```
Start the node …
=> feat(cli): add experimental-compact-goleveldb

x/blob/client/cli/payforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/1600 
Closes https://github.com/celestiaorg/celestia-app/issues/2388
Closes https://github.com/celestiaorg/celestia-app/issues/2392 
Sorry for bundling so many logical changes in one PR. 
- Accept `0x` prefixed arguments
- Improve error message if namespaceID is not 10 bytes
- Improve error message if no arguments are provided
- Mark `--from` as a required flag
- Add an example command
- Add an alias for `PayForBlob`
- Improve help message
- Remove `[]` brackets around required arguments
- Describe default for `--share-version`
- Describe default for `--namespace-version`
```
$ celestia-appd tx blob PayForBlobs --help
Pay for a data blob to be published to Celestia.
namespaceID is the user-specifiable portion of a version 0 …
```
=> feat: improve PayForBlobs CLI

README.md
There is a typo in this environment variable name. The correct spelling is: https://github.com/celestiaorg/celestia-app/blob/8b0decb6e9a4c7aa426192344f6d91f7bb729c08/app/app.go#L181
=> docs: fix typo in environment variable name

Makefile
Small formatting fix for the `lint` command having an extra column. 
See screen shot.
=> Makefile: fix formatting error on help printout

.github/workflows/ci-release.yml, .goreleaser.yaml, Makefile, README.md
**UPDATE**
This PR adds building binaries to the release process by using [goreleaser](https://goreleaser.com/).
The CI release process is largely unchanged. Releases can be trigger by either manually triggering the `ci_release` workflow, or they can be triggered by pushing a version tag. 
I know the team has not been using the CI to generate releases, so I added a `make goreleaser-release` command to build the linux distro binaries for the release locally so that they can be manually uploaded. 
Result of running `make goreleaser-release`:
```
tree build 
build
└── goreleaser
├── CHANGELOG.md
├── artifacts.json
├── celestia-app_Linux_x86_64.tar.gz
├── celestia-app_linux_amd64_v1
│   └── celestia-appd
├── checksums.txt
├── config.yaml
└── metadata.json
```
Since we are just building for …
=> build: Goreleaser

app/test/square_size_test.go
in what appears to be an effort to make the tests more stable, I think we accidently changed the square size test to not work as intended. This PR fixes this by requiring the expected square size to actually get hit.
closes #2034
=> fix: check for equal expected size in square size test

x/mint/types/constants.go
Addresses finding 004 of binary builders preliminary audit report. 
I don't think it's necessary to rename the variable to `MinimumTargetInflationRate` but can do if reviewers feel strongly that renaming is preferred over this comment.
=> docs(x/mint): explain `TargetInflationRate`

x/mint/abci_test.go, x/mint/types/constants.go, x/mint/types/minter.go, x/mint/types/minter_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2501
=> refactor(x/mint): initialize inflation decimals once

Makefile, app/prepare_proposal.go, app/test/fuzz_abci_test.go, app/test/prepare_proposal_context_test.go, app/test/prepare_proposal_test.go, app/test/process_proposal_test.go, go.mod, go.sum
I'm not sure if this fixes all of #2454, but it at least fixes one bug similar to it.
The fix in this PR allows for the antehandlers that are ran during prepare proposal to have access to a time close to the actual block time. It does this by simply adding `time.Now` to the header used for antehandler state access.
=> fix: add time to the sdk.Context used in PrepareProposal

app/prepare_proposal.go, app/test/fuzz_abci_test.go, app/validate_txs.go, test/util/malicious/out_of_order_prepare.go
This PR adds loggers back to the filter functions (but actually uses them this time), and logs when transaction get filtered during `PrepareProposal`. It also re-adds an obtuse gas limit to the transactions in the `TestPrepareProposalConsistency` test, where those errors were getting caught by the filter functions. 
part of #2517
=> chore: log filtered transactions and fix gas limits in tests

Makefile
The makefile target is already depending on `mod` before building the binary. Thus, we can remove the extra go mod tidy
=> chore: remove unnecessary go mod tidy

.github/workflows/ci-release.yml, .github/workflows/lint.yml, .github/workflows/nightly.yml, .github/workflows/test.yml, README.md, go.mod
Bump Go version to 1.21.1 because QGB repo can't depend on celestia-app due to:
```
go: module github.com/celestiaorg/quantum-gravity-bridge/v2@v2.1.1 requires go >= 1.21.1; switching to go1.21.1
```
=> chore(deps): Bump go version to 1.21.1

go.mod, go.sum, x/qgb/client/verify.go, x/qgb/types/abi_consts.go, x/qgb/types/valset.go
Removes the `+incompatible` suffix from QGB dependency
=> chore(deps): Bump QGB contracts version to v2

.github/markdown-link-check-config.json, .github/workflows/lint.yml, .github/workflows/markdown-linter.yml
… to ignore false positive link check failures
forks the .github markdown linter so that we can use our own config to ignore false positive link checks. front ported from v1.x
=> refactor: fork the markdown linter from .github and use our own config

.github/workflows/lint.yml
Support go v1.21.
Will fix CI for: https://github.com/celestiaorg/celestia-app/pull/2540
=> chore(deps): bump golang-ci version to support go 1.21

app/prepare_proposal.go, app/process_proposal.go, app/validate_txs.go
Closes: https://github.com/celestiaorg/celestia-app/issues/2517
This PR adds metrics to track:
- The amount of times process proposal recovers from a panic
- The amount of invalid transactions that get filtered in prepare proposal
- The time it takes for prepare proposal and process proposal to execute
=> feat: add metrics to prepare and process proposal

app/ante/ante.go, app/ante/panic.go, app/ante/panic_test.go
Closes: #2557
This will allow us to understand when a panic happens, which transaction caused it.
As an example here is a mock panic:
```
mock panic
caused by transaction:
*types.MsgSend{from_address:"celestia15v4r83er48zfrm7u6uuqs3lytwxc63c34ltdgn" to_address:"celestia1t5m2f2m000twkmsgaa777rty36wd254292am6c" amount:<denom:"utia" amount:"10" > }
```
=> feat: add decorator to wrap panic messages with the transaction that caused them

go.mod, go.sum
bumps core to the latest release. as a side note, we should compare bandwidth with and without the latest change to the v1 mempool.
=> chore: bump celestia-core to v1.28.0-tm-v0.34.29

cmd/celestia-appd/cmd/root.go
This is something that wasn't backported as part of #2188
Note that this changes the default indexer to `null` which is still up to discussion here: https://github.com/celestiaorg/celestia-app/issues/2322
=> chore: use the DefaultConsensusConfig() for initializing a node

app/app.go, app/ibc_proposal_handler.go, x/upgrade/test/integration_test.go
The proposal handler to upgrade IBC also invokes the standard `ScheduleUpgrade` within the upgrading module. See https://github.com/cosmos/ibc-go/blob/e2201aaf1b016356bbd40fcdc17988437adce5ae/modules/core/02-client/keeper/proposal.go#L82. This effectively means that one can create a governance proposal to upgrade the chain which is something we didn't want to support. As there is no need to handle updating the IBC client yet, this temporarily disables the proposal type.
=> feat!: disable ibc upgrade proposal handler

go.mod, go.sum
ref: https://github.com/celestiaorg/celestia-app/issues/2579
=> deps: bump ics23 from v0.9.0 to v0.9.1

app/default_overrides.go, cmd/celestia-appd/cmd/root.go
After merging https://github.com/celestiaorg/celestia-core/pull/1088, it makes sense to add a default time based TTL to the mempool. This PR reduced the block TTL to 5 (instead of 10) and the time to 5 * 15 seconds = 75 seconds
=> feat: add a default ttl to the mempool config

x/qgb/types/codec.go
This PR adds the QGB to the proto registry (noe this is different to the router)
=> fix: register qgb msg server in codec

docs/architecture/adr-008-square-size-independent-message-commitments.md
fixes the markdown linter failure (will update if there more)
=> chore: use a permalink for rollkit ADR

go.mod, go.sum
bumps core to the latest release
=> chore: bump celestia-core to v1.29.0-tm-v0.34.29

.github/workflows/codeql.yml
Currently, the auto builder doesn't support go version 1.21.1, and it expects the binary to be built using `make` instead of `make build`. This PR installs the right version of go manually and builds the binary.
=> fix: build manually the app binary for codeql

.github/workflows/ci-release.yml
Closes https://github.com/celestiaorg/celestia-app/issues/2452
Tested on my fork
```
/opt/hostedtoolcache/goreleaser-action/1.21.2/x64/goreleaser check
• checking                                 path=
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
Ref: https://github.com/rootulp/celestia-app/actions/runs/6473546638/job/17576484916?pr=39#step:3:16
=> ci: check if goreleaser config is valid

.github/workflows/lint-pull-request.yml
Closes https://github.com/celestiaorg/celestia-app/issues/1539 by validating that PR titles have a conventional commit prefix
1. https://github.com/rootulp/celestia-app/pull/42
2. https://github.com/rootulp/celestia-app/pull/43
=> ci: PRs titles must have a conventional commit prefix

docs/architecture/adr-014-versioned-namespaces.md
Closes https://github.com/celestiaorg/celestia-app/issues/2641
After this PR, there are no references to specs-staging
=> docs: remove reference to specs-staging

README.md, scripts/signing/verify-signature.sh
Closes https://github.com/celestiaorg/celestia-app/issues/2664
On a Digital Ocean droplet that has no keys,
```
root@rootulp-quicksync:~# ./verify-signature.sh checksums.txt.sig checksums.txt
Downloading the celestia-app-maintainers public key...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   689  100   689    0     0   6270      0 --:--:-- --:--:-- --:--:--  6321
Importing celestia-app-maintainers.asc
gpg: key D469F859693DC3FA: public key "celestia-app-maintainers <celestia-app-maintainers@celestia.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Deleting celestia-app-maintainers.asc
Verifying the signature of checksums.txt.sig with checksums.txt
gpg: Signature made Tue Oct 10 …
```
=> fix: download celestia-app-maintainers key in verify signature script

.github/workflows/protobuf.yml, Makefile
Still thinking about whether we should enable this on `main`
=> ci: introduce proto breakage detector

app/default_overrides.go
The default mempool size should match that of the default TTL and block size.
=> chore: update deafult mempool size to match ttl and block size

app/app.go, app/default_overrides.go, app/default_overrides_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2716
```bash
./scripts/single-node.sh
cat ~/.celestia-app/config/genesis.json
```
```genesis.json
"distribution": {
"params": {
"community_tax": "0.020000000000000000",
"base_proposer_reward": "0.010000000000000000",
"bonus_proposer_reward": "0.040000000000000000",
"withdraw_addr_enabled": true
},
```
```genesis.json
"distribution": {
"params": {
"community_tax": "0.020000000000000000",
"base_proposer_reward": "0.000000000000000000",
"bonus_proposer_reward": "0.000000000000000000",
"withdraw_addr_enabled": true
},
```
=> fix: override proposer rewards to 0%

Dockerfile, docker/Dockerfile_txsim
This PR fixes the mismatch of architectures in build stages
Same can happen in app like it happened for node
Ref: 
- https://github.com/celestiaorg/celestia-node/pull/2862
- https://github.com/celestiaorg/devops/issues/527
=> chore: fix multiplatform builds

test/util/malicious/tree.go
Reported by @vgonkivs who is working on a BEFP test and needs to pass `nmt.NodeVisitor()` in to the malicious package's tree.
=> fix(malicious): use constructor NMT options

.github/workflows/protobuf.yml, Makefile
This ports over #2671 to `main
=> ci: introduce proto breakage detector (#2671)

tools/blocktime/readme.md, x/blob/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/2762
`make markdown-link-check` passes locally
=> docs: fix broken links to docs.celestia.org

docs/architecture/adr-015-namespace-id-size.md, specs/src/specs/cat_pool.md
"Compatibility" is misspelt in a few places
=> docs: fix spelling of compatibility

app/default_overrides.go
sets the default to discard abci responses
closes #
=> chore: discard abci responses by default

app/default_overrides.go, app/default_overrides_test.go, scripts/single-node.sh
Closes https://github.com/celestiaorg/celestia-app/issues/2758
```
./scripts/single-node.sh
cat ~/.celestia-app/config/app.toml
```
Verified that 
```toml
[api]
enable = false
```
```toml
[grpc]
enable = false
```
```toml
[grpc-web]
enable = false
```
=> chore: disable API, GRPC, and GRPC web by default

.github/workflows/ci-release.yml
Forward ports https://github.com/celestiaorg/celestia-app/pull/2751 to main
FYI: may introduce merge conflicts with https://github.com/celestiaorg/celestia-app/pull/2772 cc: @MSevey
=> ci: remove markdown-linter as prerequisite to version bump

.github/workflows/ci-release.yml
Minor update I saw when debugging the CI. This will ensure that the goreleaser step won't run if the goreleaser check fails. This will just clean up the error log a little bit.
=> ci: add goreleaser-check as a require step for the goreleaser build

pkg/da/data_availability_header.go, pkg/inclusion/blob_share_commitment_rules.go, pkg/inclusion/blob_share_commitment_rules_test.go, pkg/inclusion/commitment.go, pkg/inclusion/commitment_test.go, pkg/inclusion/paths.go, pkg/square/builder.go, pkg/square/square.go, test/util/malicious/out_of_order_builder.go, x/blob/types/blob_tx.go, x/blob/types/blob_tx_test.go, x/blob/types/payforblob.go, x/blob/types/payforblob_test.go
We currently have code relating to creating and proving commitment across the inclusion, x/blob/types, and shares package. This api breaking refactor moves all of the commitment code to the inclusion package. 
The reasoning behind this is that it will eventually allow for users to import commitment creation and proving code while not having to import the blob module, tendermint, or the sdk. 
The reasoning behind keeping it in the inclusion instead of shares is that entire reason for making a commitment is to prove inclusion. So the name seems to fit better.
The reasoning behind note keeping it in the blob package was that it was difficult to not have an import cycle since this logic requires the share splitting logic for blobs.
=> refactor!: move all blob share commitment code to the inclusion package

.github/workflows/ci-release.yml
The weird tag names was due to not providing the `release_branches` param.
Proof: https://github.com/MSevey/celestia-app/tags
Closes #2688
=> ci: add release_branches to version_bump to fix tag names

cmd/celestia-appd/cmd/addrbook.go
Closes https://github.com/celestiaorg/celestia-app/issues/2784
Part of https://github.com/celestiaorg/networks/issues/513
=> feat(addrbook): skip peers with errors

test/ledger/ledger_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2225
Note: this test won't fail when Goreleaser creates binaries that break Ledger support. However, this may catch when we bump a dependency that breaks Ledger support.
=> test: Ledger support

cmd/celestia-appd/cmd/download-genesis.go, cmd/celestia-appd/cmd/root.go
Closes https://github.com/celestiaorg/celestia-app/issues/2777
Note for reviewers: I'd rather not backport this PR to v1.x b/c it's a new feature and not a bug fix. I wanted to have it ready in case ppl do want it on v1.x
Works for all 3 known networks. Complains on an unknown network
```shell
$ ./build/celestia-appd download-genesis mocha-4
Downloading genesis file for mocha-4 to /Users/rootulp/.celestia-app/config/genesis.json
Downloaded genesis file for mocha-4 to /Users/rootulp/.celestia-app/config/genesis.json
SHA-256 hash verified for mocha-4
$ ./build/celestia-appd download-genesis celestia
Downloading genesis file for celestia to /Users/rootulp/.celestia-app/config/genesis.json
Downloaded genesis file for celestia to /Users/rootulp/.celestia-app/config/genesis.json
SHA-256 hash …
```
=> feat: `download-genesis` command

x/blobstream/types/validator.go
Closes https://github.com/celestiaorg/celestia-app/issues/2800
=> chore: remove unnecessary abs operation from power diff

cmd/celestia-appd/cmd/addrbook.go, cmd/celestia-appd/cmd/root.go
Backports https://github.com/celestiaorg/celestia-app/pull/2623 and https://github.com/celestiaorg/celestia-app/pull/2783
```
$ ./build/celestia-appd addrbook ~/git/rootulp/celestia/networks/celestia/peers.txt ~/Downloads/addrbook.json
Error adding b751ffe713e3e5d80e8f45c3bd5e640ee9a91cb9@10.129.127.95:26656: Cannot add non-routable address b751ffe713e3e5d80e8f45c3bd5e640ee9a91cb9@10.129.127.95:26656
Converted /Users/rootulp/git/rootulp/celestia/networks/celestia/peers.txt into /Users/rootulp/Downloads/addrbook.json
$ head -n 10  /Users/rootulp/Downloads/addrbook.json
{
"key": "8957397890a66cd0f716cbc9",
"addrs": [
{
"addr": {
"id": "a41b4bc451b1b71d537aa1018226e08d7fa7e44e",
"ip": "5.255.77.44",
"port": 26656
},
"src": {
```
=> feat: backport addrbook command (backport #2623 and #2783)

x/blobstream/abci.go
Closes: [#2765](https://github.com/celestiaorg/celestia-app/issues/2765)
- Call `CheckEarliestAvailableAttestationNonce ` to check if Nonce is available
- Use `GetEarliestAvailableAttestationNonce ` to fetch the nonce use in [`newEarliestAvailableNonce`](https://github.com/celestiaorg/celestia-app/blob/2335d2b7d8d9463abc85f79b430926380dd41001/x/qgb/abci.go#L161) and logging in [here](https://github.com/celestiaorg/celestia-app/blob/2335d2b7d8d9463abc85f79b430926380dd41001/x/qgb/abci.go#L183) and [here](https://github.com/celestiaorg/celestia-app/blob/2335d2b7d8d9463abc85f79b430926380dd41001/x/qgb/abci.go#L189)
=> refactor(x/blobstream): remove unnecessary code

x/blob/keeper/keeper.go, x/blob/keeper/keeper_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2781
Note this _shouldn't_ be consensus breaking b/c the ABCI response results hash shouldn't depend on events. [`deterministicResponseDeliverTx`](https://github.com/celestiaorg/celestia-core/blob/ffdb652634fb1b6b6426c0f1a2c5adec8af80253/types/results.go#L45-L55) filters events from the response. Thanks @cmwaters for identifying.
I tested on a Robusta devnet named app-v130-node-v0110. See https://github.com/celestiaorg/celestia-app/pull/2794#issuecomment-1787411696 and https://github.com/celestiaorg/celestia-app/pull/2794#issuecomment-1788888796
=> fix: address serialization in PayForBlobs event 

x/blob/keeper/keeper.go, x/blob/keeper/keeper_test.go
Backports #2793 to the v1.x branch
=> fix: address serialization in PayForBlobs event (backport #2793)

app/default_overrides_test.go
I wanted to see what value we use for `MaxTxsBytes`. Since it's computed and not hard-coded, I wrote a test to see it and verify we don't accidentally revert it.
=> test: mempool overrides

cmd/celestia-appd/cmd/root.go
Closes https://github.com/celestiaorg/celestia-app/issues/2824
I verified the snapshots command was added
```shell
$ ./build/celestia-appd snapshots
Manage local snapshots
Usage:
celestia-appd snapshots [command]
Available Commands:
delete      Delete a local snapshot
dump        Dump the snapshot as portable archive format
export      Export app state to snapshot store
list        List local snapshots
load        Load a snapshot archive file (.tar.gz) into snapshot store
restore     Restore app state from local snapshot
Flags:
-h, --help   help for snapshots
```
=> feat(cmd): snapshots command

test/txsim/run.go
I have seen a few CI tests fail because although the context stops the process, it isn't correctly parsed causing the program that called the txsim to think that there was another error and not the context Canceled or DeadlineExceeded errors
=> fix: handle context cancellations in txsim

x/blob/module.go, x/blobstream/module.go
This PR fixes #2837. 
Both `blob` and `blobstream` modules lack registration for the gRPC Gateway routes, leading to the inability to query endpoints. Let me know if there is anything i need to do to merge this PR.
CI checks require 3 workflows awaiting approval.
=> fix: register gRPC Gateway routes

scripts/protocgen.sh
Closes https://github.com/celestiaorg/celestia-app/issues/744
This import hack doesn't seem necessary b/c it doesn't actually modify `x/blobstream/types/query.pb.go`
```
$ rm x/blobstream/types/query.pb.go
$ make proto-gen
```
and then observe that there is no `git diff` so no changes to the already checked in `x/blobstream/types/query.pb.go` and the generated one.
Also proto-gen passes in CI: https://github.com/celestiaorg/celestia-app/actions/runs/6881660922/job/18718509598?pr=2846
=> chore: remove import hack for protobuf any

README.md
The lint and test badges reference older GH workflows.
=> docs: remove unused badges

.coderabbit.yaml
Based on [Slack thread](https://celestia-team.slack.com/archives/C02PFFCGMNW/p1700507951358399). 
Consider re-enabling if CodeRabbit modifies this feature so that the high level summary gets included in a comment on the PR rather than modifying the original PR description.
=> ci: disable CodeRabbit high level summary

.github/workflows/lint.yml, README.md
Bump to the latest release of golangci-lint. Ref: https://github.com/golangci/golangci-lint/releases/tag/v1.55.2
I was experiencing a memory issue while running an older version of golangci-lint locally (v1.49.0) but bumping to latest resolved. This is a manual bump b/c it looks like Dependabot doesn't bump this version for us.
=> chore(deps): Bump golangci-lint to v1.55.2

proto/celestia/upgrade/v1/tx.proto, x/upgrade/keeper.go, x/upgrade/module.go, x/upgrade/tally_test.go, x/upgrade/types/msgs.go, x/upgrade/types/tx.pb.go, x/upgrade/types/tx.pb.gw.go
Addresses: #2877
Introduces a crank message for tallying all the signal messages
=> feat!: introduce MsgTryUpgrade

pkg/user/signer_test.go
Part of https://github.com/celestiaorg/celestia-app/issues/1944
Note: we don't strictly need to merge this. I opted to write a test for the existing behavior so that we have a straight-forward way to verify the behavior change after we implement gas refunds.
=> test: TestGasConsumption

go.mod
Closes https://github.com/celestiaorg/celestia-app/issues/2891
It looks like `go mod tidy` got confused by our go.mod containing four require blocks. I removed three of the `require()` statements so that all the dependencies were in one block and then `go mod tidy` was able to split them into two distinct blocks:
1. direct deps
2. indirect deps
No dependency versions should've changed. This is purely a visual convenience. 
Ref: https://stackoverflow.com/questions/69432877/why-there-are-two-require-blocks-in-go-mod-since-go-1-17
=> chore: distinct require blocks for direct vs indirect deps

pkg/appconsts/versioned_consts_test.go
During a 1:1 w/ @evan-forbes , we noticed that the versioned constant getters don't have any unit tests.
=> test: versioned constant getters

pkg/appconsts/global_consts.go, pkg/wrapper/nmt_wrapper_test.go
minor typo fix, two of them are variable, rest are comments 
have a good week-end
=> chore(pkg): typo fix

pkg/user/signer.go
very last forgotten typo from #2926 
the repo should now be typo free, quite the feat!
=> chore(pkg/user): fix typo

x/upgrade/types/codec.go, x/upgrade/types/msgs.go
Closes https://github.com/celestiaorg/celestia-app/issues/2876
I was able to sign a signal tx with a Ledger
```
$ celestia-appd tx upgrade signal 1 --from $LEDGER --ledger --fees 420utia --yes
Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: '[]'
timestamp: ""
tx: null
txhash: B512CED67CEF2EF951DEA71C231E583EEE7340BB28EA39ADFF0771EC21AA25B2
```
Ideally we have an automated test for this
=> feat(upgrade): register legacy amino json

pkg/user/tx_options.go
As was the case with the txsim, converting to int64 can occasionally truncate the value meaning that the tx has actually a lower gas price
=> feat: SetGasLimitAndFee should round up

.github/workflows/ci-release.yml, .github/workflows/goreleaser.yml
Closes https://github.com/celestiaorg/celestia-app/issues/2884 
- Remove the version_bump and branch_name jobs
- Extract the goreleaser jobs to a new file
Can still create a release. See https://github.com/rootulp/celestia-app/actions/runs/7324051789/job/19947265102
=> ci: remove version_bump job

specs/src/specs/resource_pricing.md
Addresses #2966 by using the governance modifiable params tests in PR #2973.
All four of the params are modifiable by governance, which matches the specs in [params.md](https://github.com/celestiaorg/celestia-app/blob/main/specs/src/specs/params.md).
=> docs: add column for governance modifiable params in resource_pricing

.golangci.yml, app/default_overrides.go, app/default_overrides_test.go, pkg/proof/proof.go, pkg/shares/info_byte.go, pkg/shares/shares.go, pkg/square/square_test.go, test/txsim/account.go, x/mint/test/mint_test.go, x/mint/types/constants.go, x/upgrade/types/msgs.go
Use linter to detect unnecessary type conversions
https://github.com/mdempsky/unconvert
=> chore: remove unnecessary conversions

x/blobstream/client/tx.go, x/upgrade/cli/tx.go
The `ValidateBasic` function has been called in the `GenerateOrBroadcastTxWithFactory` function, so we no longer need to add the `ValidateBasic` function when writing Cli. Related PRs can be viewed at: https://github.com/cosmos/cosmos-sdk/pull/9236#discussion_r623803504
=> refactor: remove ValidateBasic in cli

cmd/celestia-appd/cmd/download_genesis.go
Closes https://github.com/celestiaorg/celestia-app/issues/2976
Updated the help and error messages to include arabica-11
```
$ ./build/celestia-appd download-genesis --help
Download genesis file from https://github.com/celestiaorg/networks.
The first argument should be a known chain-id. Ex. celestia, mocha-4, arabica-10, arabica-11
$ ./build/celestia-appd download-genesis arabaica-12
Error: unknown chain-id: arabaica-12. Must be: celestia, mocha-4, arabica-10, arabica-11
```
Downloading arabica-11 genesis works
```
$ ./build/celestia-appd download-genesis arabica-11
Downloading genesis file for arabica-11 to /Users/rootulp/.celestia-app/config/genesis.json
Downloaded genesis file for arabica-11 to /Users/rootulp/.celestia-app/config/genesis.json
SHA-256 hash verified for arabica-11
```
=> feat: add support for arabica-11 in download-genesis command

x/blob/client/cli/payforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/2901
The previous commands still work b/c they are aliases:
```
$ ./build/celestia-appd tx blob pay-for-blob
Error: pay-for-blob requires two arguments: namespaceID and blob
$ ./build/celestia-appd tx blob pay-for-blobs
Error: pay-for-blob requires two arguments: namespaceID and blob
$ ./build/celestia-appd tx blob PayForBlob
Error: pay-for-blob requires two arguments: namespaceID and blob
$ ./build/celestia-appd tx blob PayForBlobs
Error: pay-for-blob requires two arguments: namespaceID and blob
```
=> feat: kebab-case pay-for-blob command

x/blob/client/cli/payforblob.go
Closes https://github.com/celestiaorg/celestia-app/issues/2990
```shell
$ ./build/celestia-appd tx blob PayForBlob --help
Pay for data blob(s) to be published to Celestia.
To publish a single blob, specify the namespaceID and blob via CLI arguments.
To publish multiple blobs, use the --input-file flag with the path to a JSON file.
The JSON should look like:
{
"Blobs": [
{
"namespaceID": "0x00010203040506070809",
"blob": "0x48656c6c6f2c20576f726c6421"
},
{
"namespaceID": "0x00010203040506070809",
"blob": "0x48656c6c6f2c20576f726c6421"
}
]
}
The namespaceID is the user-specifiable portion of a version 0 namespace.
The namespaceID must be a hex encoded string of 10 bytes.
The blob must be a hex encoded string of non-zero length.
Usage:
celestia-appd tx blob PayForBlobs [namespaceID blob] …
```
=> fix: CLI help for PayForBlob

pkg/user/signer.go
As this is likely to be valuable to clients who want more manual control of signing
=> feat: make the signers keyring public

pkg/user/signer.go, pkg/user/signer_test.go
This PR using a `Ticker` for periodically call `GetTx` by given hash instead of a `Timer`. This makes the code clean and avoids calling reset `Timer` multiple times.
It's similar to `WaitMined` in [geth](https://github.com/ethereum/go-ethereum/blob/09e0208029ff96a9cda0c69dbaebfd3f31a39771/accounts/abi/bind/util.go#L32).
Other changes:
* Add lock when get `pollTime`
=> refactor: Imporve signer confirm tx

Makefile, go.mod, go.sum, go.work.sum, test/testground/go.mod, test/testground/go.sum
updates core to revert the breaking config change. we'll get the config change when we update comet to something other than that based on v0.34. backporting manually since this is guaranteed to have conflicts thanks to the change in go mod
=> chore: update core to revert breaking config change

pkg/user/signer.go
It's probably misleading that `GetSequence` should not only return the sequence number but increment it. The incrementing sequence should be internal and the user should just be able to use `Sequence` if they wish to query the sequence number of the signer
=> feat: expose sequence number correctly to users of the signer

Makefile, go.work.sum
Closes https://github.com/celestiaorg/celestia-app/issues/3018
Will fix CI too because CI just calls `make govulncheck`. I kinda like that pattern b/c then we don't have to keep two versions in sync (one in Makefile and one in CI workflow file)
=> chore(deps): pin to govulncheck v1.0.1

specs/src/specs/namespace.md
I was linking to specs and noticed that the Protobuf section was empty. We don't have a Protobuf definition for namespace but we do have a Go definition.
Ref: https://github.com/celestiaorg/celestia-app/blob/34c98b96fee6e5aaf0ce9cb7b0ec03ee47f24774/pkg/namespace/namespace.go#L8-L11
=> docs: add namespace Go definition to specs

app/ante/fee_checker.go, app/ante/min_fee_test.go, go.work.sum, pkg/appconsts/initial_consts.go, pkg/appconsts/v2/app_consts.go, pkg/appconsts/versioned_consts.go
moving GlobalMinGasPrice constant under v2
Fixes - #3035
=> chore: move v2 consts to v2 directory

docs/architecture/adr-012-sequence-length-encoding.md, docs/architecture/adr-015-namespace-id-size.md, specs/src/specs/public_key_cryptography.md
Closes https://github.com/celestiaorg/celestia-app/issues/3043 by ignoring links that actually work but sometimes fail in CI when markdown-link-check is run.
`make markdown-link-check` passes locally
=> chore: ignore links that fail markdown-link-check

app/address.go, app/app.go, app/denom.go, app/init.go, app/init_test.go
A small refactor to extract some of the contents of `app.go`. Motivated by a separate PR that tried to modify app.go which is currently at 700+ line file with very little consistency.
=> refactor: extract init and denom from app.go

test/util/genesis/document.go
Overview:
This PR addresses a spelling error in variable names.
The variable names contained a spelling mistake, and this PR corrects that mistake.
=> chore: The variable name has a typo

app/app.go
Refactor to remove two temporary variables `scopedIBCKeeper` and `scopedTransferKeeper`.
=> refactor: inline scoped keepers

app/square_size.go, go.work.sum
=> fix: PrepareProposal always passes v0 to GovSquareSizeUpperBound

go.work.sum, pkg/inclusion/nmt_caching.go
Closes https://github.com/celestiaorg/celestia-app/issues/3070
There are no instances of counter in `nmt_caching.go`. `paths.go` has a counter field but that doesn't seem immediately relevant to where these comments are so proposal to remove them.
=> docs: remove comments about "counter" in NMT cacher

Dockerfile
This PR exposes the port 26660 which is needed to support metrics which we want access to for knuu and testground
=> chore: expose prometheus port in dockerfile

Makefile
This adds two commands in the makefile to make it easy to build and publish the last commit to the ghcr.io registry. This is convenient with the e2e tests which depend on a published commit to run off. 
If you want to use this you need to setup a personal access token with github and login to docker with ghcr else you won't have the requisite permissions
=> chore: allow locally publishing docker images to ghcr

Makefile, test/e2e/readme.md, test/e2e/simple_test.go, test/e2e/upgrade_test.go
A previous PR added the ability to manually build and publish docker images (which are needed to run e2e tests).
This PR adds documentation to explain how to do it.
It also removes the environment variable `E2E` which is redundant and can be replaced by `KNUU_NAMESPACE` which is required
=> chore: describe manual usage and remove unneccesary env var

scripts/build-run-single-node.sh, scripts/single-node.sh
I think we no longer expect validators to register EVM addresses so this PR removes a command from the scripts in `scripts/`.
cc: @rach-id
=> chore: stop registering EVM address in scripts

app/square_size.go, pkg/appconsts/versioned_consts.go, x/blob/README.md
Closes https://github.com/celestiaorg/celestia-app/issues/2241
We may consider renaming `GovSquareSizeUpperBound` => `MaxEffectiveSquareSize` in a future PR but that's API breaking.
=> docs: improve docs for max square size

.github/workflows/codeql.yml, .github/workflows/goreleaser.yml, .github/workflows/govulncheck.yml, .github/workflows/lint.yml, .github/workflows/nightly.yml, .github/workflows/test.yml
This should make it slightly easier to bump Go versions in the future because there will be fewer places to update. 
Thanks for the tip @ramin! See https://github.com/celestiaorg/celestia-core/pull/1242/files#r1511342490
=> ci: use Go version from go.mod

app/prepare_proposal.go, app/process_proposal.go, app/square_size.go, test/util/malicious/out_of_order_prepare.go
Motivation: the previous name `GovSquareSizeUpperBound` was easy to mix up with two other related but distinct constants:
- `SquareSizeUpperBound`
- `GovMaxSquareSize`
The new name is a bit easier to visually differentiate from those two. This is technically API breaking but celestia-node doesn't use this method.
=> refactor!: rename to MaxEffectiveSquareSize

app/module/module.go, app/module/module_test.go, go.work.sum
Closes: #3171
I've also added a sanity check on startup that runs through all the upgrades and asserts that the versions increment accordingly
=> fix: use consensus versions of the module when performing migrations

test/e2e/readme.md, test/e2e/simple_test.go
When I attempted to run e2e tests from the root directory of celestia-app, the `simple_test` failed due to an unrecognized version of the application: `unrecognized version: 91603c49c`. However, this version seems to be available at [https://github.com/celestiaorg/celestia-app/pkgs/container/celestia-app/191141043?tag=91603c4](https://github.com/celestiaorg/celestia-app/pkgs/container/celestia-app/191141043?tag=91603c4). See the details below:
```
KNUU_NAMESPACE=test E2E_LATEST_VERSION="$(git rev-parse --short main)" E2E_VERSIONS="$(git tag -l)" go test ./test/e2e/... -timeout 30m -v
=== RUN   TestE2ESimple
simple_test.go:41: unrecognized version: 91603c49c
--- FAIL: TestE2ESimple (0.00s)
=== RUN   TestMinorVersionCompatibility
upgrade_test.go:37: skipping e2e test: no versions to test …
```
=> fix: fixes e2e test failure by adjusting commit hash length in version recognition

README.md
Markdown link check has failed on the most recent two commits on main because the link to golangci-lint was broken
=> chore: fix golangci-lint link

Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/3178
```
$ make help
Choose a command run in celestia-app:
help                   Get more info on make commands.
build                  Build the celestia-appd binary into the ./build directory.
install                Build and install the celestia-appd binary into the $GOPATH/bin directory.
mod                    Update all go.mod files.
mod-verify             Verify dependencies have expected content.
proto-gen              Generate protobuf files. Requires docker.
proto-lint             Lint protobuf files. Requires docker.
proto-check-breaking   Check if there are any breaking change to protobuf definitions.
proto-format           Format protobuf files. Requires Docker.
build-docker           Build the celestia-appd docker …
```
=> fix: make help format

test/e2e/node.go, test/e2e/simple_test.go, test/e2e/testnet.go, test/e2e/upgrade_test.go
This PR:
a) deactivates the compatibility test as this is currently not working (see https://github.com/celestiaorg/celestia-app/issues/3187)
b) Fixes TestMajorUpgradeToV2 which is now working as expected 🎉 
c) Stops all nodes if they are running before destroying them (which stopped us from cleaning up resources after being finished with them)
=> chore: fix upgrade test and ensure nodes stop correctly

.github/workflows/lint.yml, README.md, app/module/migrations_test.go, app/test/process_proposal_test.go, cmd/celestia-appd/cmd/addrbook.go, test/cmd/txsim/cli.go, x/blob/ante/ante_test.go, x/blob/client/cli/query_params.go, x/blob/types/payforblob.go, x/blob/types/payforblob_test.go, x/blobstream/client/query_test.go, x/mint/client/cli/query.go, x/upgrade/cli/tx.go
Closes https://github.com/celestiaorg/celestia-app/issues/3195
idk which golangci-lint release fixed the issue in https://github.com/celestiaorg/celestia-app/issues/3195 but CI passes on this PR 🤷‍♂️
=> chore: upgrade to golangci-lint v1.57.0

docs/architecture/adr-022-multi-versioned-state-machine.md, specs/src/specs/namespace.md, test/testground/README.md
This PR addresses several Markdown linting issues found in the main branch.
=> chore: resolves markdown linting issues in main branch

.github/workflows/markdown-linter.yml, .markdownlint.yaml, README.md, docs/architecture/adr-013-non-interactive-default-rules-for-zero-padding.md, docs/architecture/adr-015-namespace-id-size.md, docs/architecture/adr-019-strict-inflation-schedule.md
Maybe closes https://github.com/celestiaorg/celestia-app/issues/2212
https://github.com/celestiaorg/celestia-app/pull/3198#issuecomment-2010437900
=> chore: upgrade to markdownlint v0.39.0

scripts/single-node.sh
Closes https://github.com/celestiaorg/celestia-app/issues/3205
```shell
./scripts/single-node.sh
celestia-app home: /Users/rootulp/.celestia-app
celestia-app version: 1.0.0-rc0-588-g952a455b
Are you sure you want to delete: /Users/rootulp/.celestia-app? [y/n] y
Deleting /Users/rootulp/.celestia-app...
Initializing validator and node config files...
Adding a new key to the keyring...
Adding genesis account...
Creating a genesis tx...
Collecting genesis txs...
Starting celestia-app...
// no error
```
=> fix: provide a fee in single node script

Dockerfile, docker/Dockerfile_txsim
This should be a non-breaking change.
This only changes the work directory when the container is started. This means that if you want to execute a command in a running container, it will be automatically in that directory instead of '/'. This improves maintaining and debugging our environments.
=> feat: add workdir to dockerfile

README.md
https://github.com/celestiaorg/celestia-app/commit/e3e11e28ac5fbcc49563cfd633317ddf55617c70 contained an extra line in the audits table that should not exist. It currently looks like this:
=> chore: fix audit table

.github/workflows/lint.yml, app/test/process_proposal_test.go, cmd/celestia-appd/cmd/addrbook.go, test/cmd/txsim/cli.go, test/e2e/cmd/e2e/main.go, x/blob/ante/ante_test.go, x/blob/client/cli/payforblob.go, x/blob/client/cli/query_params.go, x/blob/types/payforblob.go, x/blob/types/payforblob_test.go, x/mint/client/cli/query.go, x/qgb/client/query_test.go
Motivated by https://github.com/celestiaorg/celestia-app/pull/3213#pullrequestreview-1963491079
=> chore: upgrade to golangci-lint v1.57.1

tools/blocktime/readme.md
Closes https://github.com/celestiaorg/celestia-app/issues/3228
```
make markdown-link-check
```
passes locally
=> fix: consensus full node link

app/prepare_proposal.go, app/test/prepare_proposal_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/2271
=> revert: last block height == 0 check

.github/workflows/create_release_tracking_epic.yml
I created a reusable workflow to help with tracking release deployments to testnets and mainnet. 
This action calls the reusable workflow that creates an issue in the devops repo and notifies the devops team on slack.
=> feat(ci): use release tracking workflow to notify devops

proto/celestia/upgrade/v1/query.proto, proto/celestia/upgrade/v1/tx.proto, specs/src/specs/params.md, x/upgrade/README.md, x/upgrade/cli/cli_test.go, x/upgrade/cli/query.go, x/upgrade/cli/tx.go, x/upgrade/ibc.go, x/upgrade/keeper.go, x/upgrade/legacy_test.go, x/upgrade/module.go, x/upgrade/tally_test.go, x/upgrade/types/codec.go, x/upgrade/types/msgs.go, x/upgrade/types/query.pb.go, x/upgrade/types/tx.pb.go
Closes https://github.com/celestiaorg/celestia-app/issues/3223
x/upgrade README format inspired by https://docs.cosmos.network/v0.50/build/spec/SPEC_MODULE
1. Can we move some of the unit tests from tally_test.go to keeper_test.go?
2. Why does ResetTally only delete versions less than the current version? Why not delete all versions in the map?
=> docs: improve `x/upgrade` docs

test/e2e/node.go
This PR implements a correction to utilize the disk space amount specified in the resources for genesis nodes, instead of the default `1Gi`.
=> fix: uses the specified volume amount for the genesis nodes

scripts/single-node.sh
I had to do this for an IBC test and an external engineer who is using this script also has to do this b/c they are querying block results. The relevant config:
```
#######################################################
#######################################################
[storage]
discard_abci_responses = true
```
Note: this may increase disk space usage but this script is used for dev purposes and every run deletes the previous run's `data/` directory so I'm not concerned about it.
=> chore(scripts): persist ABCI responses for single-node.sh

test/cmd/txsim/cli.go
Closes #3311
No changes to the implementation are necessary to support a range for the number of blobs in txsim CLI; the description of the `--blob-amounts` flag is merely underspecified. I tested the CLI, and it can indeed accept a range, such as `--blob-amounts 1-10`.
=> chore: improves description of --blob-amounts flag in txsim CLI

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
We basically never use the checkboxes on issues so they're just visual noise. Proposal to delete them from the issue templates.
=> chore: remove checkboxes from issue templates

go.mod, go.sum
Upgrade to ibc-go [v6.3.0](https://github.com/cosmos/ibc-go/releases/tag/v6.3.0) on the v1.x branch.
=> chore(deps): upgrade to ibc-go v6.3.0

specs/src/specs/state_machine_modules.md
The markdown linter keeps failing for a broken link in CIs, and this PR fixes the issue.
=> chore: updates the upgrade module link to the signal module

cmd/celestia-appd/cmd/addr_converter.go, cmd/celestia-appd/cmd/addr_converter_test.go, cmd/celestia-appd/cmd/root.go
This is an adoption of #3249 with feedback addressed and authorship preserved.
```shell
$ ./build/celestia-appd addr-conversion --help
Reads a celestia1xxx or celestiavaloper1xxx address and converts it to the other type.
Usage:
celestia-appd addr-conversion [celestia address] [flags]
Examples:
celestia-appd addr-conversion celestia1grvklux2yjsln7ztk6slv538396qatckqhs86z
celestia-appd addr-conversion celestiavaloper1grvklux2yjsln7ztk6slv538396qatck9gj7vy
$ celestia-appd addr-conversion celestia1grvklux2yjsln7ztk6slv538396qatckqhs86z
celestiavaloper1grvklux2yjsln7ztk6slv538396qatck9gj7vy
$ celestia-appd addr-conversion celestiavaloper1grvklux2yjsln7ztk6slv538396qatck9gj7vy
celestia1grvklux2yjsln7ztk6slv538396qatckqhs86z
```
=> feat(cli): addr-conversion

docker/README.md
This PR updates the example txsim Docker command by removing the deprecated `-r ` flag, which was previously used to specify the RPC endpoint.
=> chore(txsim): removes deprecated `-r` flag from txsim docker README

Dockerfile, docker/Dockerfile_txsim
The port `:26661` needs to be exposed in order to access traced data. Please see https://github.com/celestiaorg/celestia-core/tree/main/pkg/trace#pull-based-event-collection. 
Part of #3318
=> feat: updates docker file by exposing the tracing port 26661

app/test/priority_test.go
Fixes this warning
Ref: https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/loopclosure
Note: since we're already on Go 1.22, the loop already creates a new variable per loop iteration so we don't technically need to merge this but idk how to inform the warning generator that we're already on Go 1.22 and the warning doesn't apply to us.
=> chore: resolve loopclosure warning

proto/celestia/core/v1/da/data_availability_header.pb.go, test/txsim/account.go, test/util/genesis/accounts.go
If you don't need to format the string, it is recommended to use error.New()
=> chore: use errors.New to replace fmt.Errorf with no parameters

scripts/single-node.sh
Given that we're using `set -o errexit` in the `single-node.sh` script, and we're setting the variable `CELESTIA_APP_VERSION=$(celestia-appd version 2>&1)`, if `celestia-appd` is not in the path, the execution will return nothing and just exist, and users can be confused why the script is not doing anything. This PR adds a check whether the celestia-appd binary is in the PATH and is executable, and returns an error otherwise to help users.
=> feat: check if the celestia binary is installed in single-node.sh

pkg/user/signer.go, pkg/user/signer_test.go
Resolves https://github.com/celestiaorg/celestia-app/issues/3258
=> feat: introduce gas multiplier to increase gas limit

.github/workflows/create_release_tracking_epic.yml
`main` is on this version. the bump somehow was missed for v1 branch. 
patch fixes a variable name for the slack notification.
=> chore(deps): bump .github version for release tracking epic

.github/workflows/create_release_tracking_epic.yml
I realized that the `published` event is triggered by pre-releases too.
The `released` event is only triggered when we set the release to the latest release, which is what we want to track for deployments.
=> fix(ci): update from published to released trigger for deployment epic

app/app.go, app/modules.go
A few small refactors to `app.go`.
=> refactor(app): app.go

test/e2e/benchmark/throughput.go, test/e2e/benchmark/utils.go
While we can obtain traced data and use it to calculate block time, size, and throughput, this is merely an alternative approach. We can achieve the same results at the end of the test using Python scripts and without analyzing the traced data.
=> feat: adds functionality to read the blockchain headers into a csv file

go.mod, go.sum, test/interchain/go.mod, test/interchain/go.sum, test/testground/go.mod, test/testground/go.sum
Bumps Celestia-core version to [v1.36.0-tm-v0.34.29](https://github.com/celestiaorg/celestia-core/releases/tag/v1.36.0-tm-v0.34.29)
=> chore(deps): bump core version to v1.36.0-tm-v0.34.29

pkg/user/signer.go
This PR exports an existing function to block on submitting a PFB to the mempool, but not block on getting the tx included in a block.
=> feat: export BroadcastPayForBlob to support more async blob submission.

app/modules.go
Closes https://github.com/celestiaorg/celestia-app/issues/3464
=> fix: register blob store key in v2

test/e2e/check_upgrades.go, test/e2e/main.go
Closes https://github.com/celestiaorg/celestia-app/issues/3298
Relevant logs
```
$ make test-e2e MinorVersionCompatibility
test-e2e2024/05/09 15:47:37 Running minor version compatibility test versions v1.0.0	v1.1.0	v1.2.0	v1.3.0	v1.4.0	v1.5.0	v1.6.0	v1.7.0	v1.8.0	v1.9.0	v2.0.0-rc0
test-e2e2024/05/09 15:49:38 Starting testnet
test-e2e2024/05/09 15:50:53 Upgrading node node 2 version v1.0.0
test-e2e2024/05/09 15:51:16 Upgrading node node 3 version v1.2.0
test-e2e2024/05/09 15:51:34 Upgrading node node 4 version v2.0.0-rc0
test-e2e2024/05/09 15:52:05 Upgrading node node 2 version v1.3.0
test-e2e2024/05/09 15:52:32 Upgrading node node 3 version v1.5.0
test-e2e2024/05/09 15:53:03 Upgrading node node 4 version v1.2.0
test-e2e2024/05/09 15:53:29 Upgrading node node 2 version v1.8.0 …
```
=> test: extend minor version compat to test v2

x/blob/README.md
=> docs: correct command of binary file

pkg/proof/proof.go
Exports `NewShareInclusionProofFromEDS` so that I can use when generating the proofs in Celestia-node side.
=> chore: export NewShareInclusionProofFromEDS

go.mod, go.sum, scripts/single-node.sh, test/interchain/go.mod, test/interchain/go.sum, test/testground/go.mod, test/testground/go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/3378
I updated single-node.sh to use an upgrade height so that I could verify `celestia-appd status` reports:
Block height | App version
--- | ---
1 | 1
2 | 1
3 | 2
4 | 2
=> chore(deps): upgrade to celestia-core v1.36.1-tm-v0.34.29

app/ante/ante.go, x/blob/ante/blob_share_decorator.go, x/blob/ante/blob_share_decorator_test.go, x/blob/ante/max_total_blob_size_ante.go, x/blob/ante/max_total_blob_size_ante_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/3468 by reviving the max blob size decorator and making both decorators version aware so that:
- v1 uses max blob size decorator
- v2 uses max blob share decorator
=> chore: revive max blob size decorator

scripts/single-node.sh
This PR extends the single-node.sh script by providing an option for the user to enable local tracing and retrieve traced data.
**How to test**
1. Run `single-node.sh` under the `scripts` folder
2. Respond `y` to `Do you want to set up local tracing with the ability to pull traced data? [y/n]`
3. Once the node starts, navigate to ./celestia-app/data/traces folder and you will find the locally traced files.
Also, the trace package from celestia-core has a method to pull the traced data which can be found  [here](https://github.com/celestiaorg/celestia-core/blob/a281e871c70f4c8bd4f6ab7c7e39e28c715d65b2/pkg/trace/fileserver.go#L102).
=> chore: extends single-node.sh script to support local tracing and traced data retrieval

test/e2e/benchmark/benchmark.go, test/e2e/benchmark/manifest.go, test/e2e/benchmark/throughput.go, test/e2e/testnet/node.go, test/e2e/testnet/setup.go, test/e2e/testnet/testnet.go, test/e2e/testnet/txsimNode.go, test/e2e/testnet/util.go
Closes https://github.com/celestiaorg/celestia-app/issues/3318
It enables 1) local tracing in validators knuu instances 2) pushing locally traced data from validators to a S3 bucket, given that proper configs are passed via environment vars.
Additionally, it includes changes that:
- Allow specifying the number of blobs per sequence parameter for TX clients (previously fixed at `5`).
- Log information about the presence of Grafana environment variables.
The `E2EThroughput` has been tested and I confirm both local tracing and pushing traces work correctly in knuu instances. To run the test:
```
go run ./test/e2e/benchmark  -v
```
You will see the `consensus_round_state.jsonl` file added to the root directory of the project, indicating the local tracing is operational in the validators' knuu …
=> test: enables local tracing in e2e benchmark tests

x/signal/keeper.go, x/signal/module.go
Follow up to https://github.com/celestiaorg/celestia-app/pull/3290 which fixes a few comments that still say "upgrade" when they should say "signal".
=> docs(x/signal): replace upgrade with signal in comments

x/signal/keeper.go, x/signal/keeper_test.go, x/signal/types/errors.go
Closes https://github.com/celestiaorg/celestia-app/issues/3550
=> feat!: modify constraint for signal versions

.github/workflows/test-e2e.yml
Fixes #3506 
I tested it by triggering workflow on push to my working branch and breaking e2e tests. The notifications showed up in our slack channel.
=> chore: enable slack pings

x/minfee/grpc_query.go, x/minfee/grpc_query_test.go
=> fix: rename remaining instances of GlobalMinGasPrice to NetworkMinGasPrice 

test/e2e/benchmark/benchmark.go
Closes #3589
Remnant of #3505 
With the changes in this PR, the benchamrk test runs successfully.
=> fix: removes redundant attempts to start tx clients in the BenchmarkTest's Run method

pkg/user/tx_client.go
This ports a bug that was caught in `main` whereby setting either the default address or default account name in the tx client does not automatically set the other leading in a potential incoherence between the two
=> fix: usage of default address and account in tx client

test/e2e/testnet/test_helpers.go
=> chore!: deletes JSONRPCError from e2e test_helpers

test/e2e/benchmark/main.go, test/e2e/benchmark/throughput.go
Closes https://github.com/celestiaorg/celestia-app/issues/3617
Before this PR, you could run:
```
go run ./test/e2e/benchmark
test-e2e-benchmark2024/06/24 13:02:13 No particular test specified. Running all tests.
test-e2e-benchmark2024/06/24 13:02:13 go run ./test/e2e/benchmark <test_name> to run a specific test
test-e2e-benchmark2024/06/24 13:02:13 Valid tests are: TwoNodeSimple
```
and it would start running all the benchmark tests. However, after this PR, it will require user to specify the test name:
```
go run ./test/e2e/benchmark                       
test-e2e-benchmark2024/06/24 13:26:24 No test is specified.
test-e2e-benchmark2024/06/24 13:26:24 Usage: go run ./test/e2e/benchmark <test_name>
test-e2e-benchmark2024/06/24 13:26:24 Valid tests are: TwoNodeSimple
```
=> chore(e2e benchmark test): allows selection of only one test

Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/3587
```
$ make test-interchain
--> Running interchain tests
=== RUN   TestInterChainAccounts
setup.go:203: Pruned 3 volumes, reclaiming approximately 5.0 MB
...
```
=> fix: make test-interchain

app/app.go
Addreses https://github.com/celestiaorg/celestia-app/pull/3628#pullrequestreview-2145858746
```
12:15PM INF received complete proposal block hash=A207BD135CB14E3A8CB25CE771C53C7187362805FA1D2E2C42263414CFF96458 height=2 module=consensus
12:15PM INF finalizing commit of block hash={} height=2 module=consensus num_txs=0 root=BEF4F77ABB424877031B5BB1C8BE249CA83FB2FF23BD24D80BFFF3D31E3CB788
12:15PM INF minted coins from module account amount=35512129utia from=mint module=x/bank
12:15PM INF upgrading from app version 1 to 2
12:15PM INF executed block height=2 module=state num_invalid_txs=0 num_valid_txs=0
12:15PM INF adding a new module: interchainaccounts
12:15PM INF created new capability module=ibc name=ports/icahost
12:15PM INF port binded module=x/ibc/port port=icahost
12:15PM INF claimed …
```
=> feat: log upgraded to app version 2

go.mod, go.sum
Bump to the latest release of celestia-core
=> chore: bump celestia-core

app/errors/insufficient_gas_price_test.go, app/test/big_blob_test.go, app/test/fuzz_abci_test.go, app/test/priority_test.go, pkg/user/e2e_test.go, pkg/user/tx_client.go, pkg/user/tx_options.go, x/blob/types/estimate_gas_test.go
We had an instance of someone putting the fee as the second argument instead of the gas price. I realised having `SetFee` in the function signature is misleading so I'm proposing to change it
=> chore!: rename tx option for better clarity

test/e2e/benchmark/benchmark.go, test/e2e/benchmark/throughput.go
Closes https://github.com/celestiaorg/celestia-app/issues/3669
=> chore: improves code readability of e2e benchmark tests

Makefile
I was copying this command to celestia-stack-internal and noticed that it is missing a `PHONY`
=> chore(makefile): add PHONY for markdown-link-check

Makefile
I noticed a CI failure on another PR for test-race and I'm pretty sure testnode tests will fail in race mode b/c of an un-ivestigated issue.
=> chore: skip testnode test in race mode

.goreleaser.yaml
There is an issue with goreleaser where it will automatically mark release candidates as the latest release.
Motivated by https://github.com/celestiaorg/celestia-node/pull/3569
Thanks @ramin!
=> fix(goreleaser): do not mark rcs as latest release

pkg/proof/proof_test.go, pkg/proof/querier.go
The start share shouldn't be equal to the end share because the range is end-exclusive. This PR adds this check.
=> chore: add (start share == end share) check in parse namespace

test/e2e/testnet/testnet.go, test/util/genesis/genesis.go
Recent e2e tests failed with:
```
2024/07/18 17:22:08 Failed to setup testnet: converting accounts into sdk types: invalid account 4: name cannot be empty
```
because https://github.com/celestiaorg/celestia-app/pull/3690 merged. Since e2e tests aren't run as part of CI on each PR, I didn't learn about the failure until @ninabarbakadze pinged about it.
```
make test-e2e
```
gets past that error locally.
=> fix(test/e2e): name cannot be empty error

test/e2e/testnet/node.go
There were non-blocking lint suggestions shown on every run. This pr addresses those suggestions so we don't have to keep seeing the red lines.
=> fix: lint suggestions

go.mod, go.sum, test/interchain/go.mod, test/interchain/go.sum
Upgrade to https://github.com/celestiaorg/cosmos-sdk/releases/tag/v1.24.0-sdk-v0.46.16
=> chore(deps): upgrade to cosmos-sdk v1.24.0-sdk-v0.46.16

cmd/celestia-appd/cmd/root.go
Closes https://github.com/celestiaorg/celestia-app/issues/3716
```
$ celestia-appd
Usage:
celestia-appd [command]
Available Commands:
// ...
```
=> chore: remove "start celestia app" from CLI docs

pkg/proof/proof.go
Exposes that functionality so that we don't end up copy-pasting that code in Celestia-node.
=> refactor: expose CreateShareToRowRootProofs for downstream use

test/e2e/benchmark/benchmark.go, test/e2e/testnet/testnet.go
=> test: makes network latency effective at earlier heights in benchmark tests

cmd/celestia-appd/cmd/app_exporter.go, cmd/celestia-appd/cmd/app_server.go, cmd/celestia-appd/cmd/query.go, cmd/celestia-appd/cmd/root.go, cmd/celestia-appd/cmd/tx.go
While working on the prototype for multi-app, I was reading through `root.go` and realized it contained a lot of separate functionality. I split this up into multiple files where I deemed reasonable. Also renamed some imports and added comments where I thought necessary.
=> refactor(cmd): extract contents of root.go

README.md, specs/src/specs/namespace.md, tools/blocktime/readme.md
Fixes a few broken links. See [failing CI](https://github.com/celestiaorg/celestia-app/actions/runs/10354113554/job/28658603156).
`make markdown-link-check` passes locally
=> fix: markdown links

scripts/single-node.sh
celestia-node no longer accepts a chain ID of `private` but it does accept `test` instead.
```
2024-08-12T13:59:08.549-0400	ERROR	core	core/listener.go:183	listener: received block with unexpected chain ID: expected test, received private
```
This modifies the `single-node.sh` scripts so that it can be used in conjunction with a local celestia node.
=> fix(scripts): single-node.sh chain ID

.goreleaser.yaml
Closes https://github.com/celestiaorg/celestia-app/issues/3793 by resolving this [deprecation notice](https://goreleaser.com/deprecations/#snapshotname_template)
=> ci: fix goreleaser check deprecation warning

Makefile
I forgot to remove this Makefile target in https://github.com/celestiaorg/celestia-app/pull/3776
=> chore: remove make test-interchain

app/app.go, app/app_test.go, scripts/arabica.sh, scripts/mocha.sh
Closes https://github.com/celestiaorg/celestia-app/issues/3804 with a hacky approach that infers the app version based on the snapshot height and mounts KV stores accordingly.
Kinda related to https://github.com/celestiaorg/celestia-app/issues/3804 but we didn't hit this because we don't have tests that try to state sync so I created https://github.com/celestiaorg/celestia-app/issues/3807
Using both the `arabica.sh` and `mocha.sh` scripts in this PR, I can start state syncing. I let the Arabica node fully state sync to the tip of the chain and it worked.
=> fix: state sync on v2.x

app/app.go, app/app_test.go, scripts/arabica.sh, scripts/mocha.sh
Forward port of https://github.com/celestiaorg/celestia-app/pull/3808
=> fix: state sync on main

docs/maintainers/release-guide.md
Closes https://github.com/celestiaorg/celestia-app/issues/3521
=> docs: release guide

tools/blocketa/README.md, tools/blocketa/main.go
I used this tool to predict the arrival time of the v2 activation height on Mocha.
=> feat(tools): block ETA

.goreleaser.yaml, docs/maintainers/prebuilt-binaries.md
Prevents https://github.com/celestiaorg/celestia-app/issues/3819 from happening again. Also adds a document so other maintainers can generate + upload prebuilt binaries if they don't work again in the future.
The current `-rc*` [prerelease_suffix](https://goreleaser.com/customization/git/#git) was not working because goreleaser treated v2.1.2-rc1 as more recent than v2.1.2 in the [failing workflow](https://github.com/celestiaorg/celestia-app/actions/runs/10523365886/job/29157983992#step:6:68). This resolves by removing the `*`.
1. Worked on my fork: https://github.com/rootulp/celestia-app/releases/tag/v2.1.2
2. Worked on this repo: https://github.com/celestiaorg/celestia-app/releases/tag/v2.1.2
```
• git state …
```
=> ci(goreleaser): fix release candidate suffix

tools/blocketa/main.go, tools/blockheight/main.go
1. Add more examples for both tools `blockheight` and `blocketa`
2. Use the times + heights for the v2 activation height on each network
=> feat(tools): more examples for blocketa and blockheight

go.mod, go.sum
On Go 1.23 I got such failures:
```
% make build
--> Updating go.mod
--> Updating go.mod in ./test/interchain
../../../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
../../../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
make: *** [build] Error 1
```
Due to recent change in Go 1.23 where Go team removed some internal things. Simple bump works fine.
=> chore(go.mod): bump grafana/pyroscope-go deps

scripts/mainnet.sh
Modify the mainnet.sh script to provide the `--v2-upgrade-height` and use state sync.
=> chore(scripts): mainnet v2 upgrade height

app/app.go, app/app_test.go, go.mod, go.sum, scripts/arabica-block-sync.sh, scripts/arabica.sh, scripts/mocha-block-sync.sh, scripts/mocha.sh
Closes https://github.com/celestiaorg/celestia-app/issues/3840
Forward port of https://github.com/celestiaorg/celestia-app/pull/3843
I can state sync and block sync on Arabica and Mocha
```shell
./scripts/arabica.sh
./scripts/arabica-block-sync.sh
./scripts/mocha.sh
./scripts/mocha-block-sync.sh
```
=> fix: block sync on mocha on main

docs/release-notes/release-notes.md
fix https://github.com/celestiaorg/celestia-app/pull/3887?notification_referrer_id=NT_kwDOClGbmbUxMjQ2MzY5MTMwMToxNzMxMjA0MDk#pullrequestreview-2313343476
but Im not sure If I found the right link here cc @rach-id
=> docs: fix upgrade doc link

.github/workflows/docker-build-publish.yml
This PR add two features:
1. Allow docker to trigger on network specific tags.
2. This PR shows how to use the new input for the docker ci workflow added in celestiaorg/.github#112
This would allow triggering the docker workflow on a tag that (such as the new arabica and mocha tags) that didn't trigger the workflow originally.
Ref: 
- https://github.com/celestiaorg/celestia-node/pull/3765
- https://github.com/celestiaorg/celestia-node/pull/3766
=> feat: build on network tags and manual dispatch

test/e2e/testnet/testnet.go
While attempting to use testnet pkg in the node repo. There is a need to use `knuu` object that is initialized by the `testnet.New()` to create new instances and interact with `knuu`. Since it is not exported, this PR proposed to have a getter func for it, so users can interact with knuu easily.
=> chore: add a knuu getter

.github/mergify.yml
Closes https://github.com/celestiaorg/celestia-app/issues/3917
It modifies mergify.yml.
By adding the `forwardport:main` tag to the v1.x or v2.x branch, it can forward-port it to the main branch.
=> chore(ci): forward port setting in the mergify.yml

.github/workflows/docker-build-publish.yml, app/test/priority_test.go, pkg/da/data_availability_header_test.go, x/blob/client/testutil/integration_test.go, x/blobstream/keeper/keeper_data_commitment.go, x/blobstream/keeper/keeper_valset_test.go, x/mint/client/testutil/suite_test.go, x/mint/simulation/decoder_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/3919
Fix the lint errors of golangci-lint.
Merge this [PR](https://github.com/celestiaorg/celestia-app/pull/3923) to this branch.
=> fix(lint): golang-client lint errors

specs/src/SUMMARY.md, specs/src/ante_handler.md, specs/src/ante_handler_v3.md, specs/src/parameters.md
- Fixes #3762
- Adds ante handler v3 with updated links
=> docs: remaining docs from versioned gas scheduler variables

app/process_proposal.go, app/test/prepare_proposal_test.go, app/test/process_proposal_test.go, app/validate_txs.go, x/blob/ante/blob_share_decorator.go, x/blob/ante/blob_share_decorator_test.go
this PR makes a simple optimization for checkTx
=> chore: optimize checkTx

app/app_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/3956
=> fix: TestOfferSnapshot flake

app/ante/max_tx_size.go, app/ante/max_tx_size_test.go, app/test/prepare_proposal_test.go, app/test/process_proposal_test.go, app/validate_txs.go, pkg/appconsts/v3/app_consts.go, pkg/appconsts/versioned_consts.go, pkg/appconsts/versioned_consts_test.go, specs/src/ante_handler_v3.md
- `MaxTxBytes` to `MaxTxSize` in order to better distinguish between the mempool and the application param
- Removed the logic setting `ctx.WithTxBytes` for the transaction twice in one function due to two prs working on similar changes
=> refactor: cap tx size flups

pkg/appconsts/global_consts.go
=> chore: appconsts godoc cosmetics

app/default_overrides.go, app/default_overrides_test.go
Motivation in the **Mempool TTL duration** section of https://github.com/celestiaorg/celestia-app/issues/3959#issuecomment-2405769487
Modify the default consensus node config for mempools so that:
- TTLNumBlocks from 5 to 12 because 12 six second blocks = 72 seconds which is comparable to the existing 75 second TTLDuration.
- ~~MaxTxBytes from approx 7.5 MiB to 8 MiB because it's easier to understand and communicate~~
- ~~MaxTxsBytes from approx 37.6 MiB to 40 MiB because it's easier to understand and communicate~~
`make install && ./scripts/single-node.sh` then cat the config
```toml
version = "v1"
ttl-duration = "1m15s"
ttl-num-blocks = 12
```
=> feat: increase default mempool `TTLNumBlocks` to 12

app/test/prepare_proposal_test.go, app/validate_txs.go, pkg/appconsts/global_consts.go
Motivation: https://github.com/celestiaorg/CIPs/pull/220#discussion_r1803281819
IMO we should either include this in v3.0.0-rc0 or close it b/c not worth it to break these constant names after that.
=> refactor: rename limits from tx to msg

docs/maintainers/release-guide.md
Closes https://github.com/celestiaorg/celestia-app/issues/3913
=> docs: release-guide link to release notes

app/benchmarks/benchmark_msg_send_test.go
Handles the renaming feedback in https://github.com/celestiaorg/celestia-app/pull/3904#discussion_r1808009238
=> chore: rename megabyte to mebibyte

README.md, docs/release-notes/release-notes.md
adds to the release notes to make sure folks know how to enable bbr
=> docs: fix bbr notes

docs/release-notes/release-notes.md
Provide some information to validators on signalling to upgrade
=> docs: add notes about upgrading for validators in the release notes

test/e2e/testnet/defaults.go
There was an issue with the txsim that did not allow the E2ESimple test to run; consequently, ongoing celestia-node e2e tests fail.
```sh
/opt/entrypoint.sh: illegal option -- -
Invalid option:
```
Thanks to @smuu for his investigation to discover the root cause of the issue and to propose a solution that bumps the txsim version to make it work.
This PR proposes a version bump for txsim docker image in the e2e test.
=> chore: bump txsim version

Makefile
Fix: Enable automatic loading of tcp_bbr module after reboot
=> fix: enable tcp_bbr to load automatically after reboot

Makefile
adds a makefile command to enable and disable mptcp over different ports (not interfaces) for linux kernels greater than 5.6
not required, but potentially useful
=> feat: add command to enable mptcp

Makefile, app/default_overrides.go, docs/release-notes/release-notes.md
adds a script and better docs for configuring everything for v3
=> feat: add script to configure v3

Makefile
Since sh is the default shell in the Makefile, running configure-v3 resulted in the error: `/bin/sh: 2: [[: not found`. This fix modifies the syntax to be compatible with sh, allowing the script to run successfully without errors.
=> fix: replace bash syntax with sh in configure-v3

app/test/check_tx_test.go, app/test/process_proposal_test.go, pkg/user/signer.go, x/blob/types/payforblob.go
We already check this in `CheckTx` and `ProcessProposal`. This adds the same check to the client side construction so it errors before being submitted to the network. (the check being that the signer in the blob and the actual signer of the PFB are the same)
=> feat: check for correct signer in PFB construction

Makefile
On one of our node I found the default `ttl-num-blocks` value as `10` instead of `5`, so the default approach will not work in this case and it should be fixed with this commit.
=> fix: replace any `ttl-num-blocks` value

docs/maintainers/prebuilt-binaries.md, docs/maintainers/release-guide.md
**Description**:
This pull request addresses two spelling errors in the documentation files:
1. **In `docs/maintainers/prebuilt-binaries.md`**:
- The word **occured** is corrected to **occurred** (with two "r"s).
2. **In `docs/maintainers/release-guide.md`**:
- The word **relase** is corrected to **release** (with an extra "e").
**Importance**:
These spelling corrections ensure that the documentation is accurate and professional. Correct spelling is important in maintaining clarity and trust in the documentation, especially for new contributors and users. It also improves searchability, as users may encounter issues when searching for these terms with the incorrect spelling.
=> docs: fix typos in prebuilt-binaries.md and release-guide.md

.github/mergify.yml, docs/maintainers/release-guide.md, docs/release-notes/release-notes.md
I want to use this label on another PR I just made.
=> ci: enable backport:v3.x label

Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/4033
On my fork
v3.3.0-rc0: https://github.com/rootulp/celestia-app/releases/tag/v3.3.0-rc0
v3.3.0-arabica: https://github.com/rootulp/celestia-app/releases/tag/v3.3.0-arabica
v3.3.0-mocha: https://github.com/rootulp/celestia-app/releases/tag/v3.3.0-mocha
v3.3.0: https://github.com/rootulp/celestia-app/releases/tag/v3.3.0
=> fix: instruct GoReleaser to use current tag

x/signal/integration_test.go, x/signal/keeper.go, x/signal/keeper_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4007
Using the updated single-node.sh script (see other PR), I can query the version tally even after a successful try upgrade.
```
$ ./scripts/upgrade-to-v3.sh
$ celestia-appd query signal tally 3
threshold_power: "4167"
total_voting_power: "5000"
voting_power: "5000"
```
=> fix: `query signal tally` after successful try upgrade

go.mod, go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/4057
=> chore(deps): upgrade to celestia-core v1.44.0

app/extend_block.go, app/test/integration_test.go
This will be helpful in Celestia-node to avoid copying the block when checking if it's empty
=> chore: check if a block is empty by taking its reference

test/util/testnode/comet_node_test.go, test/util/testnode/config.go
Closes https://github.com/celestiaorg/celestia-app/issues/3775
The default testnode config should closely match the mainnet config. If we have one-off tests that require overrides for certain values then they should be overridden at the test level not at the default testnode config level.
=> test: reduce testnode overrides

Makefile, app/test/upgrade_test.go, docs/architecture/adr-015-namespace-id-size.md, pkg/appconsts/overrides.go, pkg/appconsts/versioned_consts.go, pkg/appconsts/versioned_consts_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4053
1. Override the upgrade height for chain-id `test` to 3 so that there are still a few blocks of delay in tests
1. Remove `OverrideUpgradeHeightDelayStr` because it was confusing to have multiple ways to override the upgrade height (1) chain-id and (2) via ENV variables
=> refactor: override the upgrade height for chain-id `test` to 3

cmd/celestia-appd/cmd/start.go
This change was prompted by an attempt to run the application in an unprivileged docker container based on a slim image. The absence of the `sysctl` command causes the application to fail the BBR check, even though that module is loaded and available.
The goals of this PR are:
- allow the application to run the BBR check in a restricted environment such as a docker container
- make the application distribution agnostic by removing the `systemd` dependency
- remove an instance of process forking with `exec`
=> refactor: remove sysctl dependency from start command

specs/src/cat_pool.md, specs/src/data_square_layout.md, test/e2e/readme.md
1. Fix typos in transaction-related terms:
- "transacton" → "transaction"
- "transcation" → "transaction"
- "WantMsg" → "WantTx"
2. Fix grammar:
- "blobs must be placed is a way" → "blobs must be placed in a way"
3. Update environment variable name for consistency:
- "KNUUU_TIMEOUT" → "KNUU_TIMEOUT"
4. Fix apostrophe usage:
- "TTL's" → "TTLs"
5. Update minikube documentation link:
- Change from French version (kubernetes.io/fr/) to English version (kubernetes.io/docs/)
=> docs: fix transaction typos, grammar and documentation links

.github/CODEOWNERS, .github/auto_request_review.yml
Closes https://github.com/celestiaorg/celestia-app/issues/4092
Note: hasn't been tested yet. Seems like something we can verify post merge.
=> chore: auto request all reviewers

.github/workflows/ci-release.yml, .github/workflows/goreleaser.yml, Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/4081
On my fork all of [these releases](https://github.com/rootulp/celestia-app/actions/workflows/ci-release.yml?query=event%3Arelease) used the correct tag and uploaded prebuilt binaries.
=> ci(goreleaser): use latest tag from GitHub action

app/benchmarks/benchmark_ibc_update_client_test.go, app/test/upgrade_test.go, pkg/appconsts/chain_ids.go, pkg/appconsts/versioned_consts.go, pkg/appconsts/versioned_consts_test.go, test/e2e/benchmark/throughput.go, x/signal/integration_test.go, x/signal/keeper_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4070
=> refactor: export test chain id

app/ante/tx_size_gas.go, app/app.go, app/app_test.go, docker/Dockerfile
This pull request addresses several minor grammatical and typographical fixes across comments and documentation in the codebase. These adjustments enhance readability and correctness without altering any code functionality.
1. Corrected "over estimated" to "overestimated" in `tx_size_gas.go`.
2. Changed "signalling" to "signaling" to align with American English standards in `app.go`.
3. Fixed "intialised" to "initialised" in `app.go`.
4. Clarified a redundant phrase in `app_test.go` comments.
5. Fixed "maxuimum" to "maximum" in `Dockerfile`.
These fixes contribute to maintaining a clean and professional codebase, ensuring that comments and documentation are accurate and easy to understand.
No new tests were added, as these changes are non-functional. Existing tests and workflows remain …
=> fix: multiple typos

test/e2e/minor_version_compatibility.go, test/e2e/testnet/versions.go
Closes https://github.com/celestiaorg/celestia-app/issues/4116
```shell
test-e2e2024/12/13 10:44:02 === RUN MinorVersionCompatibility
test-e2e2024/12/13 10:44:02 Running MinorVersionCompatibility test with versions v1.0.0	v1.1.0	v1.10.0	v1.10.1	v1.11.0	v1.12.0	v1.13.0	v1.14.0	v1.2.0	v1.3.0	v1.3.0	v1.4.0	v1.5.0	v1.6.0	v1.7.0	v1.9.0	v2.0.0	v2.1.0	v2.1.1	v2.1.2	v2.2.0	v2.2.0	v2.2.0	v2.3.0	v2.3.0	v2.3.1	v2.3.1	v3.0.0	v3.0.0	v3.0.0	v3.0.1	v3.0.1	v3.0.1	v3.0.2	v3.0.2	v3.0.2
```
- Doesn't contain the retracted version: https://github.com/celestiaorg/celestia-app/releases/tag/v1.8.0
- Doesn't contain release candidates
- Does contain v3 versions
=> test(e2e): filter out retracted version

go.mod, go.sum
Upgrade to the latest cosmos-sdk release
=> chore(deps): upgrade to cosmos-sdk v1.25.1

test/util/test_app.go, x/blobstream/abci_test.go, x/blobstream/types/msgs.go
fix some function names in comment
=> chore: fix some function names in comment

docs/architecture/adr-004-qgb-relayer-security.md
Correcting the typo from `LatestAttestationtNonce` to `LatestAttestationNonce` ensures code consistency, improves readability, and prevents confusion among developers. Accurate naming makes the code easier to maintain and reduces the risk of future errors.  
Check the code and ensure that all variables use `LatestAttestationNonce` consistently.
Thanks
=> fix: typos

docs/architecture/adr-002-qgb-valset.md
**docs/architecture/adr-002-qgb-valset.md**
- Fixed typo: "`signification`" →  "`significant`"
=> chore: docs fix 

app/ante/ante.go, app/export.go, test/util/testfactory/namespace.go, x/signal/types/keys.go
This PR addresses and corrects grammatical errors in comments across multiple files. 
Specifically, it replaces the incorrect usage of "a" with "an" before words starting with vowel sounds. 
The affected files include:
- `ante.go`
- `export.go`
- `namespace.go`
- `keys.go`
=> fix: grammatical typos

specs/src/proto/types.proto, specs/src/proto/wire.proto
The link has expired, replace it with the latest address
=> docs: fix URL

docs/architecture/adr-011-optimistic-blob-size-independent-inclusion-proofs-and-pfb-fraud-proofs.md
…ion-proofs-and-pfb-fraud-proofs.md
Hello and happy new year.
I fixed a typo in this text:
"fraud poof": Should be "fraud proof".
Thanks.
=> chore: fix typo

docs/architecture/adr-002-qgb-valset.md, pkg/appconsts/global_consts.go, pkg/appconsts/initial_consts.go, pkg/da/data_availability_header_test.go
This pull request addresses the following errors in the documentation:
"messages" -> "message"
"defacto" -> "de facto"
"nodes" -> "node's"
"bash hash" -> "bad hash"
I hope my corrections will help you. Thank you for your work.
=> chore: fix typos

test/util/malicious/out_of_order_prepare.go, test/util/malicious/tree.go
"namepspaces - namespaces"
"hahser - hasher"
=> docs: fix typos

test/txsim/stake.go, test/util/genesis/accounts.go
Changes Made:
1. test/util/genesis/accounts.go:
- Old: "validitor" -> New: "validator"
- Location: Comment before ValidateBasic function
2. test/txs/stake.go:
- Old: "redelgated" -> New: "redelegated" 
- Location: Comment in stake sequence function
Reason:
Fixed misspellings in code comments to improve readability and maintain consistent terminology. These are documentation-only changes with no functional impact.
=> docs: fix typo

docs/release-notes/release-notes.md
Fixed the capitalization of `"Linux"` in the release notes to enhance readability and maintain consistency in documentation. This change aligns with previous efforts to improve the clarity of the project's documentation.
=> docs: correct capitalization in release notes

pkg/wrapper/nmt_wrapper_test.go
- Renamed `TestErasureNamespacedMerkleTreePushErrors` to `TestErasuredNamespacedMerkleTreePushErrors` for consistency.
- Fixed variable name `sqaureSize` to `squareSize`.
These changes enhance code readability and maintainability.
=> fix: correct typos in test function names and variables in nmt_wrapper_test.go

docs/architecture/adr-001-abci++-adoption.md, docs/architecture/adr-004-qgb-relayer-security.md, docs/architecture/adr-009-non-interactive-default-rules-for-reduced-padding.md
- Fixed "it normal" to "it is normal" in `adr-001-abci++-adoption.md`.
- Corrected "up to date" to "up-to-date" in `adr-004-qgb-relayer-security.md`.
- Removed unnecessary "of" in "all of the" in `adr-009-non-interactive-default-rules-for-reduced-padding.md`.
=> fix: spelling errors

app/default_overrides_test.go
Part of https://github.com/celestiaorg/celestia-app/issues/4213
The real fix is in https://github.com/celestiaorg/cosmos-sdk/pull/425 but this is a nice to have.
=> test: default override rates

Makefile
Before the `configure-v3` command didn't show up in Makefile help
=> docs: configure-v3

app/default_overrides.go, app/default_overrides_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4204
Note this won't modify already existing `app.toml` files so node operators need to modify their local `app.toml`. Example command:
```shell
sed -i.bak 's/^max-recv-msg-size = "10485760"/max-recv-msg-size = "20971520"/' ~/.celestia-app/config/app.toml
```
```shell
$ cat ~/.celestia-app/config/app.toml | grep max-recv
max-recv-msg-size = "10485760"
$ ./scripts/single-node.sh
$ cat ~/.celestia-app/config/app.toml | grep max-recv
max-recv-msg-size = "20971520"
```
=> feat: increase max-recv-msg-size default to 20 MiB

go.mod, go.sum, test/interchain/go.mod, test/interchain/go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/4213 by upgrading to https://github.com/celestiaorg/cosmos-sdk/releases/tag/v1.26.1-sdk-v0.46.16 which contains the fix.
=> chore(deps): sdk v1.26.1-sdk-v0.46.16

go.mod, go.sum, test/interchain/go.mod, test/interchain/go.sum
Bump to latest core and cosmos-sdk to support the new block gRPC endpoints
=> chore(deps): bump to core v1.45.0-tm-v0.34.35 and cosmos-sdk v1.27.0-sdk-v0.46.16

README.md, docs/release-notes/release-notes.md, tools/blocktime/readme.md, x/blob/README.md
- Fixes broken links in current markdown documentation
- Pairs the broken links with appropriate corresponding live (not broken) page links
=> fix:  broken links in markdown documentation

Makefile
=> Update Makefile: Fix typo max_txs_bytes

Makefile
Fixes another typo in the `make configure-v3` command.
=> fix: sed command on Linux

docs/architecture/adr-023-gas-used-and-gas-price-estimation.md
=> docs: gas used and gas price estimation ADR

tools/bytes-in-block/README.md, tools/bytes-in-block/main.go
Extremely optional tool for https://github.com/celestiaorg/celestia-app/issues/4212
```
$ go run main.go
Fetched a total of 1400 blocks (from ~4156770 up to ~4158132).
Average bytes_in_block: 2634636.38 bytes (~2.51 MiB)
Average block_time:     5967.89 ms (~5.97 seconds)
```
another invocation
```
$ go run main.go
Fetched a total of 110 blocks (from ~4170798 up to ~4170898).
Average bytes_in_block: 5617659.89 bytes (~5.36 MiB)
Average block_time:     6761.83 ms (~6.76 seconds)
```
=> feat(tools): bytes in block tool

app/errors/errors.go
This commit improves the error handling in the app/errors package by:
- Adding documentation for AppErrorsCodespace constant
- Clarifying the error code range convention
- Improving error message clarity for ErrTxExceedsMaxSize
- Adding proper documentation for error variables
These changes make the error handling more maintainable and
easier to understand for other developers.
=> docs: improve error handling documentation and messages

pkg/user/signer.go, pkg/user/tx_client_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4258
If there are other places where it would be beneficial to document the API, please let me know to make the corresponding changes.
=> feat: add the gas estimation API to the signer

app/app.go, app/test/consistent_apphash_test.go, x/paramfilter/test/gov_params_test.go
- **Fixed incorrect variable name in `app.go`**:
- `tokenFilterMiddelware` → `tokenFilterMiddleware` to maintain proper naming consistency.
- **Corrected function name in `consistent_apphash_test.go`**:
- `msgCreatePermamentLockedAccount` → `msgCreatePermanentLockedAccount` to match the intended function definition.
- **Updated incorrect variable name in `gov_params_test.go`**:
- `gotQuroum` → `gotQuorum` to align with correct terminology in governance tally parameters.
=> refactor: fix typos

app/default_overrides.go, app/default_overrides_test.go
updates the default mempool values
=> chore: update mempool defaults

x/blobstream/genesis.go
=> docs: fix comment

app/default_overrides.go, app/default_overrides_test.go
We got reports from @mindstyle85 that the v2 mempool caused issues for users so we're reverting the default back to the prioritized mempool v1.
=> revert: default mempool to prioritized (v1)

docs/maintainers/release-guide.md
To instruct maintainers to use a minor version branch.
Note: this still doesn't enforce that releases are created via minor branches but it's a first step.
=> docs: update release guide

go.mod, go.sum, test/interchain/go.mod, test/interchain/go.sum
Replace ibc-go dependency with https://github.com/celestiaorg/ibc-go/releases/tag/v6.2.3 which includes a fix for https://github.com/cosmos/cosmos-sdk/security/advisories/GHSA-8wcc-m6j2-qxvm
=> fix: non-deterministic JSON in IBC acks

test/e2e/benchmark/main.go
"No test is specified." → "No test was specified."
Reason: The second version ("No test was specified") is grammatically correct and clearer. Using past tense ("was specified") is more appropriate as it indicates that no test was provided at the time of executing the command.
"Valid tests are: %s\n\n" → "Valid test names are: %s\n\n"
Reason: The change from "tests" to "test names" clarifies that it is not the actual tests that are being referred to, but rather the names of the available tests. This makes the message more precise and understandable.
"Valid tests are: %s\n" → "Valid test names are: %s\n"
Reason: Similarly to the previous change, this modification emphasizes that the printed list is a set of test names, not the tests themselves. It adds clarity to the output message.
=> docs: fix grammar in logs

local_devnet/celestia-app/app.toml
- `dependant` → `dependent`
- `enabled` → `enable`
- `Blockchain` → `Network`
- `medata` → `metadata`
=> docs: Fix spelling errors in `app.toml`

x/blob/client/testutil/integration_test.go
no need remove TempDir manually, after changed to t.TempDir(), tested below
test log:
```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^TestIntegrationTestSuite$ -testify.m ^(TestSubmitPayForBlob)$ github.com/celestiaorg/celestia-app/v3/x/blob/client/testutil
=== RUN   TestIntegrationTestSuite
/Users/dengdiliang/ddl/github_sources/celestia-app/x/blob/client/testutil/integration_test.go:63: setting up integration test suite
=== RUN   TestIntegrationTestSuite/TestSubmitPayForBlob
=== RUN   TestIntegrationTestSuite/TestSubmitPayForBlob/single_blob_valid_transaction
--- PASS: TestIntegrationTestSuite/TestSubmitPayForBlob/single_blob_valid_transaction (1.05s)
=== RUN   TestIntegrationTestSuite/TestSubmitPayForBlob/multiple_blobs_valid_transaction
--- PASS: …
```
=> refactor(x/blob): use t.TempDir() instead of os.MkdirTemp 

app/modules.go, docs/architecture/adr-002-qgb-valset.md, local_devnet/celestia-app/app.toml, pkg/proof/proof.pb.go, pkg/wrapper/nmt_wrapper.go, specs/src/parameters_v1.md, test/pfm/simapp.go, x/blobstream/README.md
Fixed typos in documentation:
- "dependant" → "dependent"
- "Multsig" → "Multisig"
- "parameter" → "parameters"
- "medata" → "metadata"
- "a ErasuredNamespacedMerkleTree" → "an ErasuredNamespacedMerkleTree"
=> docs: fix typos in multiple files

cmd/celestia-appd/cmd/app_server.go, test/util/malicious/test_app.go
I am verifying some lint idea in my project see https://github.com/alingse/sundrylint/pull/10
it report the function call with repeat args from a sub-function call.
we think the sub-function call is heavy, so the repeat args probably a copy-and-paste mistake.
I check the top 4000 github repos, and found this repo has this case.
=> refactor: remove duplicate `SetMinRetainBlocks` invocation

x/blob/types/payforblob.go
standard library package:`slices` already include slices.Contains since Go 1.21, remove experimental package `x/exp `
=> refactor: remove x/exp dependency for slices package

app/grpc/tx/tx.pb.go, proto/celestia/core/v1/tx/tx.proto, proto/celestia/qgb/v1/query.proto, x/blobstream/types/query.pb.go
✅ **tx.proto**
- Updated the description of `tx_id` in `TxStatusRequest` to clarify it is a **64-character hex string representing 32 bytes** instead of misleading "64 bytes".
✅ **query.proto**
- Refactored HTTP option formatting for consistency (`option (google.api.http) = { get: ... }`).
- Improved comment clarity.
=> docs: improve proto comments

docs/architecture/adr-023-gas-used-and-gas-price-estimation.md, x/minfee/README.md, x/signal/README.md
Hi! I fixed broken links in the documentation across multiple files. The links to Celestia Improvement Proposals (CIPs) were incorrect due to inconsistent formatting of the CIP numbers (e.g., `cip-18.md` instead of `cip-018.md`). This PR standardizes the links to ensure they point to the correct resources.
=> docs: fix broken links in docs

.github/dependabot.yml, .github/workflows/codeql.yml, .github/workflows/docker-build-publish.yml, .github/workflows/github-pages.yml, .github/workflows/goreleaser.yml, .github/workflows/issue-label-automation.yml, .github/workflows/lint-pull-request.yml, .github/workflows/lint.yml, .github/workflows/markdown-linter.yml, .github/workflows/pr-review-requester.yml, .github/workflows/project-automation.yml, .github/workflows/protobuf.yml, .github/workflows/stale.yml, .github/workflows/test-e2e.yml, .github/workflows/test.yml
This PR fixes: https://github.com/celestiaorg/celestia-app/issues/4426
Modify a GH action in this repo to use SHAs instead of tags. Include a comment with the version so that dependabot can update it.
=> ci: add SHAs and commented versions in workflow .yml files

app/ante/tx_size_gas.go, pkg/inclusion/nmt_caching_test.go, tools/blocktime/main.go
=> refactor: modernized code with built-in func

app/init.go, app/init_test.go, go.mod, go.sum, test/interchain/go.mod, test/interchain/go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/4427
The only important change is ignoring the error returned by `os.UserHomeDir()`. The rest of the diff is a refactor for legibility. I re-ordered celestiaHome in arguments and test cases first because it takes precedence over userHome.
cc: @lzrscg
=> fix: enable celestia-app to run in Vercel Go runtime

docs/release-notes/pending-release.md, pkg/appconsts/versioned_consts.go, pkg/appconsts/versioned_consts_test.go, x/signal/keeper_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4413
Note: This targets main but it won't ever be used on main because https://github.com/celestiaorg/celestia-app/pull/4400 simplifies the versioned constants. Main (and v4+) won't have versioned constants because they just need to support constants for the latest release. This change will be backported to v3.x where it will be used.
=> feat!: reduce upgrade height delay for Arabica and Mocha

go.mod, go.sum
Upgrade to https://github.com/celestiaorg/go-square/releases/tag/v2.2.0
=> chore(deps): upgrade to go-square v2.2.0

x/blob/ante/blob_share_decorator.go, x/blob/ante/blob_share_decorator_test.go
Previously the BlobShareDecorator was not looking inside authz `MsgExec`s.
=> fix: BlobShareDecorator check for nested authz messages

x/blob/ante/ante.go, x/blob/ante/ante_test.go
Previously the MinGasPFB decorator was not looking inside authz `MsgExec`s.
=> fix: MinGasPFB decorator check for nested authz messages 

x/blob/ante/ante.go, x/blob/ante/ante_test.go
Reverts celestiaorg/celestia-app#4468
This decorator runs in process proposal because of these lines:
```go
if ctx.IsReCheckTx() {
return next(ctx, tx, simulate)
}
```
and we'd rather not include a consensus breaking change in a patch release.
=> revert: "fix: MinGasPFB decorator check for nested authz messages  (backport #4465)"

app/ante/ante.go, app/ante/msg_exec.go, app/ante/msg_exec_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/3609 by adding a new ante handler that rejects a tx if it contains a MsgExec which contains a MsgExec or MsgPayForBlobs.
=> feat(ante)!: reject MsgExec if it contains a MsgExec or MsgPayForBlobs

app/ante/ante.go, app/ante/msg_exec.go, app/ante/msg_exec_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/3609 by adding a new ante handler that rejects a tx if it contains a MsgExec which contains a MsgExec or MsgPayForBlobs.
Note: this targets v3.x so the antehandler only runs on checkTx.
=> feat(ante): reject MsgExec if it contains a MsgExec or MsgPayForBlobs

cmd/celestia-appd/cmd/root.go, go.mod, go.sum
Pending https://github.com/celestiaorg/cosmos-sdk/pull/433
=> feat: wire module-by-hash debug command

README.md
Closes https://github.com/celestiaorg/celestia-app/issues/4229
Low likelihood that this stops air-drop hunters but worth a shot. 
Ref: https://github.com/celestiaorg/.github/blob/main/CONTRIBUTING.md#pull-requests
=> docs: link to org wide CONTRIBUTING guideline

Makefile
The changes include:
- Adding documentation for the 'disable-mptcp' target as requested in issue #4216
- Adding documentation for internal implementation targets like 'check-bbr'
- Adding documentation for Docker-related targets (build-docker, build-ghcr-docker, publish-ghcr-docker)
- Adding documentation for the prebuilt-binary target
Fixes #4216
=> docs: document all Makefile targets

specs/src/state_machine_modules_v1.md, specs/src/state_machine_modules_v2.md
Trying to get green CI checks on `main`.
`make markdown-link-check` passes locally
=> docs: fix markdown links

Makefile
Bump downloaded binary on `make build` and `make install` to v3.9.0-rc0
=> build: bump embedded binary to v3.9.0-rc0

.github/workflows/docker-build-publish.yml
In order to build and test images in the v3 line on non amd64 architectures, we can update the workflows to build multi arch images.
The current 0.5.0 workflow builds [just for amd64](https://github.com/celestiaorg/.github/blob/45533fc35847a8568deb0d4cae1851a2872f3651/.github/workflows/reusable_dockerfile_pipeline.yml#L311) while the newer workflow builds for both [`amd64` and `arm64`](https://github.com/celestiaorg/.github/blob/v0.6.1/.github/workflows/reusable_dockerfile_pipeline.yml#L305)
=> ci: build v3 docker images with multiple platforms

x/blob/README.md
- Added a reference to the implementation responsible for generating the share commitment used in blob inclusion proofs.
- Included a mention of the specification that explains how fraud proofs work in the context of data availability.
=> docs: replace TODO with links to blob inclusion and fraud proof documentation

cmd/celestia-appd/cmd/start.go
Currently, when running in standalone mode (i.e. as an embedded binary in the multiplexer), the tm services are not registered correctly. 
When running the E2E upgrade test, txsim got the following error
```
Error: rpc error: code = Unimplemented desc = unknown service cosmos.base.tendermint.v1beta1.Service
Usage:
txsim [flags]
```
When working with local binaries we didn't hit the same api.
This will need to make its way into a v3 tag.
=> fix: add registration of tendermint and node services in standalone mode

app/benchmarks/benchmark_msg_send_test.go
BenchmarkProcessProposal_MsgSend_8MB emitted `block_size_(mb)` (extra underscore), creating a duplicate metric and splitting dashboard/alert data. Renamed to `block_size(mb)` for consistent aggregation across all benchmarks.
=> refactor(benchmarks): align metric name to `block_size(mb)`

go.mod, go.sum, multiplexer/abci/multiplexer.go
=> chore: update the default address for remote ABCI over grpc

README.md, app/init.go, app/init_test.go
Ref: #4532
This PR adds the environment variable `CELESTIA_APP_HOME`, behaving as #4532 prescribes. It does not change the behavior of `CELESTIA_HOME` if used without `CELESTIA_APP_HOME`. When used together, `CELESTIA_APP_HOME` takes precedence (since `CELESTIA_HOME` can still be set for `celestia-node`).
=> fix: `CELESTIA_HOME` for app v3

Makefile, README.md
Motivated by https://celestia-team.slack.com/archives/C02PFFCGMNW/p1745700834072559
```
$ rm internal/embedding/*.tar.gz
$ make build
--> Updating go.mod
--> Updating go.mod in ./test/interchain
--> Downloading embedded binaries for v3
Binary celestia-app_darwin_v3_arm64.tar.gz not found, downloading
Binary celestia-app_linux_v3_arm64.tar.gz not found, downloading
Binary celestia-app_darwin_v3_amd64.tar.gz not found, downloading
Binary celestia-app_linux_v3_amd64.tar.gz not found, downloading
--> Downloaded embedded binaries for v3
--> Building build/celestia-appd with multiplexer enabled
```
=> fix: download v3 binaries on make build

Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/4705
- `make build` passes locally
- [CI build](https://github.com/celestiaorg/celestia-app/actions/runs/14758805123/job/41433985530?pr=4707) passes
=> fix: make build

Makefile
Closes #4664
This PR refactors the `make install` process to download only the embedded v3 binary required for the current platform (`GOOS`/`GOARCH`), instead of downloading all 4 binaries (linux/macOS, amd64/arm64). This improves efficiency and reduces redundant downloads.
- Added platform detection logic (`go env GOOS` / `GOARCH`) in the `download-v3-binaries` Makefile target.
- Replaced the loop over all 4 platforms with a `case` statement that selects the appropriate binary for the current host.
- Updated `download_v3_binary.sh` script is used to handle version checking and downloading.
On an M2 MacBook (`darwin/arm64`), the following result is observed:
```bash
make install
Checking if BBR is enabled...
sysctl: unknown oid 'net.ipv4.tcp_congestion_control'
WARNING: BBR is not …
```
=> fix: download only current platform's embedded v3 binary in `make install`

app/default_overrides.go, app/default_overrides_test.go
When running `celestia-appd init` the following is present in the gov params
```json
"expedited_min_deposit": [
{
"denom": "stake",
"amount": "50000000"
}
],
```
=> fix: update the default bond denom in default_overrides

Makefile, docker/txsim/Dockerfile
closes #4712
The existing command just looked at tags with no constraints, this became a problem with a second go.mod being introduced. 
The new command filters by tags beginning with `v` (i.e no workflow or multiplexer tags ), and strips the v. This is in line with how it is in other binaries.
running locally I get
```sh
celestia-appd version
4.0.0-rc1-32-g229e6ab4
celestia-appd passthrough v3 version
3.9.0-rc0
```
If this is run on a tag itself, it should return just the tag. E.g. `4.0.0-rc1`
This is in line with how it is done in [the sdk](https://github.com/celestiaorg/cosmos-sdk/blob/9901e41a28bad6e39de0e464038a2718ed4e8ac3/Makefile#L5)
=> fix: correct version command in Makefile

Makefile, docker/multiplexer.Dockerfile
Closes https://github.com/celestiaorg/celestia-app/issues/4709
```
make build-docker-multiplexer
```
```
$ make build
--> Updating go.mod
--> Updating go.mod in ./test/interchain
--> Downloading celestia-app v3.9.0-rc0 binary
Skipping download because expected version already downloaded: celestia-app_darwin_v3_arm64.tar.gz
--> Building build/celestia-appd with multiplexer enabled
$ make build DOWNLOAD=false
--> Updating go.mod
--> Updating go.mod in ./test/interchain
--> Building build/celestia-appd with multiplexer enabled
$ make build DOWNLOAD=true
--> Updating go.mod
--> Updating go.mod in ./test/interchain
--> Downloading celestia-app v3.9.0-rc0 binary
Skipping download because expected version already downloaded: celestia-app_darwin_v3_arm64.tar.gz
--> Building build/celestia-appd …
```
=> fix: docker build for multiplexer

docs/maintainers/release-guide.md
This adds instructions on how we get multiplexer or v3.x.x changes into the latest v4.x.x release.
=> docs: release notes for multiplexer and v3.x.x

cmd/celestia-appd/cmd/start.go, local_devnet/celestia-app/config.toml
I hope this is the correct target branch?
This PR replicates the changes in https://github.com/celestiaorg/cosmos-sdk/pull/576 but for celestia-app/v3.
ref: #4646
=> fix: use 36658 for abci over grpc for v3.x

README.md, cmd/celestia-appd/cmd/testnet.go, docker/Dockerfile, docker/multiplexer.Dockerfile, docker/txsim/Dockerfile
Fixes a regression introduced in https://github.com/celestiaorg/celestia-app/pull/4666
Should use the standard `appDirectory` const: https://github.com/celestiaorg/celestia-app/blob/main/app/init.go#L18
=> fix: use standard appDirectory where applicable

local_devnet/celestia-app/genesis.json, multiplexer/cmd/start.go
found when trying to replicate https://github.com/celestiaorg/celestia-app/issues/4763#issuecomment-2855796623.
running ` ./local_devnet/scripts/init.sh` would fail on hyperlane genesis unmarshal.
the script doesn't work nice because of the renaming of local_devnet chain id.
`MULTIPLEXER=true  ./local_devnet/scripts/init.sh` works fine tho.
=> test(scripts): add missing genesis

docker/multiplexer.Dockerfile, multiplexer/abci/multiplexer.go
Due to the multiplexer copying start command functionality from the sdk, I discovered that running native apps (for example, v4) will not expose the core BlockAPI when through the multiplexer, i.e. the changes in https://github.com/celestiaorg/cosmos-sdk/pull/455 do not take effect which spin up the core BlockAPI in-process.
The BlockAPI is however available right now when:
- Running embedded apps (for example, v3) through the multiplexer. 
- Running a v4 standalone app without the multiplexer.
The replication of start command code being distributed and copied amongst different places is extremely error prone to manage, and quite frankly, its spaghetti.
=> fix: ensure core block api runs through multilplexer native app

cmd/celestia-appd/cmd/start.go
Closes https://github.com/celestiaorg/celestia-app/issues/4773
IMO it's a huge foot gun that it is possible to invoke `ctx.Logger.Error("msg", key)` without a corresponding value. 
If reviewers want, I'm also open to replacing all of the modified lines with this format which seems like the original intention:
```
ctx.Logger.Error(fmt.Sprintf("failed to start api server: %v", err))
```
=> fix(cmd): include error in logs

app/default_overrides.go, app/default_overrides_test.go, docs/release-notes/release-notes.md, scripts/single-node.sh
Closes https://github.com/celestiaorg/celestia-app/issues/4729
IIUC then the RPC GRPC listen address is used when the multiplexer binary is running celestia-app v3 prior to the v4 activation height. Since `./scripts/single-node-upgrades.sh` still works, it seems safe to use `127.0.0.1` instead of `0.0.0.0`.
=> refactor: use 127.0.0.1 for RPC GRPC listen address

multiplexer/abci/remote_v1.go, multiplexer/abci/remote_v1_test.go, scripts/arabica-block-sync.sh
Closes https://github.com/celestiaorg/celestia-app/issues/4800
The multiplexer was converting a `nil` consensus params into a zeroed out consensus params. celestia-core used the zeroed out consensus params to overwrite the app version in state 😭 
This fix modifies the multiplexer to return `nil` consensus params if InitChain returned `nil` consensus params to match the behavior on v3.x.
```
make install
./scripts/arabica-block-sync.sh
```
starts block syncing from genesis
=> fix(multiplexer): arabica block sync

multiplexer/cmd/start.go
Simplified `getState` while debugging https://github.com/celestiaorg/celestia-app/issues/4800.
Something was weird in core about `state.Version.Consensus.App` (https://github.com/celestiaorg/celestia-core/blob/v1.51.0-tm-v0.34.35/state/state.go#L326-L377), but eventually reverted that change https://github.com/celestiaorg/celestia-app/pull/4801/commits/b0ecce51788a29d7f33ed1c15691a561c0de9ebe as it was a core specific change.
=> refactor(multiplexer): simplify `getState`

go.mod, go.sum
Part of https://github.com/celestiaorg/celestia-app/issues/4806
This release of celestia-core increases the GRPC max message recv size
=> chore(deps): upgrade to v1.52.0-tm-v0.34.35

Makefile
Attempts to close https://github.com/celestiaorg/celestia-app/issues/4816 🤞 
I'm surprised by the `test-race` failure because the `TestReadBlockchainHeaders` hasn't been modified recently
=> test: skip TestReadBlockchainHeaders in race mode

multiplexer/appd/run.go
Closes https://github.com/celestiaorg/celestia-app/issues/4838
Previously every `celestia-appd` invocation created a tmp directory and didn't clean it up. With this PR, the tmp directory gets cleaned up.
```shell
$ ls  /var/folders/y0/dd92_x8x4tlf397xstgwfz_c0000gn/T/ | grep appd-v3-* | wc -l
2289
$ rm -rf /var/folders/y0/dd92_x8x4tlf397xstgwfz_c0000gn/T/appd-v3-*
$ ls  /var/folders/y0/dd92_x8x4tlf397xstgwfz_c0000gn/T/ | grep appd-v3-* | wc -l
0
$ make install
$ celestia-appd foo
Error: unknown command "foo" for "celestia-appd"
Run 'celestia-appd --help' for usage.
$ ls  /var/folders/y0/dd92_x8x4tlf397xstgwfz_c0000gn/T/ | grep appd-v3-* | wc -l
0
```
=> fix(multiplexer): clean up tmp directories

multiplexer/cmd/passthrough.go, multiplexer/cmd/passthrough_test.go
this pr makes `celestia-appd passthrough`, `celestia-appd passthrough -h` or `celestia-appd passthrough --help` show the commands help information. 
closes #4850 
the reason this change is needed is because `DisableFlagParsing` is set to true so it would always try to execute the command of the underlying binary which would fail without the top level `passthrough` command help showing
=> fix: make passthrough show help

multiplexer/appd/run.go
Reverts https://github.com/celestiaorg/celestia-app/pull/4842 because it caused this regression https://github.com/celestiaorg/celestia-app/issues/4849.
This should unblock @damiannolan from testing https://github.com/celestiaorg/celestia-app/pull/4852#issuecomment-2897276927
=> revert: "fix(multiplexer): clean up tmp directories (#4842)"

.github/workflows/docker-build-publish.yml
This PR removes the usage of buildArgs since it is already set in the reusable pipeline workflow https://github.com/celestiaorg/.github/blob/main/.github/workflows/reusable_dockerfile_pipeline.yml#L269C11-L269C45
closes #4855 
CI could be skipping the build due to me being marked as external.
=> fix: build docker image for multiple platforms

.goreleaser.yaml, Makefile, scripts/download_v3_binary.sh
closes: #4798
This PR updates the goreleaser file to add builds for the multiplexer.
Output of local dry run
```
make go-releaser-dry-run
Running GoReleaser in dry-run mode...
docker run \
--rm \
--env CGO_ENABLED=1 \
--env GORELEASER_CURRENT_TAG= \
--env-file .release-env \
-v /var/run/docker.sock:/var/run/docker.sock \
-v `pwd`:/go/src/github.com/celestiaorg/celestia-app/v4 \
-w /go/src/github.com/celestiaorg/celestia-app/v4 \
ghcr.io/goreleaser/goreleaser-cross:v1.23.6 \
release --snapshot --clean --parallelism 4
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credential-stores
Login Succeeded
WARNING! Your password will be stored …
```
=> ci: update go releaser to support multiplexer

multiplexer/appd/init.go
Addresses feedback from https://github.com/celestiaorg/celestia-app/pull/4851
I was also going to refactor the two `init.go` files in this PR but it seems worth punting that because it may cause unnecessary side-effects. In other words, the ordering of `init()` execution may change and seems not worth risk.
=> chore: address feedback on #4851

go.mod, go.sum, test/interchain/go.mod, test/interchain/go.sum
Closes https://github.com/celestiaorg/celestia-app/issues/4888 by upgrading to https://github.com/celestiaorg/celestia-core/releases/tag/v1.52.1-tm-v0.34.35 which contains https://github.com/celestiaorg/celestia-core/pull/1872
=> fix: enable downgrades from v4.x.x

README.md
During the adoption onsite, @jcstein and I were confused about all the servers exposed by celestia-app. I promised to write a blurb about it and this is a first attempt at that.
I could see this being improved upon in the future by:
- describe which server gets hit when a user submits a blob
- describe which server needs to be used to connect to a bridge node / light node
- include a diagram
=> docs(README): server architecture

go.mod, go.sum, multiplexer/abci/multiplexer.go, test/docker-e2e/go.mod, test/docker-e2e/go.sum
This PR adds an assertion in the multiplexer which ensures that the configuration of the consensus engine remote ABCI client, matches that of the app state machine ABCI server.
The intension is to fix issues where changes to the configuration file `config.toml` which belongs to consensus engine and not respected. 
If a user or node operator wants to use an alternative port to the default port (:36658), then they should override both the client and server configurations `--proxy_app` and `--address` on startup.
closes: #4936
=> fix: ensure remote abci conn ports are aligned

specs/src/proto/types.proto
Replaced the outdated reference to the Decimal type specification in types.proto with the correct, up-to-date link:
https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#decimal
This ensures the documentation comment points to an existing and relevant section in the Celestia specs.
=> docs(specs): Fix Decimal type spec link to current location

cmd/celestia-appd/cmd/root.go, multiplexer/abci/multiplexer.go
Partially fixes: https://github.com/celestiaorg/celestia-app/issues/4968
ref: https://github.com/celestiaorg/celestia-app/issues/4968#issuecomment-2958215472
The log options weren't as well passed down when using the `--log-to-file` flag in the app command on v4.
Another PR comes for the fix in v3 as well.
=> fix(cmd): pass down log options

.github/workflows/goreleaser.yml
Fixes #4869 
- updates the runner to be set to ubuntu-8 github managed, non shared runner
=> chore(ci): update runner

.goreleaser.yaml, Makefile, internal/embedding/data.go
Need this before we create v4.0.3-mocha
=> chore: bump to v3.10.2-mocha

test/cmd/txsim/cli.go, test/txsim/blob.go
This PR adds a flag to allow a set of one or more predefined namespaces for txsim to use for blob submission. If more than one namespace is provided, it will choose a namespace at random for blob submission. 
```
--namespace <28 byte hex encoded V0 string> --namespace <28 byte hex encoded V0 string>
```
There is no way to currently ensure every defined namespace lands in every block (if 2 or more are provided), but we can add a feature later that disables the randomisation of `blobsPerPFB` per block.
=> feat(test/cmd/txsim): Allow predefined set of namespaces for blob submission

.github/copilot-setup-steps.yml
Updates all instances of actions/cache@v3 to actions/cache@v4
Changes:
Updates all instances of actions/cache@v3 to actions/cache@v4
Reference:
Latest version confirmation: https://github.com/actions/cache/releases/tag/v4.2.3
This update ensures we're using the most recent stable version of the GitHub cache action across our CI/CD pipelines, with improved security features like masking of SAS tokens in debug logs.
=> ci: update actions/cache to v4

.goreleaser.yaml
Closes https://github.com/celestiaorg/celestia-app/issues/5057
```
make goreleaser-check
```
passes
=> fix: goreleaser config by replacing deprecated fields

app/encoding/blob_tx_decoder.go
Noticed that we were using an outdated version of decoding the blob tx (which now resides in go-square instead of tendermint)
=> fix: use go-square to unmarshal blob tx instead of tendermint

tools/talis/deployment.go, tools/talis/digital_ocean.go
Without this rate limiting, DO rejects requests for networks > 20 validators because of too many requests. This limits the number of requests to 10 a time.
=> chore: rate limit creation/destruction of DO droplets

.github/dependabot.yml
Closes https://github.com/celestiaorg/celestia-app/issues/4929
Closes https://github.com/celestiaorg/celestia-app/issues/5080
I couldn't find a native solution in Dependabot to bump dependencies in multiple `go.mod`s in one PR. Based on docs [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--) and [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates).
Instead this PR:
- Decreases the frequency from daily to weekly
- Configured Dependabot to create PRs for test/docker-e2e and test/interchain. I think that we can merge those PRs before merging the one that bumps the root `go.mod`
Note: this isn't a 100% solution but should mitigate the problem.
=> ci(dependabot): reduce frequency of dependabot

cmd/celestia-appd/cmd/init.go
Closes https://github.com/celestiaorg/celestia-app/issues/4891 by implementing option 1 from https://github.com/celestiaorg/celestia-app/issues/4891#issuecomment-3000526542
```
$ celestia-appd init foo --chain-id celestia
The chain ID celestia is a public network.
Please download the genesis file via:
celestia-appd download-genesis celestia
...
```
=> feat: add log to download-genesis after init

docker/txsim/README.md
Corrected typos in volume mount paths from "txsimp" to "txsim" in Docker Compose and Kubernetes Deployment examples.
=> docs: fix typos in txsim Docker Image Usage Guide

multiplexer/abci/multiplexer.go, multiplexer/appd/run.go, multiplexer/appd/run_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/5194
The problem was that v3 wasn't fully stopped before v4 started. v4 tried to access the db before v3 fully released it. The fix is to wait for v3 to fully stop in the `Stop` command.
```
./scripts/single-node-upgrades.sh
...
8:33PM INF stopping embedded app for version active_app_version=3 module=server
Error: 130
2025/07/08 20:33:12 Process finished with error: exit status 1
8:33PM INF using latest app app_version=4 module=server
8:33PM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0x14002bc4fc0, circuit}" version=36
8:33PM INF Upgrading IAVL storage for faster queries + execution on live state. This may …
```
=> fix(multiplexer): wait for v3 app to stop before starting v4

scripts/mainnet.sh
I tested Evan's state sync PR by running this script successfully. 
The `--upgrade-height-v2` flag is deprecated on v4 and doesn't work.
I updated the seeds on Mainnet by using https://itrocket.net/services/testnet/celestia/community/seeds/
=> chore(scripts): improve mainnet state sync script

Makefile
Closes: https://github.com/celestiaorg/celestia-app/issues/5222
Because I was foolish and ignorant, in my earlier v5 PR, I downloaded the multiplexer binary of v4 instead of the standalone one. When running v5, it recognised it was v4 and tried to run the v4 multiplexer. We had multiplexers within multiplexers
Fortunately, this was an easy fix. I've tested manually and it seems to be working.
=> fix(statesync): download the standalone v4 binary instead

go.mod, go.sum
bumps core to fix the EventAttributeUnmarshalling
part of #5205 in that we can't we can't query events that were indexed before the multiplexer was used.
=> chore: bump core to fix EventAttribute unmarshalling

cmd/celestia-appd/cmd/modify_root_command_multiplexer.go
I was observing this message in the logs:
```
Flag --v2-upgrade-height has been deprecated, This flag is deprecated and was only useful prior to v4.
```
This was coming about because, the v2UpgradeHeight flag was being set to both the v3 and v4 binary when it only needs to be set for v3
=> fix: apply v2 upgrade height to v3 binary only

docs/architecture/adr-002-qgb-valset.md
Remove "fix last e2e tests" text from the ValSetConfirm section header that was accidentally included in the documentation
=> typo: Remove development note from section header

test/docker-e2e/dockerchain/config.go, test/docker-e2e/e2e_upgrade_test.go, test/docker-e2e/go.mod, test/docker-e2e/go.sum, test/util/genesis/genesis.go
I wasn't sure if this would work correctly so I didn't want to ask you to do these changes and waste your time.
Key points:
- don't need to use a separate function exec on running container
- fixed ordering of key names so they are mapped correctly to validators
- use the existing Exec fn (need to pass in home and node)
- removed additional entries to genesis and made it work with default
- removed pin
I think we could move the --home / --node args into a reusable fn and not need to specify them all the time.
=> test: update test to use existing tastora fns

go.mod, go.sum, test/docker-e2e/go.mod, test/docker-e2e/go.sum
Just waiting for CI to pass and I will cut the final release of go-square
=> fix: update go mod to v2.3.1 of go-square

specs/src/state_machine_modules_v1.md, specs/src/state_machine_modules_v2.md, specs/src/state_machine_modules_v3.md
A recent PR deleted x/tokenfilter from main which caused the links in the specs to break. This should fix markdown-link-check by using permalinks to the x/tokenfilter README.m
=> docs: fix tokenfilter link

.github/workflows/markdown-linter.yml
This PR updates the GitHub Actions workflow to use Node.js 24 instead of 18.
Node.js 24 includes updated V8, npm 11, and other performance and compatibility improvements.
The node-version field in markdown-linter.yml has been changed accordingly.
No other changes were required. CI and lint checks run successfully under the new version.
Reference: [Node.js 24.4.1 release notes](https://github.com/nodejs/node/releases/tag/v24.4.1)
=> ci: upgrade to Node.js 24

x/blob/types/genesis.go
Fix incorrect documentation in blob/types/genesis.go by removing references to "capability" module from comments. These comments were incorrectly copied from the capability module and should refer only to the blob module functionality
=> docs: fix comments

.goreleaser.yaml
Goreleaser is failing to attach binaries because the download_binary.sh script was renamed.
See: https://github.com/celestiaorg/celestia-app/actions/runs/16601565878/job/46962549875#step:7:74
=> fix(goreleaser): download_binary script name

x/mint/types/minter.go
The comment for the CalculateInflationRate function incorrectly referenced "block height" as the basis for inflation calculation. This has been updated to "block time" to accurately reflect the function's logic, which uses the current block time from the context. This change improves code clarity and helps prevent confusion for future maintainers. No functional code changes were made.
=> docs(x/mint): fix comment 

.goreleaser.yaml, Makefile, docker/multiplexer.Dockerfile, internal/embedding/data.go, test/docker-e2e/dockerchain/config.go, test/docker-e2e/e2e_test.go
v4.1.0-arabica -> v4.1.0
also noticed a v4.0.7-mocha instance in the e2e test which has been switched as well
=> chore(deps): upgrade embedded binary to celestia-app v4.1.0

scripts/single-node.sh
noticed the `sed -i'.bak'` syntax was causing issues on GNU/Linux, since it expects a space after `-i` when providing a backup extension.
replaced it with the more portable `-i.bak`, which works consistently across both macOS and Linux.
p.s.everything else stays the same - just fixing the compatibility hiccup.
=> fix: cross-platform `sed` syntax for better compatibility

multiplexer/abci/multiplexer_test.go
Rename Test_getProgramArgs to TestRemoveStart to accurately reflect
that the test is testing the removeStart function, not getProgramArgs.
=> test: rename test function to match tested function

go.mod, go.sum, test/interchain/go.mod, test/interchain/go.sum
Part of https://github.com/celestiaorg/celestia-app/issues/4370
Upgrades to a Cosmos SDK release with
https://github.com/celestiaorg/cosmos-sdk/pull/635 to hopefully restore the ability to sync from genesis with a single binary (the latest multiplexer binary) with a v3 embedded binary cut after this merges.
=> fix: UnpackAny limit for historical blocks

docs/architecture/adr-006-non-interactive-defaults.md, docs/architecture/adr-008-square-size-independent-message-commitments.md
1. Removes a development comment in ADR-006 (line 73) that was not meant to be included in the final version. The comment was asking whether a specific rule should be included and tagging a contributor for feedback.
2. Fixes inconsistent repository links in ADR-008. Updates an outdated link to the celestiaorg/rollmint repository to point to the current rollkit/rollkit repository, ensuring both references in the document point to the same location.
=> docs: fix inconsistencies in ADR documentation

multiplexer/abci/multiplexer.go
Replace m.nativeApp with version.AppVersion in error message on line 500 of multiplexer.go. The %d format specifier requires a numeric value, but m.nativeApp is an application object
=> refactor(multiplexer): improve error message

test/docker-e2e/e2e_simple_test.go
This is a followup PR for #5456 to remove redundant code from the test.
context: https://github.com/celestiaorg/celestia-app/pull/5456#discussion_r2257871844
=> chore: removed redundant code from PFB tx upgrade test

test/docker-e2e/e2e_block_sync_test.go, test/docker-e2e/e2e_full_stack_pfb_test.go, test/docker-e2e/e2e_simple_test.go, test/docker-e2e/e2e_state_sync_test.go, test/docker-e2e/e2e_test.go, test/docker-e2e/e2e_upgrade_test.go
hack to give the e2e liveness check some breathing room and also just refactor.
the best fix would involve doing a more complex check to see if a node actually halted and if so for what reason. This is not that, therefore doesn't cl0se #5481 imo, however might (at least for now) close #5478
likely reduces flakiness
=> fix: refactor the e2e liveness check

Makefile, app/app.go, app/default_overrides.go, app/default_overrides_test.go, app/ica_host.go, app/ica_host_test.go, app/upgrades.go, app/upgrades_test.go, scripts/single-node-all-upgrades.sh, scripts/single-node.sh, test/util/test_app.go
Closes https://github.com/celestiaorg/celestia-app/issues/5400
On v5
```
$ celestia-appd query ica host params
Error: rpc error: code = Unknown desc = unknown query path: unknown request
```
On v6
```
$ celestia-appd query ica host params
Error: rpc error: code = Unknown desc = unknown query path: unknown request
$ celestia-appd query ica host params
allow_messages:
- /ibc.applications.transfer.v1.MsgTransfer
- /cosmos.bank.v1beta1.MsgSend
- /cosmos.staking.v1beta1.MsgDelegate
- /cosmos.staking.v1beta1.MsgBeginRedelegate
- /cosmos.staking.v1beta1.MsgUndelegate
- /cosmos.staking.v1beta1.MsgCancelUnbondingDelegation
- /cosmos.distribution.v1beta1.MsgSetWithdrawAddress
- /cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward
- /cosmos.distribution.v1beta1.MsgFundCommunityPool
- …
```
=> fix!: set ICA params during v6 upgrade handler

Makefile
Closes https://github.com/celestiaorg/celestia-app/issues/5510
```
make install
celestia-appd version --long
...
build_tags: ledger,multiplexer
```
```
make install-standalone
celestia-appd version --long
...
build_tags: ledger
```
=> fix(Makefile): populate the build tags in version output

.github/workflows/test.yml, Makefile
The workflow was specifying the test suite but the command actually requires it to be the name of the test entrypoint.
I renamed the var to be "entrypoint" rather than suite because I think that's a little more clear.
=> chore: fix ibc test workflow

app/upgrades.go, app/upgrades_test.go, pkg/appconsts/app_consts.go, scripts/min-commission-rate-proposal-v1.json, scripts/min-commission-rate.sh, scripts/single-node.sh, test/util/test_app.go, x/mint/README.md, x/mint/client/testutil/grpc_test.go, x/mint/client/testutil/suite_test.go, x/mint/keeper/abci_test.go, x/mint/types/constants.go, x/mint/types/minter_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/5435
1. Decrease inflation
2. Increase MinComissionRate from 5% to 10%
The upgrade handler in this PR will attempt to update the commission rate for validators to the new min commission rate if the validator's commission rate was previously below that. However, the update will fail for certain validators (example: [SmartStake](https://celenium.io/validator/82827?tab=Delegators)) who have set a max rate that is lower than the new min rate. I also expect it to fail for validators with a small `MaxChangeRate`.
1. https://github.com/celestiaorg/celestia-app/issues/5528
=> feat!: implement CIP-41

tools/talis/docker/Dockerfile
Because it takes a lot of time to regenerate celestia-node Docker image and it is currently unused
=> chore(talis): remove celestia-node

Makefile, README.md, cmd/celestia-appd/cmd/bbr.go, scripts/arabica.sh, scripts/block-sync.sh, scripts/build-run-single-node.sh, scripts/mainnet.sh, scripts/mocha-halt.sh, scripts/mocha.sh, scripts/single-node-all-upgrades.sh, scripts/single-node-halt.sh, scripts/single-node-upgrades.sh, scripts/single-node.sh
Closes #3853 
On MacOS
```
$ make check-bbr
Checking if BBR is enabled...
BBR is not available on non-Linux systems.
$ make enable-bbr
Configuring system to use BBR...
BBR is not available on non-Linux systems.
```
On Linux
```shell
root@rootulp-scaleway:~/celestia-app# make enable-bbr
Configuring system to use BBR...
BBR is not enabled. Configuring BBR...
tcp_bbr
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
BBR has been enabled.
root@rootulp-scaleway:~/celestia-app# make check-bbr
Checking if BBR is enabled...
BBR is enabled.
```
=> refactor: skip BBR check on non-Linux machines

test/docker-e2e/e2e_ibc_test.go
`"github.com/celestiaorg/tastora/framework/docker"`  was imported twice.
I remove the duplicate import to make the code cleaner and more readable.
=> refactor: remove duplicate package import

app/app.go, app/grpc/gasestimation/gas_estimator.go, app/grpc/gasestimation/gas_estimator_e2e_test.go, pkg/appconsts/initial_consts.go, pkg/user/tx_client_test.go
Ref: https://github.com/celestiaorg/celestia-app/issues/5162
To ensure a smooth transition, we will bump the min fee on the estimation side in the v0.5.x that the v6 multiplexer imports. This way, users will already be submitting with the higher min fee prior to the upgrade to v6
=> feat: bump min gas price estimation

x/minfee/module.go, x/signal/module.go, x/signal/types/codec.go
Fix incorrect module references in function comments that were copied from blob module
- x/minfee/module.go: Fix "blob module" → "minfee module" in RegisterLegacyAminoCodec comment
- x/signal/module.go: Fix multiple "blob module" → "signal module" references in comments
- x/signal/types/codec.go: Fix "upgrade module" → "signal module" in RegisterInterfaces comment
=> docs: correct module references in function comments

pkg/wrapper/nmt_wrapper.go
The Push method comment incorrectly referenced DefaultNamespaceIDLen which doesn't exist. 
Updated to reference share.NamespaceSize which is actually used in the implementation.
=> docs: replace undefined DefaultNamespaceIDLen with share.NamespaceSize in comment

x/mint/module.go
The comment for NewAppModule function mentioned a non-existent InflationCalculationFn parameter and described behavior that doesn't match the actual function signature. The function only accepts three parameters: cdc, keeper, and ak.
=> docs(x/mint): remove outdated comment about InflationCalculationFn

app/app.go
Remove redundant zero capacity parameter from map initialization in **app/app.go.**
The second parameter in make(map[K]V, 0) is a capacity hint that serves no purpose when set to zero. This change follows Go idioms and removes unnecessary code without changing behavior.
=> refactor: remove unnecessary zero capacity from map initialization

test/docker-e2e/dockerchain/testchain.go
Update the comment example in test/docker-e2e/dockerchain/testchain.go to use tastoracontainertypes.NewImage(...) instead of the non-existent NewDockerImage(...), and fix the missing closing parenthesis. This avoids misleading readers toward an API that doesn’t exist and aligns the example with the actual tastora container API used across the codebase.
=> docs(docker-e2e): fix image constructor in comment example

pkg/user/tx_client.go
CI on main has been failing since https://github.com/celestiaorg/celestia-app/pull/5675/files merged. The PR that merged right before it started using the `signer` in that method: https://github.com/celestiaorg/celestia-app/pull/5582/files
=> fix: unused params regression

test/txsim/run.go
Remove incorrect RPC endpoint requirement from Run function documentation.
Function only accepts grpcEndpoint parameter and uses gRPC for all operations.
RPC is only used in tests for validation, not in main function logic.
=> docs(txsim): correct Run function documentation to reflect actual gRPC-only usage

pkg/user/tx_client_test.go
- Fix incorrect comment in assertTxInTxTracker function that claimed sequence does not increase, when it actually validates sequence increases by 1
- Remove leftover refactoring comment "Changed from error to bool" in broadcastTestCase struct
=> docs(pkg/user): fix misleading comment

pkg/proof/proof_test.go
Update the test case name from “square size of 32” to “square size of 64”. The test uses endingShare 4097, which is just beyond 4096 (64×64), not 1024 (32×32). The previous label was misleading and could confuse readers about the intended boundary condition being tested.
=> test(pkg/proof): fix test name

pkg/proof/querier.go
Fixed comment that incorrectly referenced `Querier` instead of actual function name, and corrected non-existent `prove.QueryPath` reference.
=> docs: improve comment

test/txsim/sequence.go
Fix typo in Next() method documentation - replace EndOfSequence with ErrEndOfSequence to match actual variable name used in code implementations.
=> docs(txsim): fix name of error in comment

scripts/archive-node.sh
Script to start an archive node on Mainnet. Used for debugging an issue unique to archive nodes.
```
./scripts/archive-node.sh
```
started block syncing a node on Mainnet.
=> chore(scripts): archive-node

docker/multiplexer.Dockerfile, docker/standalone.Dockerfile
Updates runtime base to alpine:3.20 for security fixes and consistency with txsim.
=> chore: upgrade to alpine 3.20

.goreleaser.yaml, Makefile, docker/multiplexer.Dockerfile, internal/embedding/data.go, test/docker-e2e/dockerchain/config.go
Upgrade multiplexer to the latest v5.x release
=> chore: upgrade multiplexer to v5.0.10

Makefile
Found inconsistent shell variable escaping on line 449. Initially wasn't sure if this was actually a bug, so I tested the behavior.
Created test Makefiles and discovered the key issue:
- $(shell sysctl ...) executes during Makefile parsing
- $$(sysctl ...) executes during target execution  
For BBR status checking, this is critical - we need to check system state at runtime, not when reading the file.
Verified the rest of the code - lines 432 and 470 already use correct $$ escaping. Line 449 was the only exception.
Tested the fix - `make enable-bbr` works correctly.
=> fix: correct shell variable escaping in enable-bbr target

pkg/wrapper/buffered_tree.go, pkg/wrapper/nmt_wrapper.go
- Remove options []nmt.Option from ErasuredNamespacedMerkleTree and resizeableBufferTree.
- The nmt.Options are applied at construction time to nmt.New(...) and are never read afterward; the stored fields were dead state.
- This eliminates confusion about dynamic option use, reduces struct size, and prevents potential divergence between stored options and the actual NMT configuration.
- Matches how callers use the API (construction-time only), aligns with docs/tests, and introduces no behavioral change.
=> refactor(wrapper): remove unused options fields from NMT wrappers

docs/maintainers/modify-param.md
`submit-proposal` command was using `gov-proposal.json` instead of the expected `proposal.json`.
this update renames the file to match the command and ensures submissions work correctly.
=> docs: fix filename mismatch in proposal submission

go.mod, go.sum
This PR adds support for a mechanism to start/stop the legacy block prop mechanism. It introduces a param in `config.toml` called `enable_legacy_block_prop` which is set to `false` by default.
With this PR, we will the following params to control block prop:
```
enable_legacy_block_prop = false
disable_propagation_reactor = false
```
By default, these allow the new recovery reactor to run without the legacy block prop mechanism. However, in emergencies, we can ask nodes to set `enable_legacy_block_prop` to true to enable the legacy mechanism. And if needed, also disable the new recovery reactor.
I don't think it's worth adding flags like `celestia-appd start --enable-legacy-block-prop` because node operators can just change these in the config and restart.
Let me know if you agree or if …
=> chore: bump core to v0.39.7

pkg/user/mock_tx_server_test.go
Function is actually used in mock server setup and parallel tests
=> fix: remove incorrect nolint:unused annotation from defaultBroadcastHandler

test/util/testnode/config.go
- Replace outdated deprecation comment in `test/util/testnode/config.go`:
- from “Deprecated: Use WithBlockTime instead.”
- to “Deprecated: Use WithDelayedPrecommitTimeout instead.”
- The referenced `WithBlockTime` does not exist. Pointing to `WithDelayedPrecommitTimeout` prevents confusion and misuse.
=> fix: deprecated note in testnode config to reference WithDelayedPrecommitTimeout

test/util/testnode/utils.go
Replace duplicated UDP port allocation logic in MustGetFreePort() with a call to existing GetFreePort() function. This eliminates 12 lines of redundant code while maintaining identical behavior
=> refactor: remove duplicate code in MustGetFreePort function
